### ISSUE TITLE
AlphaFold (2.3.x)

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#100]
* link to support ticket: [#2023022760000621](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=111952)
* website: https://github.com/deepmind/alphafold
* installation docs: https://github.com/deepmind/alphafold#installation-and-running-your-first-prediction
* toolchain: `foss/2022a`
* easyblock to use: *(see existing `AlphaFold` easyconfigs)*
* required dependencies:
  * *(see existing `AlphaFold` easyconfigs)*
* notes:
  * ...
* effort: *(TBD)*

**Comment by boegel** [comment]
PR for AlphaFold 2.3.0 with `foss/2021b` merged at https://github.com/easybuilders/easybuild-easyconfigs/pull/16874

AlphaFold 2.3.1 with `foss/2022a` requires that there's a TensorFlow easyconfig with `foss/2022a`, see for example https://github.com/easybuilders/easybuild-easyconfigs/pull/17241 or https://github.com/easybuilders/easybuild-easyconfigs/pull/17092

**Comment by lexming** [comment]
@boegel we just got a request for this in VUB, thanks for the timely merge :heart:

**Comment by lexming** [comment]
PRs for AlphaFold 2.3.0 and 2.3.1 are already merged upstream.

Closing.
