### ISSUE TITLE
KrakenUniq

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#102]
* link to support ticket: [#2023021460001804](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=110217)
* website: https://github.com/fbreitwieser/krakenuniq
* installation docs: https://github.com/fbreitwieser/krakenuniq#installation
* toolchain: `foss/2022a`
* easyblock to use: `Tarball`?
* required dependencies:
  * [ ] Jellyfish
* notes:
  * ...
* effort: *(TBD)*

**Comment by deniskristak** [comment]
cleaned up, closing
