### ISSUE TITLE
DeePMD-kit

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#107]
* link to support ticket: [#2023021760001326](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=110655)
* website: https://docs.deepmodeling.com/projects/deepmd
* installation docs: https://github.com/deepmodeling/deepmd-kit/blob/master/doc/install/install-from-source.md
* toolchain: `foss/2022a`
* easyblock to use: `???`
* required dependencies:
  * TensorFlow
  * for Python dependencies, see https://github.com/deepmodeling/deepmd-kit/blob/master/pyproject.toml
* notes:
  * need both Python and C++ interface (for use with LAMMPS)
  * should wait until [PR for TensorFlow with `foss/2022a`](https://github.com/easybuilders/easybuild-easyconfigs/pull/17241) is merged
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
- other install methods
- conda:
    - https://anaconda.org/conda-forge/deepmd-kit

**Comment by laraPPr** [comment]
User Installed it themselves
