### ISSUE TITLE
DRAGMAP

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#11]
* link to support ticket: [HPC-UGent OTRS t#2022062760001123 ](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=84363)
* website: https://github.com/Illumina/DRAGMAP
* installation docs: https://github.com/Illumina/DRAGMAP/tree/master#install
* toolchain: `foss/2021b` (or `gompi/2021b` due to `Boost` dependency)
* easyblock to use: `ConfigureMake` (with `skipsteps = ['configure']`)
* required dependencies:
  * see https://github.com/Illumina/DRAGMAP/tree/master#prerequisites
* notes:
  * control compiler (`CC="$CC" CXX="$CXX"`) + dependency locations via `buildopts`, see https://github.com/Illumina/DRAGMAP/tree/master#other-variables-controlling-the-build-process
  * replace hardcoded `-msse4.2 -mavx2 ` in `config.mk` with `$CXXFLAGS` value via `sed` in `prebuildopts`
* effort: *(TBD)*

**Comment by ItIsI-Orient** [comment]
PR Open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16532

**Comment by ItIsI-Orient** [comment]
PR merged, cleaning up
