### ISSUE TITLE
funannotate

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#114]
* link to support ticket: [#2023031360001037](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=113595)
* website: https://funannotate.readthedocs.io
* installation docs: https://funannotate.readthedocs.io/en/latest/install.html
* toolchain: `foss/2021b`
* easyblock to use: `...`
* required dependencies:
  * see https://github.com/nextgenusfs/funannotate/blob/master/setup.py
* notes:
  * requires Python 3.9?
* effort: *(TBD)*

**Comment by boegel** [comment]
PR open: https://github.com/easybuilders/easybuild-easyconfigs/pull/17588

**Comment by PetrKralCZ** [comment]
- other install methods
- container image/recipe:
    - https://hub.docker.com/r/nextgenusfs/funannotate
- conda:
    - https://anaconda.org/bioconda/funannotate

**Comment by PetrKralCZ** [comment]
PR merged. Closing...
