### ISSUE TITLE
CASPR

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#116]
* link to support ticket: [#2023031760000611](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114388)
* website: https://judithbergada.github.io/CASPR
* installation docs: https://judithbergada.github.io/CASPR/installation
* toolchain: `foss/2022a`
* easyblock to use: `Tarball`?
* required dependencies:
  * see https://judithbergada.github.io/CASPR/installation/#conda-environment-installation
* notes:
  * ...
* effort: *(TBD)*

**Comment by deniskristak** [comment]
cleaned up
