### ISSUE TITLE
DiCE

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#117]
* link to support ticket: [#2023031760000647](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114391)
* website: https://interpret.ml/DiCE
* installation docs: https://interpret.ml/DiCE/readme.html#installing-dice
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/interpretml/DiCE/blob/main/requirements.txt
* notes:
  * *not* the same as `Dice` (https://github.com/easybuilders/easybuild-easyconfigs/pull/16752)
* effort: *(TBD)*

**Comment by deniskristak** [comment]
this can be closed, as PR has been merged
