### ISSUE TITLE
turbinesFoam

### ISSUE THREAD

**Issue by smoors** [vscentrum/vsc-software-stack#120]
* link to support ticket: INC0139905
* website: https://github.com/turbinesFoam/turbinesFoam
* installation docs: ...
* toolchain: `...`
* easyblock to use: `...`
* required dependencies:
  * [ ] OpenFOAM
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*

**Comment by smoors** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17917

**Comment by ItIsI-Orient** [comment]
PR merged, closing
