### ISSUE TITLE
MONAI Label

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#122]
* link to support ticket: [#2023032160000915](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114750) + [#2023051760000492](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=120469) + [#2023100360001935](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=134145)
* website: https://docs.monai.io/projects/label
* installation docs: https://docs.monai.io/projects/label/en/latest/installation.html
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] PyTorch (1.12.1) + CUDA 11.7.0
  * [x] torchvision
  * [x] torchaudio
* notes:
  * see https://pypi.org/project/monailabel
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
- other install methods
- container image/recipe:
    - https://hub.docker.com/r/projectmonai/monailabel

**Comment by PetrKralCZ** [comment]
PRs
torchaudio dependency:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18139

**Comment by PetrKralCZ** [comment]
Latest version `0.7.0` would require `MONAI 1.2.0`. For `foss/2022a` we have `MONAI 1.0.1`.
Latest usable version of `MONAI Label` for `foss/2022a` is `0.5.2`:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18180

**Comment by boegel** [comment]
PR merged, ready for cleanup
