### ISSUE TITLE
ColabFold

### ISSUE THREAD

**Issue by lexming** [vscentrum/vsc-software-stack#123]
* link to support ticket: INC0139706 (VUB)
* website: https://github.com/sokrypton/ColabFold
* installation docs: 
* toolchain: `foss/2022a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [x] alphafold-colabfold
  * [x] py3Dmol
* notes:
  * ColabFold depends on a special fork of AlphaFold: https://github.com/sokrypton/alphafold
* effort: *annoying because of the fork*

**Comment by lexming** [comment]
PR:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17751

**Comment by boegel** [comment]
@lexming PRs merged, so this can be closed?

**Comment by lexming** [comment]
Indeed
