### ISSUE TITLE
pytorch-image-models (timm)

### ISSUE THREAD

**Issue by smoors** [vscentrum/vsc-software-stack#126]
* link to support ticket: INC0141353
* website: https://github.com/huggingface/pytorch-image-models#introduction
* installation docs: ...
* toolchain: `...`
* easyblock to use: `...`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*

**Comment by smoors** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17787

**Comment by PetrKralCZ** [comment]
other install methods
- conda:
    - https://anaconda.org/conda-forge/timm

**Comment by boegel** [comment]
@smoors PR merged, so this can be closed?
