### ISSUE TITLE
CatBoost

### ISSUE THREAD

**Issue by hajgato** [vscentrum/vsc-software-stack#128]
* link to support ticket: https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=118422
* website: https://catboost.ai/
* installation docs: https://catboost.ai/en/docs/concepts/python-installation
* toolchain: `???`
* easyblock to use: `???`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
- other install methods
- conda:
    - https://anaconda.org/conda-forge/catboost
- pre-built binaries:
    - https://github.com/catboost/catboost/releases

**Comment by deniskristak** [comment]
closing, finished
