### ISSUE TITLE
CDO (Python)

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#132]
* link to support ticket: [#2023032160001414](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114800)
* website: https://pypi.org/project/cdo
* installation docs: https://pypi.org/project/cdo
* toolchain: `foss/2021b`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [x] Python (incl. six)
  * [x] CDO
* notes:
  * ...
* effort: *(TBD)*

**Comment by lexming** [comment]
We already have this! see: https://github.com/easybuilders/easybuild-easyconfigs/pull/16669

**Comment by lexming** [comment]
I'll let you grab it for a :beer:

**Comment by boegel** [comment]
Oh excellent, thanks!

I totally overlooked that because there's no clear link from https://pypi.org/project/cdo/ to https://github.com/Try2Code/cdo-bindings
