### ISSUE TITLE
GapFiller

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#134]
* link to support ticket: [#2023032160001343](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114793)
* website: https://sourceforge.net/projects/gapfiller
* installation docs: https://sourceforge.net/projects/gapfiller/files/v2.1.2/README/download
* toolchain: `GCC/11.3.0`
* easyblock to use: `ConfigureMake`
* required dependencies:
  * [x] Boost
  * [x] zlib
* notes:
  * see old easyconfigs @ https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/g/GapFiller
* effort: *(TBD)*
* other install methods
  * conda: https://anaconda.org/bioconda/gapfiller
  * container image: ❌ 
  * pre-built binaries (RHEL8 Linux x86_64): ❌ 
  * easyconfig outside EasyBuild: ❌

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/17920

**Comment by laraPPr** [comment]
Installed and user was informed
OTRS ticket closed since 17/05/2023
