### ISSUE TITLE
CmdStanR

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#136]
* link to support ticket:[ #2023050260001054](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=119192)
* website: [https://mc-stan.org/cmdstanr/](https://mc-stan.org/cmdstanr/)
* installation docs: [https://github.com/stan-dev/cmdstanr](https://github.com/stan-dev/cmdstanr)
* toolchain: `foss/2022a`
* easyblock to use: `...`
* required dependencies:
  * [x] R
  * [x] CmdStan
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes

**Comment by laraPPr** [comment]
I have a working updated easyconfig for this

**Comment by boegel** [comment]
@laraPPr Can you add your easyconfig to a new `136_CmdStanR` directory in the `wip` branch of this repository?

Cfr. https://github.com/vscentrum/vsc-software-stack/tree/wip#work-in-progress-wip-branch

**Comment by laraPPr** [comment]
CmdStanR is dependend on CmdStan which does not have an easyconfig yet. At the moment CmdStanR installs CmdStan locally. Which means that researcher is not hindered by the fact that CmdStan is not available as a module. 

I started working on the easyconfig for CmdStan and this is what it looks like at the moment:
``` 
easyblock = 'MakeCp'

name = 'CmdStan'
version = '2.32.2'

homepage = 'https://mc-stan.org/users/interfaces/cmdstan'
description = 'CmdStan is the command line interface to Stan'

toolchain = {'name': 'GCC', 'version': '11.3.0'} 


source_urls = ['https://github.com/stan-dev/cmdstan/archive/refs/tags/']
sources = ['v%(version)s.tar.gz']

buildopts = 'build'

files_to_copy = None
```

I run in to the following error:
```
Build of /kyukon/data/gent/461/vsc46128/easybuildrepos/Personalconfigs/CmdStan-2.23.2-GCC-11.3.0.eb failed (err: 'build failed (first 300 chars): cmd " make  -j 16 build" exited with exit code 2 and output:\nmake: *** No rule to make target \'stan/src/stan/model/model_header.hpp\', needed by \'stan/src/stan/model/model_header.hpp.gch\'.  Stop.\nmake: *** Waiting for unfinished jobs....\n\ncurl -L https://github.com/stan-dev/stanc3/releases/download/n')
```

intersting part of log file:
```
== 2023-07-04 15:02:51,723 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): cmd " make  -j 16 build" exited with exit code 2 and output:
make: *** No rule to make target 'stan/src/stan/model/model_header.hpp', needed by 'stan/src/stan/model/model_header.hpp.gch'.  Stop.
make: *** Waiting for unfinished jobs....

curl -L https://github.com/stan-dev/stanc3/releases/download/nightly/linux-stanc -o bin/stanc --retry 5 --retry-delay 10
--- Compiling the main object file. This might take up to a minute. ---
g++ -O2 -ftree-vectorize -march=native -fno-math-errno   -c -o src/cmdstan/main.o src/cmdstan/main.cpp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
src/cmdstan/main.cpp:1:10: fatal error: cmdstan/command.hpp: No such file or directory
    1 | #include <cmdstan/command.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [make/program:14: src/cmdstan/main.o] Error 1
100 13.4M  100 13.4M    0     0  16.6M      0 --:--:-- --:--:-- --:--:-- 20.5M
chmod +x bin/stanc
 (at easybuild/tools/run.py:643 in parse_cmd_output)
```

I also found [this issue](https://discourse.mc-stan.org/t/run-cmdstan-on-linux-error-1-no-such-file-or-directory/19470/7) which seems similar.
