### ISSUE TITLE
Hydra plugins: hydra-submitit-launcher + hydra-optuna-sweeper

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#137]
* link to support ticket: [#2023032160001549](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114813)
* website: https://hydra.cc/docs/plugins/submitit_launcher/ + https://hydra.cc/docs/plugins/optuna_sweeper/
* installation docs: https://hydra.cc/docs/plugins/submitit_launcher/#installation + https://hydra.cc/docs/plugins/optuna_sweeper/#installation
* toolchain: `GCCcore/11.3.0`
* easyblock to use: *(see existing easyconfig)*
* required dependencies:
  * [ ] Hydra
* notes:
  * should be installed as extensions with [`Hydra`](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/h/Hydra) ?
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/19244

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21977
- based on https://github.com/easybuilders/easybuild-easyconfigs/pull/19244

**Comment by laraPPr** [comment]
How much time did you spend on this @pavelToman

**Comment by laraPPr** [comment]
Reminder for after Holidays: started installation on Tier-2

**Comment by pavelToman** [comment]
> How much time did you spend on this @pavelToman

2h

**Comment by laraPPr** [comment]
Installed and informed user
