### ISSUE TITLE
bioBakery workflows

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#138]
* link to support ticket: [#2023032260001092](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114924)
* website: https://huttenhower.sph.harvard.edu/biobakery_workflows
* installation docs: https://github.com/biobakery/biobakery_workflows/wiki/Installing-the-workflows-with-pip
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] Kneaddata
  * [ ] HUMAnN (see `humann-3.6-foss-2022a.eb`?)
  * [x] MetaPhlAn
  * [ ] AnADAMA2
* optional dependencies:
  * [ ] biom-format
* notes:
  * use separate easyconfigs for the different dependencies listed with their own `pip install` command in https://github.com/biobakery/biobakery_workflows/wiki/Installing-the-workflows-with-pip
  * check whether databases can easily be downloaded to a specific directory (not included in the installation), see https://github.com/biobakery/biobakery_workflows#install-databases
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/biobakery/biobakery_workflows#installation)
  * container image: yes (https://github.com/biobakery/biobakery_workflows#installation)
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: ???

**Comment by deniskristak** [comment]
cleaned up, closing
