### ISSUE TITLE
AMICA

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#139]
* link to support ticket: [#2023032260001396](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114954)
* website: https://github.com/sccn/amica
* installation docs: https://github.com/sccn/amica#to-compile-with-intel-fortran-on-expanse-supercomputer
* toolchain: `intel/2022b` (or `foss/2022b`)
* easyblock to use: `CmdCp`?
* required dependencies:
  * [x] Fortran compiler
  * [x] MPI
* notes:
  * no proper versioning, so use datestamp of last commit
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no (only for Ubuntu, macOS, Windows)
  * easyconfig outside EasyBuild: ???

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19842

**Comment by boegel** [comment]
PR merged, ready for cleanup
