### ISSUE TITLE
 how_are_we_stranded_here 

### ISSUE THREAD

**Issue by hajgato** [vscentrum/vsc-software-stack#14]
* link to support ticket: https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=86074
* website: https://github.com/signalbash/how_are_we_stranded_here
* installation docs: https://github.com/signalbash/how_are_we_stranded_here 
* toolchain: `foss/2021b`
* easyblock to use: ???
* required dependencies:
  * [ ] Kallisto 0.44.0
  * [x] RSeQC 4.0.0
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*

**Comment by boegel** [comment]
@ItIsI-Orient Current draft easyconfig `how_are_we_stranded_here.eb` works for me as long as I use `eb --parallel 1` (so you should probably add `parallel = 1` in the easyconfig itself.

Please also check if we can avoid that `htslib.a` is built from source, and whether it can be provided as a proper dependency instead (`HTSlib`)

**Comment by boegel** [comment]
Ready for cleanup, see https://github.com/easybuilders/easybuild-easyconfigs/pull/16220 + https://github.com/easybuilders/easybuild-easyconfigs/pull/16227
