### ISSUE TITLE
Sniffles

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#141]
* link to support ticket: [#2023032260001538](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114968)
* website: https://github.com/fritzsedlazeck/Sniffles
* installation docs: https://github.com/fritzsedlazeck/Sniffles#installation
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] Python
  * [x] Pysam
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/fritzsedlazeck/Sniffles#installation)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: yes
    * https://github.com/FredHutch/easybuild-life-sciences/tree/main/fh_easyconfigs/s/Sniffles
    * https://github.com/easybuilders/easybuild-easyconfigs/pull/4827

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18048

**Comment by boegel** [comment]
PR merged, ready for cleanup
