### ISSUE TITLE
cuteSV

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#142]
* link to support ticket: [#2023032260001547](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114969)
* website: https://github.com/tjiangHIT/cuteSV
* installation docs: https://github.com/tjiangHIT/cuteSV#installation
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/tjiangHIT/cuteSV/blob/master/setup.py#L24
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/tjiangHIT/cuteSV#installation)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
should be same toolchain generation as Sniffles (#141)

**Comment by PetrKralCZ** [comment]
> should be same toolchain generation as Sniffles (#141)

`Sniffles` is `GCC/11.3.0` but `cuteSV` needs `numpy`, so it needs to be `foss/2022a`, doesn't it?

**Comment by boegel** [comment]
Sure, `GCC/11.3.0` is compatible with `foss/2022a`, so no problem.

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18077

**Comment by boegel** [comment]
@PetrKralCZ PR merged, so ready for cleanup
