### ISSUE TITLE
NanoCaller

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#143]
* link to support ticket: [#2023032260001556](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114970)
* website: https://github.com/WGLab/NanoCaller
* installation docs: https://github.com/WGLab/NanoCaller/blob/master/docs/Install.md
* toolchain: `Tarball`
* easyblock to use: `foss/2022a`
* required dependencies:
  * see https://github.com/WGLab/NanoCaller/blob/master/environment.yml
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/WGLab/NanoCaller#installation)
  * container image: yes (https://github.com/WGLab/NanoCaller#installation)
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no?

**Comment by boegel** [comment]
should be same toolchain generation as Sniffles (#141)

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18587
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18588
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18592
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18593
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18594
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18628
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18629
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18636
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18726
