### ISSUE TITLE
SVIM

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#144]
* link to support ticket: [#2023032260001565](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=114971)
* website: https://github.com/eldariont/svim
* installation docs: https://github.com/eldariont/svim#installation
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/eldariont/svim#dependencies + https://github.com/eldariont/svim/blob/master/setup.py#L39
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/eldariont/svim#installation)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no?

**Comment by boegel** [comment]
should be same toolchain generation as Sniffles (#141)

**Comment by PetrKralCZ** [comment]
> should be same toolchain generation as Sniffles (#141)

`Sniffles` is `GCC/11.3.0` but `SVIM` needs `scipy` for example, so it needs to be `foss/2022a`, doesn't it?

**Comment by boegel** [comment]
> > should be same toolchain generation as Sniffles (#141)
> 
> `Sniffles` is `GCC/11.3.0` but `SVIM` needs `scipy` for example, so it needs to be `foss/2022a`, doesn't it?

Yes, and that's fine, just as long as `SVIM` and `Sniffles` can be loaded together. Since `GCC/11.3.0` is a subtoolchain of `foss/2022a`, that should pose no problem.

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18071

**Comment by boegel** [comment]
PR merged, ready for cleanup...
