### ISSUE TITLE
NanoStat

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#148]
* link to support ticket: [#2023032860000395](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=115555)
* website: https://github.com/wdecoster/nanostat
* installation docs: https://github.com/wdecoster/nanostat#installation
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * nanoget + nanomath, cfr. https://github.com/wdecoster/nanostat/blob/master/setup.py#L33
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/bioconda/nanostat)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18201

**Comment by boegel** [comment]
PR merged, ready for cleanup
