### ISSUE TITLE
Transformers

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#151]
* link to support ticket: [#2023040360000653](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=116650)
* website: https://github.com/huggingface/transformers
* installation docs: https://github.com/huggingface/transformers#installation
* toolchain: `foss/2022b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * *(see existing easyconfig)*
* notes:
  * update of `Transformers-4.24.0-foss-2022a.eb`
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/huggingface/transformers#with-conda)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18200

**Comment by boegel** [comment]
PR merged, ready for cleanup
