### ISSUE TITLE
PyTorch + PyTorch-Lightning 2.0

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#154]
* link to support ticket: [#2023040660000764](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=117029) + [#2023070160000062](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=124510)
* website: https://pytorch.org
* installation docs: https://github.com/pytorch/pytorch#from-source
* toolchain: `foss/2022b`
* easyblock to use: *(see existing `PyTorch` easyconfigs)*
* required dependencies:
  * *(see existing `PyTorch` easyconfigs)*
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://pytorch.org/get-started/locally/#mac-anaconda)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
Some work has been done on this already in the EasyBuild community, for example by @branfosj, which we can work on top of, possible in collaboration with others.

**Comment by laraPPr** [comment]
@boegel can I close this one because this, https://github.com/easybuilders/easybuild-easyconfigs/pull/19573, is installed?

**Comment by boegel** [comment]
PR for PyTorch-Lightning:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/19964

**Comment by boegel** [comment]
[#19964](https://github.com/easybuilders/easybuild-easyconfigs/pull/19964) was merged, but isn't installed yet, I'll follow up on that and inform the researcher who requested it...

**Comment by boegel** [comment]
Now installed and informed user, so closing this...
