### ISSUE TITLE
Structure_threader

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#157]
* link to support ticket: [#2023041460000445](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=117546)
* website: https://github.com/StuntsPT/Structure_threader
* installation docs: https://structure-threader.readthedocs.io/en/latest/install/
* toolchain: `foss/2022b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] Python
  * [ ] see https://github.com/StuntsPT/Structure_threader/blob/master/setup.py#L78
  * [ ] see https://structure-threader.readthedocs.io/en/latest/external/
* notes:
  * make sure that no junk gets installed to `~/.local/bin`, see point 4 in `GNU/Linux` section at https://structure-threader.readthedocs.io/en/latest/install/
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18219
