### ISSUE TITLE
NanoStat

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#158]
* link to support ticket: [#2023041960001051](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=118174)
* website: https://github.com/wdecoster/nanostat
* installation docs: https://github.com/wdecoster/nanostat#installation
* toolchain: `foss/2021a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] nanoget (`nanoget-1.18.1-foss-2021a.eb`)
  * [x] nanomath (`nanomath-1.2.1-foss-2021a.e`)
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/bioconda/nanostat)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18199

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/18199 merged, ready for cleanup
