### ISSUE TITLE
Yambo 5.1.1

### ISSUE THREAD

**Issue by hajgato** [vscentrum/vsc-software-stack#16]
* link to support ticket: https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=86260
* website: https://github.com/yambo-code/yambo/tree/master
* installation docs: https://www.yambo-code.eu/wiki/index.php?title=Install_Yambo_on_Ubuntu/LinuxMint_with_Intel_compiler
* toolchain: `intel/2021b`
* easyblock to use: `...`
* required dependencies:
  * [x] PETSC
  * [x] SLEPC
  * [X] HDF5
  * [x] netCDF
  * [x] netCDF-Fortran
* optional dependencies:
 
* notes:
  * see https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/y/Yambo/Yambo-5.0.4-intel-2021a.eb for inspiration
  * Use external PETSC and SLEPC, watch out for the extra downloaded files (try to use as much external as much is possible
* effort: *(TBD)*

**Comment by ItIsI-Orient** [comment]
PR open for PETSc and SLEPc:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17625

**Comment by ItIsI-Orient** [comment]
PR open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17918

**Comment by boegel** [comment]
@ItIsI-Orient PR merged, ready for cleanup & closing...
