### ISSUE TITLE
POT

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#161]
* link to support ticket: [#2023042160000101](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=118306)
* website: https://pythonot.github.io/
* installation docs: https://pythonot.github.io/index.html#installation
* toolchain: `foss/2022b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://pythonot.github.io/index.html#installation + existing easyconfig
* notes:
  * add `sanity_pip_check = True`
  * also try to install additional dependencies fro sub-modules, cfr. https://pythonot.github.io/#dependencies
  * see also [`POT-0.5.1-intel-2018b-Python-3.6.6.eb`](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/POT/POT-0.5.1-intel-2018b-Python-3.6.6.eb)
* effort: *(TBD)*
* other install methods
  * conda: yes (https://pythonot.github.io/#anaconda-installation-with-conda-forge)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- For `foss/2022b` we would need to update `PyTorch`.
- Here is a PR for a `foss/2022a`
    - https://github.com/easybuilders/easybuild-easyconfigs/pull/18233
