### ISSUE TITLE
LeafCutter

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#162]
* link to support ticket: [#2023042560001129](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=118689)
* website: https://davidaknowles.github.io/leafcutter
* installation docs: http://davidaknowles.github.io/leafcutter/articles/Installation.html
* toolchain: `foss/2022b`
* easyblock to use: `Tarball` + `RPackage` ?
* required dependencies:
  * see http://davidaknowles.github.io/leafcutter/articles/Installation.html
* notes:
  * try to avoid using Python 2.7!
* effort: *(TBD)*
* other install methods
  * conda: yes (http://davidaknowles.github.io/leafcutter/articles/Installation.html#using-conda)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by laraPPr** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/18615
Installed on all clusters
