### ISSUE TITLE
LayoutParser

### ISSUE THREAD

**Issue by lexming** [vscentrum/vsc-software-stack#163]
* link to support ticket: INC0145525
* website: https://layout-parser.github.io/
* installation docs: https://github.com/Layout-Parser/layout-parser
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] SciPy-bundle
  * [x] OpenCV
  * [x] Pillow
  * [x] PyYAML
* optional dependencies:
  * [x] torchvision
  * [x] pycocotools
  * [x] PyTorch-Image-Models
  * [x] Safetensors
* effort: *medium*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by lexming** [comment]
PRs:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/18220

**Comment by boegel** [comment]
@lexming ready to close?
