### ISSUE TITLE
HybPiper

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#164]
* link to support ticket: [#2023042660001083](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=118867)
* website: https://github.com/mossmatters/HybPiper
* installation docs: https://github.com/mossmatters/HybPiper/wiki/Installation
* toolchain: `foss/2022b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * https://github.com/mossmatters/HybPiper/wiki/Installation#Dependencies
* notes:
  * use `hybpiper check_dependencies` as sanity check command?
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/mossmatters/HybPiper/wiki/Installation)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18414
