### ISSUE TITLE
Mikado

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#165]
* link to support ticket: [#2023042760000608](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=118881)
* website: https://github.com/EI-CoreBioinformatics/mikado
* installation docs: https://mikado.readthedocs.io/en/stable/Installation
* toolchain: `foss/2022b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/EI-CoreBioinformatics/mikado/blob/master/requirements.txt
* notes:
  * try using `python -c 'import Mikado; Mikado.test()'` as sanity check command
* effort: *(TBD)*
* other install methods
  * conda: yes (https://mikado.readthedocs.io/en/stable/Installation/#download)
  * container image: yes (https://mikado.readthedocs.io/en/stable/Installation/#install-using-containers)
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
1. https://github.com/easybuilders/easybuild-easyconfigs/pull/18525
2. https://github.com/easybuilders/easybuild-easyconfigs/pull/18529
3. https://github.com/easybuilders/easybuild-easyconfigs/pull/18571
4. https://github.com/easybuilders/easybuild-easyconfigs/pull/18614

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/18614 merged, ready for cleanup
