### ISSUE TITLE
IsoQuant

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#168]
* link to support ticket: [#2023051060000254](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=119844)
* website: https://github.com/ablab/IsoQuant
* installation docs: https://github.com/ablab/IsoQuant#manual-installation-and-requirements
* toolchain: `foss/2022b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * https://github.com/ablab/IsoQuant/blob/master/requirements.txt
* notes:
  * use `isoquant.py --test` as sanity check command
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/ablab/IsoQuant#installing-from-conda)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18331
