### ISSUE TITLE
inferCNV with foss/2022a

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#173]
* link to support ticket: [#2023052460001012](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=120954)
* website: https://github.com/broadinstitute/infercnv
* installation docs: https://github.com/broadinstitute/inferCNV/wiki/Installing-infercnv
* toolchain: `foss/2022a`
* easyblock to use: *(see existing easyconfigs)*
* required dependencies:
  * *(see existing easyconfigs)*
* notes:
  * sources for recent releases are available via https://bioconductor.org/packages/release/bioc/html/infercnv.html
  * must be compatible with `R-bundle-Bioconductor/3.15-foss-2022a-R-4.2.1`
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/bioconda/bioconductor-infercnv)
  * container image: yes (https://github.com/broadinstitute/inferCNV/wiki/Installing-infercnv#using-a-container-image)
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18299
