### ISSUE TITLE
bakta

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#174]
* link to support ticket: [#2023052460001076](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=120960)
* website: https://github.com/oschwengers/bakta
* installation docs: https://github.com/oschwengers/bakta#installation
* toolchain: `...`
* easyblock to use: `...`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/oschwengers/bakta#bioconda)
  * container image: yes (https://github.com/oschwengers/bakta#singularity)
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
@PetrKralCZ Maybe you can take a quick look at how difficult this would be?

Not sure I actually got anywhere, so I'll unassign it from myself...

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21861

**Comment by boegel** [comment]
@PetrKralCZ PR merged, software installed, ready for cleanup
