### ISSUE TITLE
BUStools

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#176]
* link to support ticket: [#2023060660000199](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=121820)
* website: https://bustools.github.io/
* installation docs: https://github.com/BUStools/bustools/#installation
* toolchain: `GCC/11.3.0`
* easyblock to use: *(see existing easyconfigs)*
* required dependencies:
  * *(see existing easyconfigs)*
* notes:
  * see `BUStools-0.40.0-GCCcore-9.3.0.eb`
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/bioconda/bustools)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): yes (https://bustools.github.io/download)
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19433

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19433

**Comment by PetrKralCZ** [comment]
PR Merged. Closing...
