### ISSUE TITLE
RSAT (rsa-tools)

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#177]
* link to support ticket: [#2023060660000322](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=121833)
* website: http://rsat.eu + https://github.com/rsa-tools/rsat-code
* installation docs: https://github.com/rsa-tools/rsat-code/blob/master/INSTALL.Rmd
* toolchain: `foss/2022b`?
* easyblock to use: `???`
* required dependencies:
  * see https://github.com/rsa-tools/rsat-code/blob/master/INSTALL.Rmd
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/bioconda/rsat-core)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
copy of https://github.com/vscentrum/vsc-software-stack/issues/421
