### ISSUE TITLE
pyodbc

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#178]
* link to support ticket: [#2023060660001009](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=121901)
* website: https://pypi.org/project/pyodbc + https://github.com/mkleehammer/pyodbc
* installation docs: https://github.com/mkleehammer/pyodbc/wiki/Install#installing-on-linux
* toolchain: `GCC/12.2.0` (`foss/2022b`)
* easyblock to use: `PythonBundle`
* required dependencies:
  * unixODBC (requires update of `unixODBC-2.3.7-foss-2018b.eb`)
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18334
