### ISSUE TITLE
SMCpp

### ISSUE THREAD

**Issue by hajgato** [vscentrum/vsc-software-stack#18]
* link to support ticket: https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=85917
* website: https://github.com/popgenmethods/smcpp
* installation docs: https://github.com/popgenmethods/smcpp#installation-instructions
* toolchain: `foss/2021b`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [x] GMP
  * [x] MPFR
  * [x] GSL
* optional dependencies:
  * none
* notes:
  * see https://github.com/easybuilders/easybuild-easyconfigs/pull/15738 for inspiration (almost done)
* effort: *(TBD)*

**Comment by deniskristak** [comment]
just adding this to show there's a wip easyconfig
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/62d2c1c30413bf14b5d8e9736dc729ccba3ecf82/easybuild/easyconfigs/s/SMC%2B%2B/SMC%2B%2B-1.15.4-foss-2022a.eb#L4

**Comment by boegel** [comment]
done, see https://github.com/easybuilders/easybuild-easyconfigs/pull/16017
