### ISSUE TITLE
Sabre

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#180]
* link to support ticket: [#2023062060001189](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=123199)
* website: https://github.com/najoshi/sabre
* installation docs: https://github.com/najoshi/sabre#building-and-installing-sabre
* toolchain: `GCC/12.2.0`
* easyblock to use: `MakeCp`
* required dependencies:
  * [x] zlib
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- conda package (other install method) here? https://anaconda.org/bioconda/sabre

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18342
