### ISSUE TITLE
zarr

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#184]
* link to support ticket: [#2023071360000183](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=125331;ArticleID=443177)
* website: https://zarr.readthedocs.io/en/stable/index.html
* installation docs: https://zarr.readthedocs.io/en/stable/installation.html
* toolchain: `foss/2022b`
* easyblock to use: 
* required dependencies:
  * [x] python, 3.10.8
  * [x] SciPy-bundle, 2023.02
* optional dependencies:
* notes:
  * Started on updating [zarr-2.13.3-foss-2022a.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/z/zarr/zarr-2.13.3-foss-2022a.eb) to new toolchain but installation is failing with new version of the extention numcodecs. [easyconfig in wip](https://github.com/vscentrum/vsc-software-stack/blob/wip/184_zarr/zarr-2.16.0-foss-2022b.eb).
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by laraPPr** [comment]
There is config file in wip but is failing to install zarr

this is the error:
```
== 2023-08-04 14:25:17,400 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): cmd " /apps/gent/RHEL8/zen2-ib/software/Python/3.10.8-GCCcore-12.2.0/bin/python -m pip install --prefix=/data/gent/461/vsc46128/easybuild/RHEL8/zen2-ib/software/zarr/2.16.0-foss-2022b  --no-deps  --ignore-installed  --no-index  --no-build-isolation  ." exited with exit code 1 and output:
Processing /tmp/vsc46128/zarr/2.16.0/foss-2022b/numcodecs/numcodecs-0.11.0
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
   Preparing metadata (pyproject.toml) did not run successfully.
   exit code: 1
  > [13 lines of output]
      Traceback (most recent call last):
        File "/apps/gent/RHEL8/zen2-ib/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/apps/gent/RHEL8/zen2-ib/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/apps/gent/RHEL8/zen2-ib/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/apps/gent/RHEL8/zen2-ib/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/apps/gent/RHEL8/zen2-ib/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
      ModuleNotFoundError: No module named 'cpuinfo'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

 Encountered error while generating package metadata.
> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by boegel** [comment]
This indicates there's a missing dependency on https://pypi.org/project/py-cpuinfo?

**Comment by laraPPr** [comment]
Should I than add py-cpuinfo to the extentions to see if this resolves the error? Or as a dependency?

**Comment by boegel** [comment]
We already have separate easyconfigs for `py-cpuinfo`, so a dependency makes more sense.

It's possible that `zarr` (or one of its dependencies) has started requiring `py-cpuinfo`, where that wasn't the case yet with `zarr-2.13.3-foss-2022a.eb`

**Comment by laraPPr** [comment]
That did the trick, Thanks for the help. I'll open a pr.
