### ISSUE TITLE
Leafcutter

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#187]
* link to support ticket: [#2023071760000372](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=125564) + [#2023072860000173](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=126016)
* website: http://davidaknowles.github.io/leafcutter/index.html
* installation docs: http://davidaknowles.github.io/leafcutter/articles/Installation.html
* toolchain: `foss/2022b`
* easyblock to use: `...`
* required dependencies:
  * [x] samtools
  * [x] regtools
  * [x] python
  * [x] R
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (http://davidaknowles.github.io/leafcutter/articles/Installation.html#using-conda)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by laraPPr** [comment]
made easyconfig for newer RegTools

**Comment by laraPPr** [comment]
Added a the easyconfig for leafcutter to WIP.  When running it I get the following error: ERROR: no packages specified

**Comment by boegel** [comment]
You probably need to instruct EasyBuild to run the installation command for the R package from the `leafcutter` subdirectory, since that's where the `[DESCRIPTION](https://github.com/davidaknowles/leafcutter/blob/master/leafcutter/DESCRIPTION)` file is located:

```python
start_dir = 'leafcutter'

**Comment by laraPPr** [comment]
Now I hit the following error:
```
Error: object evalWithTimeout is not exported by 'namespace:R.utils'
Execution halted
ERROR: lazy loading failed for package leafcutter
```
I also had another question. On their website it says that the latest version is 0.2.9 but I can only find 0.2.7 and older.

**Comment by boegel** [comment]
Seems like you will need to create a patch so it uses `withTimeout` instead, see also https://github.com/nuno-agostinho/psichomics/issues/383 

W.r.t. version: the [DESCRIPTION](https://github.com/davidaknowles/leafcutter/blob/master/leafcutter/DESCRIPTION) file says it's 0.2.9, so I would download the commit that set the version to `0.2.9` in that file, and download that as `leafcuffer-0.2.9.tar.gz`?

**Comment by boegel** [comment]
Note: duplicate of #162 (so we have 3 open install requests for Leafcutter)

**Comment by laraPPr** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/18615
