### ISSUE TITLE
chopper

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#189]
* link to support ticket: [#2023072060000179](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=125649)
* website: https://github.com/wdecoster/chopper
* installation docs: https://github.com/wdecoster/chopper
* toolchain: ``
* easyblock to use: ``
* required dependencies:
  * 
* optional dependencies:
  * 
* notes:
  * latest version of chopper
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/bioconda/chopper)
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
Seems done by this PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21418
