### ISSUE TITLE
Ax

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#191]
* link to support ticket: [#2023073160000774](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=126138)
* website: https://ax.dev/
* installation docs: https://ax.dev/docs/installation.html
* toolchain: ``
* easyblock to use: ``
* required dependencies:
  * [x] botorch >= 0.1.3
  * [x] jinja2
  * [x] pandas
  * [x] scipy
  * [x] sklearn
  * [x] plotly >=2.2.1
* optional dependencies:
  * 
* notes:
  * You need Python 3.8 or later to run Ax
  * Test if you can run this notebook https://ax.dev/tutorials/multiobjective_optimization.html
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/conda-forge/ax-platform)
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: no

**Comment by WilleBell** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18448

**Comment by boegel** [comment]
@WilleBell `Ax/0.3.3-foss-2022a` is installed on Hortense (will pop up in `module avail` very soon, after automatic Lmod cache update)

**Comment by boegel** [comment]
@WilleBell This issue can be closed now?

**Comment by WilleBell** [comment]
Sure, closing, thank you @boegel
