### ISSUE TITLE
FSL

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#192]
* link to support ticket: [#2023080160000293](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=126175)
* website: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/
* installation docs: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/Linux
* toolchain: `foss/2022b`
* easyblock to use: ``
* required dependencies:
  * 
* optional dependencies:
  * 
* notes:
  * [easyconfig available for foss/2021a](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/f/FSL/FSL-6.0.5.1-foss-2021a.eb)
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
The installation procedure for FSL has changed quite a bit since v6.0.6 - sources are now no longer provided as they were before.

See https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2308&L=FSL&O=D&P=39851 + https://git.fmrib.ox.ac.uk/fsl/conda/docs/-/tree/master for more info...

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/18697

**Comment by boegel** [comment]
installed, so closing...
