### ISSUE TITLE
devbio-napari

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#193]
* link to support ticket: [#2023080160000319](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=126177)
* website: https://gitlab.math.tu-dresden.de/bia-pol/singularity-devbio-napari
* installation docs: https://gitlab.math.tu-dresden.de/bia-pol/singularity-devbio-napari
* toolchain: ``
* easyblock to use: ``
* required dependencies:
  * [ ] ocl-icd-system
  * [ ] cupy
  * [ ] cudatoolkit
  * [ ] pyopencl
  * [ ] pytorch-gpu
  * [ ] dask-image
  * [ ] dask-jobqueue
  * [ ] zarr
  * [ ] aicsimageio (#239)
  * [ ] bioformats_jar
  * [ ] devbio-napari
  * [ ] napari-aicsimageio
* optional dependencies:
  * [ ] 
* notes:
  * https://github.com/napari/napari/tree/main/examples we could run any of those python files to test the implementation
  * as many plugins are developed for napari, using a container would facilitate its installation
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/conda-forge/devbio-napari)
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
@PetrKralCZ PR merged https://github.com/easybuilders/easybuild-easyconfigs/pull/19392, ready for cleanup

**Comment by boegel** [comment]
with CUDA support:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/19586
