### ISSUE TITLE
MitoHiFi

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#198]
* link to support ticket: [#2023081660000943](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=127210)
* website: https://github.com/marcelauliano/MitoHiFi
* installation docs: https://github.com/marcelauliano/MitoHiFi#2-installation
* toolchain: `foss/2022b` (or older if necessary)
* easyblock to use: `Tarball`
* required dependencies:
  * see https://github.com/marcelauliano/MitoHiFi#23-manually-install-all-dependencies
  * MitoFinder (see #216)
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: only dependencies (see https://github.com/marcelauliano/MitoHiFi#22-conda-partially-installing-dependencies-with-conda)
  * container image: yes (https://github.com/marcelauliano/MitoHiFi#21-using-docker-and-singularity)
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
MitoFinder (#216) requires Python 2.7, so may need to change default for annotation in MitoHifi to use MITOS?

**Comment by boegel** [comment]
@deniskristak Can you take a look at this?

**Comment by deniskristak** [comment]
PR open: https://github.com/easybuilders/easybuild-easyconfigs/pull/19263

have to solve patch (see PR)
