### ISSUE TITLE
CLEAR

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#2]
* link to support ticket: [HPC-UGent OTRS #2022060760000359](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=82259)
* website: https://github.com/YangLab/CLEAR
* installation docs: https://github.com/YangLab/CLEAR#installation
* toolchain: `foss/2021b`
* easyblock to use: `PythonPackage` or `PythonBundle`
* required dependencies:
  * see https://github.com/YangLab/CLEAR#installation-requirements
* notes:
  * ...
* effort: *(TBD)*

**Comment by ItIsI-Orient** [comment]
There also is the possibility that the example test files are corrupted/there is something wrong with the genome sources or indexes that are included, but I am not sure how to test for that.

**Comment by boegel** [comment]
@ItIsI-Orient Please make a pull request for the CLEAR easyconfig you have to the central easyconfigs repository, maybe make it a WIP (draft) PR.

I'll install CLEAR with that easyconfig file, and ask the researchers who asked for it to be installed to test the installation.
If it's just a problem with the provided example data, and it works for them, then we're done I guess...

**Comment by ItIsI-Orient** [comment]
PRs Open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16356
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16357

**Comment by ItIsI-Orient** [comment]
Updated the files for CLEAR, namely Cufflinks with the near 100MB log, that gets created when I try to build Cufflinks with statically linked Boost 1.75.0

**Comment by boegel** [comment]
```
/kyukon/home/apps/RHEL8/cascadelake-ib/software/GCCcore/11.2.0/include/c++/11.2.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
   32 | #error This file requires compiler and library support \
      |  ^~~~~
```

looks like it’s hardcoded in Cufflinks’ [configure.ac](http://configure.ac/) , see https://github.com/cole-trapnell-lab/cufflinks/commit/3de614ee80ea6c00eaa3cac0a9fa622423719d14 .
But one of the dependencies probably requires C++11 now (Eigen maybe)
So I’d try using:

```python
preconfigopts = "sed -i 's/std=c++03/std=c++11/g' configure.ac && "
```

and adding a comment why that’s necessary

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/16357 merged, ready for cleanup...
