### ISSUE TITLE
SEACells

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#201]
* link to support ticket: [2023082560000757](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=128149) + [2023090560000481](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=129632)
* website: https://github.com/dpeerlab/SEACells
* installation docs: https://github.com/dpeerlab/SEACells
* toolchain: `foss/2021a`
* easyblock to use: `...`
* required dependencies:
  * [x] Python
    * alabaster
    * six
    * tabulate
    * joblib
  * [ ] legacy-api-wrap (ext in cell2location)
  * [ ] louvain (ext in cell2location)
  * [x] SciPy-bundle
    * numpy
    * pandas
    * scipy
  * [ ] anndata (already easyconfig)
  * [x] cmake
  * [ ] Cython (already an easyconfig)
  * [x] h5py 
  * [x] leidenalg
  * [x] matplotlib
    *  kiwisolver
  * [x] numba
    * llvmlite
  * [ ] palantir
  * bnpy/Perl
    * [ ] munkres
  * FLAIR
    * [ ] ncls  
 * [ ] PhenoGraph
  * [ ] psutil (already an easyconfig)
  * [ ]  pyranges
  * [ ] pyrle
  * [x] scanpy
  * [x] scikit-learn
  * [x] Seaborn
  * [ ] sorted-nearest
  * [x] statsmodels
  * [ ] tables
  * [x] tqdm
  * [ ] tzdata
  * [ ] tzlocal
  * [x] umap-learn
* optional dependencies:
* notes:
  * ..
* effort: *(TBD)*
* other install methods
  * conda: [yes]( https://github.com/dpeerlab/SEACells)
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/18724
