### ISSUE TITLE
EUKulele

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#206]
* link to support ticket: [#2021010860001152 ](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=5993)
* website: https://github.com/AlexanderLabWHOI/EUKulele
* installation docs: https://eukulele.readthedocs.io/en/latest/install.html
* toolchain: `foss`
* easyblock to use: `PythonVundle`
* required dependencies:
  * [ ] Python
  * [ ] SciPy-bundle
  * [ ] Biopython
  * [ ] matplotlib
  * [ ] PyYAML
  * [ ] Seaborn
  * [ ] BLAST
  * [ ] BUSCO
  * [ ] DIAMOND
  * [ ] TransDecoder
* optional dependencies:
  * [ ] ...
* notes:
   * This is already a very old ticket and the user has let us know that he would still like to have it
   * There was already worked on it in 2021 but it has never been finished because there were problems with the BUSCO dependency
   * There two prs made for this who have never been finished 
     *  https://github.com/easybuilders/easybuild-easyconfigs/pull/12152/files#diff-5838fa6d606dccd5dfbe3e29623efe74041f4662e9774ec40bb8bb1ad6343e5d
     *  https://github.com/easybuilders/easybuild-easyconfigs/pull/12193
   * The user would like to have the latest version
* effort: *(TBD)*
* other install methods
  * conda: [yes](https://eukulele.readthedocs.io/en/latest/install.html)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
@deniskristak https://github.com/easybuilders/easybuild-easyconfigs/pull/19217 merged, ready for cleanup

**Comment by deniskristak** [comment]
cleaned up, closing
