### ISSUE TITLE
Finder

### ISSUE THREAD

**Issue by hajgato** [vscentrum/vsc-software-stack#21]
* link to support ticket: [#2022072860000255](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=86564)
* website: https://github.com/sagnikbanerjee15/Finder
* installation docs: https://github.com/sagnikbanerjee15/Finder#downloading-finder-from-release-latest-stable-version
* toolchain: `foss/2021b`
* easyblock to use: ???
* required dependencies:
  * [ ] BRAKER https://github.com/vscentrum/vsc-software-stack/issues/20
  * optional dependencies:
  * [ ] ...
* notes:
  * Might be a tricky one, as it wants to download a docker/singularity image and run the software in the image....
* effort: *(TBD)*

**Comment by deniskristak** [comment]
PsiCLASS is one of deps - opened PR

**Comment by deniskristak** [comment]
https://github.com/sagnikbanerjee15/Finder/issues/64
opened issue, asking about the way to avoid docker/singularity

**Comment by deniskristak** [comment]
the problem is that there will be a whole lot of patching
https://github.com/sagnikbanerjee15/Finder/blob/master/run_finder
as the main script pulls docker image everytime you run it...

**Comment by deniskristak** [comment]
so i just asked if anyone did it before

**Comment by deniskristak** [comment]
PR opened

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/16910 merged, ready for cleanup \o/

**Comment by deniskristak** [comment]
cleaned up
