### ISSUE TITLE
PASA

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#215]
* link to support ticket: [#2023092060000764](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=131980)
* website: https://github.com/PASApipeline/PASApipeline
* installation docs: https://github.com/PASApipeline/PASApipeline/wiki/Pasa_installation_instructions
* toolchain: `foss/2022b`?
* easyblock to use: `???`
* required dependencies:
  * see https://github.com/PASApipeline/PASApipeline/wiki/Pasa_installation_instructions
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: yes (https://github.com/PASApipeline/PASApipeline/wiki/PASA_Docker#running-pasa-via-singularity)
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19570

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup
