### ISSUE TITLE
PretextMap

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#217]
* link to support ticket: [#2023092260001474](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=132403)
* website: https://github.com/wtsi-hpag/PretextMap
* installation docs: https://github.com/wtsi-hpag/PretextMap
* toolchain: `GCCcore/12.3.0`
* easyblock to use: `...`
* required dependencies:
  * [x] Clang-16.0.6-GCCcore-12.3.0.eb
  * [x] Meson-1.1.1-GCCcore-12.3.0.eb
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: [yes](https://github.com/wtsi-hpag/PretextMap)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20790

**Comment by boegel** [comment]
@pavelToman ready for cleanup
