### ISSUE TITLE
dynesty

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#219]
* link to support ticket: [#2023092660001967](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=132973)
* website: https://dynesty.readthedocs.io
* installation docs: https://dynesty.readthedocs.io/en/stable/#installation
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * `numpy`, `scipy`, `matplotlib`, `tqdm`
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/conda-forge/dynesty)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by ItIsI-Orient** [comment]
PR open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/19091

**Comment by boegel** [comment]
@ItIsI-Orient PR merged, ready for cleanup
