### ISSUE TITLE
SOAPdenovo-Trans

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#220]
* link to support ticket: [#2023100260001339](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=133825)
* website: https://github.com/aquaskyline/SOAPdenovo-Trans
* installation docs: https://github.com/aquaskyline/SOAPdenovo-Trans/blob/master/README.md#installation
* toolchain: `...`
* easyblock to use: *(see existing easyconfig `SOAPdenovo-Trans-1.0.4-intel-2017a.eb`)* 
* required dependencies:
  * `zlib`
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/bioconda/soapdenovo-trans)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): yes (but no?)
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19530

**Comment by boegel** [comment]
PR merged, software installed => closing...
