### ISSUE TITLE
OrthoFinder (v2.5.5)

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#222]
* link to support ticket: [#2023100260002472](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=133939)
* website: https://github.com/davidemms/OrthoFinder
* installation docs: https://github.com/davidemms/OrthoFinder#installing-orthofinder-on-linux
* toolchain: *(see existing easyconfig `OrthoFinder-2.5.4-foss-2020b.eb`)*
* easyblock to use: `foss/2023a`
* required dependencies:
  * *(see existing easyconfig `OrthoFinder-2.5.4-foss-2020b.eb`)*
* notes:
  * also requested: MAFFT v7.520 FastTree v2.1.11 (check if that's latest versions)
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/bioconda/orthofinder)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/18980

**Comment by ItIsI-Orient** [comment]
MAFFT PR:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/18981

**Comment by boegel** [comment]
PRs merged, software installed, no subdir in `wip` branch to clean up, so closing...
