### ISSUE TITLE
Transrate

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#224]
* link to support ticket: [#2023100260002491](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=133941) + [#2024062860000299](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=160696)
* website: https://hibberdlab.com/transrate
* installation docs: https://hibberdlab.com/transrate/installation.html
* toolchain: `GCC/12.3.0`
* easyblock to use: `RubyGem`?
* required dependencies:
  * [ ] Ruby
  * [ ] ...?
* notes:
  * easyconfig for pre-built binary already available (`Transrate-1.0.3.eb`)
     * check if pre-built binary still works on RHEL8 OS
     * see if it can be installed from source
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/bioconda/transrate)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): yes? (https://hibberdlab.com/transrate/installation.html)
  * easyconfig outside EasyBuild: no

**Comment by laraPPr** [comment]
The same user has opened another request for transrate [#2024062860000299](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=160696)

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20964

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20964

**Comment by laraPPr** [comment]
The installation failed on shinx with 
```
FAILED: Installation ended unsuccessfully (build directory: /tmp/vsc40003/easybuild/Transrate/1.0.3/GCC-12.3.0): build failed (first 300 chars): Location to gem file in unpacked sources must be specified via gem_file
```
On the other clusters it seems to be succeeding already build for skitty, donphan, accelgor and doduo

**Comment by laraPPr** [comment]
Informed the user that it is install everywhere but shinx. We'll see if I have some time to look at why might not be installed on shinx

**Comment by boegel** [comment]
@laraPPr The problem is probably that I didn't update the EasyBuild installation ued on shinx before submitting the Transrate installation there.
On the RHEL8 clusters, we use an EasyBuild installation on top of Python 3.6, while on shinx which is already using RHEL9, we're using an installation on top of Python 3.9.

So it's two separate EasyBuild installations, and there's no easy way to keep them in sync via our usual procedure (running `eb_update.sh` on the production login nodes).
For shinx, we either need to run `eb_update.sh` in a shinx session, or on a (brand new, WIP) RHEL9 login node

I'll look into that right now.

**Comment by boegel** [comment]
`Transrate/1.0.3-GCC-12.3.0` is now also installed on `shinx`

@laraPPr Can you inform the users?

@PetrKralCZ ready for cleanup & closing

**Comment by laraPPr** [comment]
yes will do
