### ISSUE TITLE
HPCC

### ISSUE THREAD

**Issue by smoors** [vscentrum/vsc-software-stack#226]
* link to support ticket: ...
* website: https://hpcchallenge.org/
* installation docs: ...
* toolchain: `...`
* easyblock to use: `...`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by smoors** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18892

**Comment by boegel** [comment]
PR merged, so closing...
