### ISSUE TITLE
SNAP-ESA

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#227]
* link to support ticket: [#2023100960001326](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=134897)
* website: https://earth.esa.int/eogateway/tools/snap
* installation docs: http://step.esa.int/docs/tutorials/SNAP_CommandLine_Tutorial.pdf + https://senbox.atlassian.net/wiki/spaces/SNAP/pages/30539778/Install+SNAP+on+the+command+line
* toolchain: `???`
* easyblock to use: `???` (`Binary` or custom easyblock?)
* required dependencies:
  * ???
* notes:
  * different `SNAP` than [what is already in EasyBuild](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/s/SNAP), so need to use different software name => `SNAP-ESA`
  * sources available via https://github.com/senbox-org
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): yes?
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
Looks like this is going to be a fun one...

```
$ ./esa-snap_all_unix_9_0_0.sh --help
Unpacking JRE ...
Starting Installer ...
This will install ESA SNAP on your computer.
OK [o, Enter], Cancel [c]

```

**Comment by lexming** [comment]
I already did this one some time ago:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/13198

**Comment by boegel** [comment]
Oh great, I totally overlooked that one...

**Comment by boegel** [comment]
@lexming Some changes necessary before we can merge your PR: https://github.com/lexming/easybuild-easyconfigs/pull/2

**Comment by boegel** [comment]
easyconfig PR for SNAP-ESA 9.0.0:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/19031
