### ISSUE TITLE
CellRank + scVelo

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#230]
* link to support ticket: [#2023101160001394 (CellRank)](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=135290) + [#2023101160001438 (scVelo)](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=135294)
* website: https://cellrank.readthedocs.io + https://scvelo.readthedocs.io
* installation docs: https://cellrank.readthedocs.io/en/latest/installation.html + https://scvelo.readthedocs.io/en/stable/installation
* toolchain: `foss/2022a`
* easyblock to use: *(see existing easyconfigs)*
* required dependencies:
  * *(see existing easyconfigs)*
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/bioconda/cellrank + https://anaconda.org/bioconda/scvelo)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
WIP easyconfig available in [230_CellRank_scVelo](https://github.com/vscentrum/vsc-software-stack/tree/wip/230_CellRank_scVelo)

Got stuck with a enigmatic build problem with an update of `petsc4py`:

```
ImportError: /software/PETSc/3.17.4-foss-2022a/lib/libpetsc.so.3.17: undefined symbol: SCOTCH_dgraphOrderTreeDist
```

This suggests that `PETSc` may not be built/linked correctly to the SCOTCH static libraries?

```
$ ldd /software/PETSc/3.17.4-foss-2022a/lib/libpetsc.so.3.17 | grep SCOTCH

$ nm /software/SCOTCH/7.0.1-gompi-2022a/lib/libptscotch.a | grep SCOTCH_dgraphOrderTreeDist
0000000000000010 T SCOTCH_dgraphOrderTreeDist
                 U SCOTCH_dgraphOrderTreeDist
```

**Comment by deniskristak** [comment]
funnily enough, I'm not getting the same error, I'm only getting this:
```
python -c 'from petsc4py import PETSc':
	[node4013.donphan.os:1316568] OPAL ERROR: Unreachable in file ext3x_client.c at line 112
```
full log here:
https://github.com/vscentrum/vsc-software-stack/blob/wip/230_CellRank_scVelo/easybuild-petsc4py-3.17.4-20231127.200317.qeoJr.log

**Comment by boegel** [comment]
@deniskristak That looks like a hard failure when doing `MPI_Init`, which you may see when running directly in an interactive Slurm job.

Try doing `ssh node1234` (with correct node name) first, before you do `eb --module-only` (or just rebuild)

**Comment by boegel** [comment]
It seems like the PETSc issue was introduced in https://github.com/easybuilders/easybuild-easyblocks/pull/2796, where the order in which the list of SCOTCH libraries to link to was sorted alphabetically (on my request), which is wrong...

This patch for the PETSc easyblock should probably fix that:

```diff
diff --git a/easybuild/easyblocks/p/petsc.py b/easybuild/easyblocks/p/petsc.py
index d5081d528..1820d565d 100644
--- a/easybuild/easyblocks/p/petsc.py
+++ b/easybuild/easyblocks/p/petsc.py
@@ -237,10 +237,10 @@ class EB_PETSc(ConfigureMake):
                 inc_spec = "-include=[%s]" % ','.join(scotch_inc)

                 # For some reason there is a v3 suffix added to libptscotchparmetis
-                # which is the reason for this new code.
-                req_scotch_libs = ['libesmumps.a', 'libptesmumps.a', 'libptscotch.a',
-                                   'libptscotcherr.a', 'libptscotchparmetisv3.a', 'libscotch.a',
-                                   'libscotcherr.a']
+                # which is the reason for this new code;
+                # note: order matters here, don't sort these alphabetically!
+                req_scotch_libs = ['libptesmumps.a', 'libptscotchparmetisv3.a', 'libptscotch.a',
+                                   'libptscotcherr.a', 'libesmumps.a', 'libscotch.a', 'libscotcherr.a']
                 scotch_libs = [os.path.join(scotch, "lib", x) for x in req_scotch_libs]
                 lib_spec = "-lib=[%s]" % ','.join(scotch_libs)
                 self.cfg.update('configopts', ' '.join([withdep + spec for spec in ['=1', inc_spec, lib_spec]]))
```

Most existing central installations in `/apps/gent` are actually unaffected, because they were installed with an older version of the PETSc easyblock, only `/apps/gent/RHEL8/zen3-ampere-ib/software/PETSc/3.17.4-foss-2022a` will need to be re-installed

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/19515

**Comment by boegel** [comment]
for scVelo 0.3.1, see:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20002

**Comment by boegel** [comment]
@laraPPr Can you look into merging https://github.com/easybuilders/easybuild-easyconfigs/pull/19515 so we can close this?

**Comment by boegel** [comment]
@PetrKralCZ merged & installed, ready for cleanup
