### ISSUE TITLE
Suppa

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#231]
* link to support ticket: [#2023101660001331](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=135814)
* website: https://github.com/comprna/SUPPA
* installation docs: https://github.com/comprna/SUPPA
* toolchain: `?`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] ?
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: [yes](https://anaconda.org/bioconda/suppa)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19181

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19275

**Comment by boegel** [comment]
@PetrKralCZ ready for cleanup + closing
