### ISSUE TITLE
EasyMocap

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#232]
* link to support ticket: [#2023102160000152](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=136405)
* website: https://chingswy.github.io/easymocap-public-doc/
* installation docs: https://chingswy.github.io/easymocap-public-doc/install/install.html#install-easymocap-step-by-step
* toolchain: `2022a`
* easyblock to use: `...`
* required dependencies:
  * [ ] ipdb
  * [ ] joblib
  * [x] tqdm
  * [ ] opencv-python
  * [x] yacs
  * [ ] tabulate
  * [ ] termcolor
  * [ ] git+https://github.com/mattloper/chumpy.git
  * [ ] mediapipe==0.10.0
  * [ ] func_timeout
  * [x] ultralytics
  * [ ] gdown
  * [ ] setuptools==59.5.0
  * [ ] tensorboard==2.8.0
  * [x] pytorch-lightning==1.5.0
  * [x] pytorch
* optional dependencies:
  * [ ] ...
* notes:
  * https://chingswy.github.io/easymocap-public-doc/quickstart/quickstart.html The commands under "Demo on multiple calibrated cameras" would need to be executed on the data in my VSC account. The path was given so that the test case can be executed as shown in the quickstart
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries  no
  * easyconfig outside EasyBuild:  no

**Comment by boegel** [comment]
@PetrKralCZ As discussed, let's try to use `foss/2023a` here instead, since we have `PyTorch` available now with that toolchain...

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20307

**Comment by boegel** [comment]
@PetrKralCZ Please also look into CUDA version of `EasyMocap` (make that a separate PR)

**Comment by boegel** [comment]
CUDA version of EasyMocap was trivial, see:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20446

**Comment by boegel** [comment]
@PetrKralCZ minor TODO: cleanup `232_EasyMocap` in `wip` branch
