### ISSUE TITLE
MiXCR v4.5.0

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#233]
* link to support ticket: [#2023102360001148](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=136558)
* website: https://mixcr.com/
* installation docs: https://github.com/milaboratory/mixcr
* toolchain: `...`
* easyblock to use: `Tarball`
* required dependencies:
  * [ ] Java
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/milaboratories/mixcr)
  * container image: yes (https://github.com/milaboratory/mixcr/pkgs/container/mixcr%2Fmixcr)
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: yes

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19517

**Comment by boegel** [comment]
PR merged + software installed, so closing...

**Comment by boegel** [comment]
user-facing instructions w.r.t. the license are available at https://mixcr.com/mixcr/getting-started/milm, I've informed the researcher that they need to provide a license themselves
