### ISSUE TITLE
pythermalcomfort

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#234]
* link to support ticket: [#2023102360001219](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=136565) + [#2023103160000124](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=137605)
* website: https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort
* installation docs: https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort#installation
* toolchain: ``
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19285

**Comment by boegel** [comment]
PR merged, software installed, ready for cleanup & close
