### ISSUE TITLE
singleM

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#235]
* link to support ticket: [#2023102460000111](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=136619)
* website: https://github.com/wwood/singlem
* installation docs: https://wwood.github.io/singlem/Installation
* toolchain: `foss 2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] polars
  * [x] Biopython
  * [x] DIAMOND
  * [x] hmmer
  * [x] orfm
  * [x] mfqe
  * [x] extern (as extension)
  * [x] graftm (as extension)
  * [x] krona (krona-tools)
  * [x] pplacer
  * [x] sra-tools 
  * [x] ncbi-ngs-sdk
  * [x] sqlite (in Python)
  * [x] mafft
  * [x] seqmagick
  * [x] expressbetadiversity
  * [x] cd-hit (available for 2022b)
  * [x] fasttree
  * [x] fastalite (as extension)
  * [x] jinja2 (as extension)
  * [x] sqlalchemy (as extension)
  * [x] smafa
  * [x] pyranges (as extension)
  * [x] prodigal (available for 2022b)
  * [x] tqdm
  * [x] pyarrow (as Arrow in EC)
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) 
  * container image: yes (link?) 
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: yes

**Comment by boegel** [comment]
Let's make sure we use `foss/2023a` for this, even though easyconfigs are missing for 13 dependencies, to make sure we can also install this on our latest cluster `shinx` (which has AMD Genoa CPUs).

Priority for this is "lowest", so this can be put on hold for now until later...

**Comment by boegel** [comment]
@pavelToman For the `polars`, I've opened an issue for the problem with generates contents for `crates` when using `CargoPythonPackage`, see https://github.com/easybuilders/easybuild-easyblocks/issues/3078

**Comment by lexming** [comment]
FYI I opened a PR for `polars` in 2023a (worked on it for other reasons than `singleM`):
* https://github.com/easybuilders/easybuild-easyconfigs/pull/19770

It's for v0.19.19 instead of 0.20.x because the latter needs features in Rust that are not available in Rust v1.75

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21016

**Comment by laraPPr** [comment]
Am now installing polars centrally. so reopening to make sure I don't forget

**Comment by laraPPr** [comment]
installed and and ready for clean-up
