### ISSUE TITLE
NGSpeciesID

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#236]
* link to support ticket: [#2023102560001304](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=136907)
* website: https://github.com/ksahlin/NGSpeciesID
* installation docs: https://github.com/ksahlin/NGSpeciesID#INSTALLATION
* toolchain: `...`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?)
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: yes

**Comment by boegel** [comment]
@PetrKralCZ I've opened an issue on the `pyspoa` segfault, let's see if they reply, see https://github.com/nanoporetech/pyspoa/issues/12

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19803
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19804
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19808
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19809
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19810
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19813
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19814
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19815

**Comment by boegel** [comment]
all PRs merged, ready for cleanup...
