### ISSUE TITLE
Glog

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#237]
* link to support ticket: [#2023102560001313](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=136908)
* website: https://github.com/google/glog
* installation docs: https://github.com/google/glog#building-glog-with-cmake
* toolchain: `GCC-11.3.0`
* easyblock to use: `CMakeMake`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: yes

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19426

**Comment by PetrKralCZ** [comment]
- PR is merged. Closing...
