### ISSUE TITLE
gflags

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#238]
* link to support ticket: [#2023102560001322](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=136909)
* website: https://github.com/gflags/gflags
* installation docs: https://gflags.github.io/gflags/#download
* toolchain: `GCC-11.3.0`
* easyblock to use: `CMakeMake`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda:  no
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: yes

**Comment by boegel** [comment]
see https://github.com/easybuilders/easybuild-easyconfigs/pull/19364

**Comment by PetrKralCZ** [comment]
PR merged, so closing...
