### ISSUE TITLE
AICSImageIO

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#239]
* link to support ticket: [#2023110860000541](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=138275)
* website: https://allencellmodeling.github.io/aicsimageio/_static/v3/index.html#
* installation docs: https://allencellmodeling.github.io/aicsimageio/_static/v3/installation.html
* toolchain: `foss-2022a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda:  no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19315
