### ISSUE TITLE
radian

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#240]
* link to support ticket: [#2023111660001052](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=139216)
* website: https://github.com/randy3k/radian
* installation docs: https://github.com/randy3k/radian#installation
* toolchain: `2022b`
* easyblock to use: ``
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/randy3k/radian#installation)
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19484

**Comment by boegel** [comment]
PR merged, software installed
