### ISSUE TITLE
ANSYS v2023R2

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#241]
* link to support ticket: [#2023112160000552](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=139578)
* website: https://www.ansys.com
* installation docs: 
* toolchain: `...`
* easyblock to use: `...`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda:  no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: yes

**Comment by laraPPr** [comment]
Also asked for 2023R1 and 2024R1 in [#2024071960000232](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=162614)

**Comment by laraPPr** [comment]
request of 2024R2 [#2024091360000231](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=167857)

**Comment by boegel** [comment]
all good, recent versions of FLUENT have been installed now...
