### ISSUE TITLE
python packages: gcsfs and s3fs

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#243]
* link to support ticket: [#2023111460000342](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=138873)
* website: https://pypi.org/project/gcsfs/#history and https://pypi.org/project/s3fs/
* installation docs: https://github.com/fsspec/gcsfs and https://s3fs.readthedocs.io/en/latest/install.html
* toolchain: `...`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://s3fs.readthedocs.io/en/latest/install.html and https://gcsfs.readthedocs.io/en/latest/)
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild:  no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19574

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19576
