### ISSUE TITLE
PySCF

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#245]
* link to support ticket: [#2023101660001474](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=135828)
* website: http://www.pyscf.org
* installation docs: https://pyscf.org/install.html
* toolchain: `foss/2022b`
* easyblock to use: `CMakeMakeCp`
* required dependencies:
  * [x] Python
  * [x] SciPy-bundle
  * [x] libcint
  * [x] libxc
  * [x] XCFun
  * [x] CPPE
  * [x] PyBerny
  * [x] PyCheMPS2 
  * [x] Block
  * [ ] NECI
  * [x] Dice 
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by laraPPr** [comment]
Working on it

**Comment by laraPPr** [comment]
I'm stuck on the dependency Block. You can find the work that I've already done in wip.
I get the following Error:
"""
pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
"""

**Comment by laraPPr** [comment]
No longer stuck on Block
https://github.com/easybuilders/easybuild-easyconfigs/pull/19493

**Comment by laraPPr** [comment]
NECI failing during testing with following error:
```
[node4012.donphan.os:521773] OPAL ERROR: Unreachable in file ext3x_client.c at line 112
--------------------------------------------------------------------------
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute. There are several options for building PMI support under
SLURM, depending upon the SLURM version you are using:

  version 16.05 or later: you can use SLURM's PMIx support. This
  requires that you configure and build SLURM --with-pmix.

  Versions earlier than 16.05: you must use either SLURM's PMI-1 or
   PMI-2 support. SLURM builds PMI-1 by default, or you can manually
   install PMI-2. You must then build Open MPI using --with-pmi pointing
   to the SLURM PMI library location.
 
 Please configure as appropriate and try again.
 --------------------------------------------------------------------------
```

**Comment by boegel** [comment]
@laraPPr That problem with NECI may be because NECI can be very memory-hungry, so we'll likely have to use a full node to get it installed...

**Comment by laraPPr** [comment]
Dice PR 
https://github.com/easybuilders/easybuild-easyconfigs/pull/19566
