### ISSUE TITLE
ebGSEA

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#247]
* link to support ticket: [#2023112160001061](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=139629)
* website: https://github.com/aet21/ebGSEA
* installation docs: https://github.com/aet21/ebGSEA (
* toolchain: `foss/2022a`
* easyblock to use: `?`
* required dependencies:
  * [ ] foss/2022a-R-4.2.1
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda:  no
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild:  no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19447

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup
