### ISSUE TITLE
openLISEM

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#25]
* link to support ticket: [#2022082360000253](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=88668)
* website: https://github.com/vjetten/openlisem
* installation docs: https://github.com/vjetten/openlisem/blob/main_C/ubuntu%20compile.txt
* toolchain: `foss/2021b`
* easyblock to use: `CMakeMake`
* required dependencies:
  * see https://github.com/vjetten/openlisem/blob/main_C/ubuntu%20compile.txt
* notes:
  * ...
* effort: *(TBD)*

**Comment by laraPPr** [comment]
@smoors i'm going through the old issues. I saw that you seem to be mostly in contact with users as far as I can see. Are you still following up on this request?

**Comment by smoors** [comment]
the issue is that openLISEM is a pain to get ported from windows to linux
the users wrote a simplified version of the software based on the openLISEM code with help from the developer.

so this can be closed.
