### ISSUE TITLE
llama-cpp-python 

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#250]
* link to support ticket: [#2023112360001315](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=139927)
* website: https://github.com/abetlen/llama-cpp-python
* installation docs: https://github.com/abetlen/llama-cpp-python?tab=readme-ov-file#installation
* toolchain: `?` (Toolchain needs to have pytorch build
* easyblock to use: `CMake?`
* required dependencies:
  * [ ] OpenBlas
  * [ ] cuBLAS
  * [ ] Metal
  * [ ] CLBlast
  * [ ] hipBLAS
* optional dependencies:
  * [ ] ...
* notes:
  * 
* effort: *(TBD)*
* other install methods
  * conda:  no
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64): / no
  * easyconfig outside EasyBuild: / no

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21959

**Comment by boegel** [comment]
@pavelToman PR merged, software installed, ready for cleanup
