### ISSUE TITLE
PyInstaller

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#251]
* link to support ticket: [#2023120260000014](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=140654)
* website: https://pyinstaller.org/en/stable/
* installation docs: https://pyinstaller.org/en/stable/installation.html
* toolchain: `GCCcore-12.3.0 OR foss/2023a`
* easyblock to use: `PythonPackage?`
* required dependencies:
  * [ ] glibc
  * [ ] binutils
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: / no
  * container image:  / no
  * pre-built binaries (RHEL8 Linux x86_64):  / no
  * easyconfig outside EasyBuild: / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19519

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup
