### ISSUE TITLE
Sagemath + plantri

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#253]
* link to support ticket: [#2023120660000043](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=140974)
* website: https://doc.sagemath.org/html/en/index.html + https://doc.sagemath.org/html/en/reference/spkg/plantri.html
* installation docs: https://doc.sagemath.org/html/en/installation/source.html + https://users.cecs.anu.edu.au/~bdm/plantri/
* toolchain: `?`
* easyblock to use: `CMake?`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * Open On Demand has container based solutions where users can install stuff themselves
* effort: *(TBD)*
* other install methods (only for sagemath)
  * conda: https://doc.sagemath.org/html/en/installation/conda.html
  * container image: No
  * pre-built binaries (RHEL8 Linux x86_64): yes (https://doc.sagemath.org/html/en/installation/binary.html)
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20133
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20467
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20469
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20478
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20479
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20481
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20482
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20483
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20550
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20552
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20588
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20589
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20597
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20599
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20600
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20601
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20602
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20603
- ...

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20651

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20652

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20654

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20655

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20753

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20787

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20788

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20789

**Comment by boegel** [comment]
@PetrKralCZ You mentioned that the Sagemath installation currently fails with:
```
      error: command '/apps/gent/RHEL8/cascadelake-ib/software/GCCcore/13.2.0/bin/gcc' failed with exit code 1
      Exception ignored in: <function Pool.__del__ at 0x1481e0e2a2a0>
      Traceback (most recent call last):
        File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/pool.py", line 271, in __del__
          self._change_notifier.put(None)
        File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/queues.py", line 377, in put
          self._writer.send_bytes(obj)
        File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/connection.py", line 199, in send_bytes
          self._send_bytes(m[offset:offset + size])
        File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
          self._send(header + buf)
        File "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/multiprocessing/connection.py", line 367, in _send
          n = write(self._handle, buf)
              ^^^^^^^^^^^^^^^^^^^^^^^^
      OSError: [Errno 9] Bad file descriptor
      [end of output]
```

From the log you provided, it seems like the actual compiler error is this though:
```
      build/cythonized/sage/rings/polynomial/pbori/pbori.cpp:1253:10: fatal error: polybori/pbori_defs.h: No such file or directory
       1253 | #include "polybori/pbori_defs.h"
            |          ^~~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
```

The `OSError` above is probably fallout from the `gcc` compilation command failing.

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21206

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21254

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21283

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21303

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21304

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21305

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21312

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21326

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21327

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21339

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21365

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup \o/ 🥳
