### ISSUE TITLE
Dask v2023.12.0

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#254]
* link to support ticket: [#2023120660000383](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=141008)
* website: https://docs.dask.org/en/stable/
* installation docs: https://docs.dask.org/en/stable/install.html
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19483

**Comment by boegel** [comment]
PR merged, software installed
