### ISSUE TITLE
PyopenCL

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#255]
* link to support ticket: [#2023121060000053](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=141303)
* website: https://mathema.tician.de/software/pyopencl/
* installation docs: https://documen.tician.de/pyopencl/misc.html
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] Python
  * [x] SciPy-Bundle
  * [x] pocl
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19475

**Comment by boegel** [comment]
PR merged, software installed, closing...
