### ISSUE TITLE
mvtnorm and sn (Rpackages)

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#256]
* link to support ticket: [#2023121360003125](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=141926)
* website: https://cran.r-project.org/web/packages/mvtnorm/index.html, https://cran.r-project.org/web/packages/sn/index.html
* installation docs: ...
* toolchain: `foss/2022a`
* easyblock to use: ``
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * can you add "mvtnorm" and "sn" to R-bundle-Bioconductor/3.15-foss-2022a-R-4.2.1 Thanks.
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
both are already included in `R` installation, so closing
