### ISSUE TITLE
flash-attention

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#258]
* link to support ticket: [#2023121960000662](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=142510)
* website: https://github.com/Dao-AILab/flash-attention
* installation docs: https://github.com/Dao-AILab/flash-attention#installation-and-features
* toolchain: `foss/2023a`
* easyblock to use: `?`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21083
