### ISSUE TITLE
OpenFOAM-v7 with `WM_LABEL_SIZE=64`

### ISSUE THREAD

**Issue by WilleBell** [vscentrum/vsc-software-stack#259]
* link to support ticket: [Ticket#2023112760001184](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=140160)
* website: https://openfoam.org/download/7-source/
* installation docs: ...
* toolchain: `foss`
* easyblock to use: `OpenFOAM`
* required dependencies:
* optional dependencies:
* notes:
  * 64-bit integers version
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by WilleBell** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19603

**Comment by boegel** [comment]
@WilleBell Installed on Rome + Milan partitions of Hortense
