### ISSUE TITLE
OpenFOAM-v2206 with `WM_LABEL_SIZE=64`

### ISSUE THREAD

**Issue by WilleBell** [vscentrum/vsc-software-stack#260]
* link to support ticket: [Ticket#2023112760001201](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=140162)
* website:https://dl.openfoam.com/source/v2206/
* installation docs: ...
* toolchain: `foss`
* easyblock to use: `OpenFOAM`
* required dependencies:
* optional dependencies:
* notes:
  * 64-bit integers version
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
`WM_LABEL_SIZE=64` requires:
```python
toolchainopts = {'i8': True}

**Comment by boegel** [comment]
and use `-int64` as `versionsuffix`

**Comment by WilleBell** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19575

**Comment by boegel** [comment]
@WilleBell Installed on Rome + Milan partitions of Hortense
