### ISSUE TITLE
Sentence-Transformers

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#261]
* link to support ticket: [#2023122160000211](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=142683)
* website: https://github.com/UKPLab/sentence-transformers
* installation docs: https://www.sbert.net/docs/installation.html
* toolchain: `foss/2023a`
* easyblock to use: `?`
* required dependencies:
  * [ ] transformers (has exhisting ec but not for foss/2023a) (exts: huggingface-hub)
  * [x] tqdm
  * [ ] Pytorch (can't go to older toolchain because need at least python 3.11)
  * [x] SciPy-bundle (exts: numpy, scipy
  * [x] scikit-learn
  * [ ] NLTK (has exhisting ec but not for foss/2023a)
  * [ ] Sentence-Piece (has exhisting ec but not for GCC/12.3.0)
  * [x] Pillow
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/19509 (CPU-only)
