### ISSUE TITLE
Cartopy v0.22.0

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#262]
* link to support ticket: [#2024010260000444](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=143014)
* website: https://scitools.org.uk/cartopy/docs/latest/
* installation docs: https://scitools.org.uk/cartopy/docs/latest/installing.html
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] Python
  * [ ] Fiona (update easyconfig to new toolchain)
  * [x] GDAL
  * [x] GEOS
  * [x] matplotlib
  * [x] pyproj
  * [x] SciPy-bundle
  * [x] lxml
  * [x] Pillow
  * [x] PROJ
  * [x] PyYAML
* optional dependencies:
  * [ ] ...
* notes:
  * should be installed by 6 march 2024
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/19474
