### ISSUE TITLE
task-spooler

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#27]
* link to support ticket: [#2022090560002159](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=90495)
* website: ...
* installation docs: http://viric.name/soft/ts
* toolchain: `GCCcore/11.3.0`
* easyblock to use: `???`
* required dependencies:
  * ???
* notes:
  * ...
* effort: *(TBD)*

**Comment by ItIsI-Orient** [comment]
PR Open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17048
