### ISSUE TITLE
phyluce

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#271]
* link to support ticket: [#2024010860000782](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=143374)
* website: https://github.com/faircloth-lab/phyluce
* installation docs: https://phyluce.readthedocs.io/en/latest/installation.html
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/faircloth-lab/phyluce/blob/main/distrib/phyluce-1.7.3-py36-Linux-conda.yml
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: [conda environment file available](see https://github.com/faircloth-lab/phyluce/blob/main/distrib/phyluce-1.7.3-py36-Linux-conda.yml)
  * container image: no, but [Dockerfile](https://github.com/faircloth-lab/phyluce/blob/main/docker/Dockerfile) available
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19779

**Comment by boegel** [comment]
PR merged, software installed, ready to close
