### ISSUE TITLE
LRBinner

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#272]
* link to support ticket: [#2024011160001499](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=143875)
* website: https://github.com/anuradhawick/LRBinner
* installation docs: https://github.com/anuradhawick/LRBinner#compiling-the-source-code
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/anuradhawick/LRBinner#dependencies
* notes:
  * definitely use `pip`, may need to run `python setup.py build` via `preinstallopts`
* effort: *(TBD)*
* other install methods
  * conda: yes no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
@PetrKralCZ Can you look at this one next?

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21310

**Comment by boegel** [comment]
@PetrKralCZ PR merged, software installed, ready for cleanup...
