### ISSUE TITLE
GUIDANCE 2.02

### ISSUE THREAD

**Issue by smoors** [vscentrum/vsc-software-stack#273]
* link to support ticket: ...
* website: https://taux.evolseq.net/guidance/source
* installation docs: ...
* toolchain: `...`
* easyblock to use: `...`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by smoors** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19614
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19610
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19615
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19616
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19618
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19617

**Comment by boegel** [comment]
@smoors all easyconfig PRs merged
