### ISSUE TITLE
timm==0.9.7  CUDA

### ISSUE THREAD

**Issue by WilleBell** [vscentrum/vsc-software-stack#276]
* link to support ticket: [Ticket#2024012260001101](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=144803)
* website: https://huggingface.co/docs/timm/index
* installation docs: https://huggingface.co/docs/timm/installation
* toolchain: no preference
* easyblock to use: 
* required dependencies:
  * [maturin]
* optional dependencies:
* notes:
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by WilleBell** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19739

**Comment by boegel** [comment]
installation done on Tier-1 Hortense
