### ISSUE TITLE
deepfold

### ISSUE THREAD

**Issue by smoors** [vscentrum/vsc-software-stack#277]
* link to support ticket: https://vub.service-now.com/nav_to.do?uri=incident.do?sys_id=c2ed161887c88a101801ba6e8bbb357f
* website: https://github.com/newtonjoo/deepfold
* installation docs: see Dockerfile
* toolchain: `...`
* easyblock to use: `...`
* required dependencies:
  * [ ] jax
  * [ ] mpi4jax
  * [ ] tensorflow
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by smoors** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/20247

**Comment by boegel** [comment]
@smoors PR is merged, so this issue can be closed?
