### ISSUE TITLE
FFAVES

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#278]
* link to support ticket: [#2024011660000231](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=144217)
* website: https://github.com/aradley/FFAVES
* installation docs: https://github.com/aradley/FFAVES#installation
* toolchain: `foss/2022a` Asked the user for a newer toolchain will update when I get anwser
* easyblock to use: `PythonPackage`
* required dependencies:
  * [x] numpy==1.20.3 
  * [x] scipy==1.7.3 
  * [x] multiprocess==0.70.12.2
* optional dependencies:
  * [ ] 
* notes:
  * The researcher is using scanpy and this is the newest version  scanpy/1.9.1-foss-2022a  on the system right now -> asking what the software is that they are using so that we can hopefully get the software on a new toolchain.
* effort: *(TBD)*
* other install methods
  * conda:  no
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19822

**Comment by laraPPr** [comment]
@Pavel is this installed already on the clusters?

**Comment by laraPPr** [comment]
It is installed but the ticket in OTRS was not closed yet. I've informed the user and closed the ticket. So everything is good. Thanks Pavel

**Comment by boegel** [comment]
I triggered the installation yesterday evening, was going to inform the user today, but thanks for taking care of that for me :)
