### ISSUE TITLE
RAPIDS

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#279]
* link to support ticket: [#2024011960000716](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=144652)
* website: https://rapids.ai/
* installation docs: https://docs.rapids.ai/install?_gl=1*1erkcod*_ga*MTk4Mzc0ODY2Ny4xNzA2NTQ2Mjc3*_ga_RKXFW6CM42*MTcwNjU0NjI3Ni4xLjAuMTcwNjU0NjI3Ni42MC4wLjA.
* toolchain: `foss/2022a`
* easyblock to use: `...`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] seaborn
* notes:
  * user asked for `foss/2022a` but the only software that he is using that is not on 2023a yet is searborn so maybe should go with `foss/2023a`
* effort: *(TBD)*
* other install methods
  * conda: yes ([link?) / no](https://docs.rapids.ai/install?_gl=1*1erkcod*_ga*MTk4Mzc0ODY2Ny4xNzA2NTQ2Mjc3*_ga_RKXFW6CM42*MTcwNjU0NjI3Ni4xLjAuMTcwNjU0NjI3Ni42MC4wLjA.#conda)à)
  * container image: yes (https://docs.rapids.ai/install?_gl=1*1erkcod*_ga*MTk4Mzc0ODY2Ny4xNzA2NTQ2Mjc3*_ga_RKXFW6CM42*MTcwNjU0NjI3Ni4xLjAuMTcwNjU0NjI3Ni42MC4wLjA.#docker)
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild:  no

**Comment by lexming** [comment]
I'm working on cuML which is part of RAPIDS. Right now I'm writing down an easyconfig for RAFT, one of the dependencies. Issue for reference https://github.com/vscentrum/vsc-software-stack/issues/274

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21058

**Comment by boegel** [comment]
see also #274
