### ISSUE TITLE
TELEMAC

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#28]
* link to support ticket: [#2022090760000335](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=90741)
* website: http://www.opentelemac.org
* installation docs: http://wiki.opentelemac.org/doku.php?id=installation_on_linux
* toolchain: `foss/2022a`?
* easyblock to use: `Binary` (or custom easyblock)
* required dependencies:
  * [x] Fortran compiler
  * [x] Python
  * [x] numpy (via SciPy-bundle)
* optional dependencies:
  * [x] MPI
  * [x] METIS
  * [x] ParMETIS
  * [x] scipy (via SciPy-bundle)
  * [x] matplotlib
  * [x] HDF5
  * [ ] MED
  * [x] SCOTCH
  * [ ] MUMPS (see [PR #16168](https://github.com/easybuilders/easybuild-easyconfigs/pull/16168))
  * [ ] AED
* notes:
  * ...
* effort: *(TBD)*

**Comment by hajgato** [comment]
@boegel can you point me to the logs?

**Comment by boegel** [comment]
With the TELEMAC easyconfig from commit 010d08aca50d6256f8c8f638dc3ec98712408745, I get a working installation, but it's not clear to me whether it's actually fully functional...

The example that's being run as a sanity check command failed (and hence I commented it out in the easyconfig for now), which may be due to a missing dependency.

I'll keep this issue open for now, I have asked the researcher to report back whether or not the installation works for them...

**Comment by boegel** [comment]
TELEMAC is fully working as expected now using the easyconfig file in https://github.com/easybuilders/easybuild-easyconfigs/pull/16274
