### ISSUE TITLE
RFdiffusion/ProteinMPNN/AlphaFold pipeline + ColabDesign

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#283]
* link to support ticket: [#2024012960000591](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=145581)
* website: https://colab.research.google.com/github/sokrypton/ColabDesign/blob/main/rf/examples/diffusion.ipynb
* installation docs: https://github.com/RosettaCommons/RFdiffusion, https://github.com/dauparas/ProteinMPNN, https://colab.research.google.com/github/sokrypton/ColabDesign/blob/main/rf/examples/diffusion.ipynb
* toolchain: `foss/2022a` (where we have AlphaFold already)
* easyblock to use: `???`
* required dependencies:
  * ???
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18359 there is RFdiffusion with models wip

**Comment by boegel** [comment]
@pavelToman Other than finding the WIP PR mentioned above, have you looked into this at all?

I'm asking before I'm looking into setting up a meeting with others (incl. @smoors and @ThomasHoffmann77) to discuss this...

**Comment by pavelToman** [comment]
Not lately, ProteinMPNN-1.0.1-foss-2022a.eb is ready, but not RFdiffusion

**Comment by boegel** [comment]
@pavelToman We've recently installed the latest AlphaFold with `foss/2023a`, see https://github.com/easybuilders/easybuild-easyconfigs/pull/19942 + https://github.com/easybuilders/easybuild-easyconfigs/pull/21628

**Comment by boegel** [comment]
ColabDesign has been installed in user account, closing this until we hear back from them...
