### ISSUE TITLE
FDMNES

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#284]
* link to support ticket: [#2024020560000857](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=146255)
* website: https://fdmnes.neel.cnrs.fr
* installation docs: https://cloud.neel.cnrs.fr/index.php/s/nL2c6kH2PLwcB5r (see also https://fdmnes.neel.cnrs.fr/download)
* toolchain: `gomkl/2023a` (to be compatible with other modules installed with this toolchain)
* easyblock to use: `???`
* required dependencies:
  * MUMPS LAPACK BLAS MPI (based on p7 of manual)
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): yes (https://cloud.neel.cnrs.fr/index.php/s/7MnBxJt2m77rnbi)
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20321

**Comment by boegel** [comment]
PR merged, ready for cleanup
