### ISSUE TITLE
ExtremeLy

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#285]
* link to support ticket: [#2024020960000377]()
* website: https://github.com/SURYA-LAMICHANEY/ExtremeLy
* installation docs: https://github.com/SURYA-LAMICHANEY/ExtremeLy?tab=readme-ov-file#dependencies
* toolchain: `foss/2022a` (must be compatible with `TensorFlow/2.11.0-foss-2022a-CUDA-11.7.0`)
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] lmoments3 (https://github.com/OpenHydrology/lmoments3)
  * [x] scikit-extremes (https://github.com/kikocorreoso/scikit-extremes)
  * [x] evt
  * [x] seaborn
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19870

**Comment by boegel** [comment]
PR merged, ready for cleanup
