### ISSUE TITLE
zUMIs

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#286]
* link to support ticket: [#2024020960000804](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=146761) + [#2024021460000367](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=147155)
* website: https://github.com/sdparekh/zUMIs
* installation docs: https://github.com/sdparekh/zUMIs/wiki/Installation
* toolchain: `foss/2023a`
* easyblock to use: `Tarball`?
* required dependencies:
  * SAMtools, STAR, Rscript, Pigz (see https://github.com/sdparekh/zUMIs/wiki/Installation#dependencies)
* notes:
  * don't just use the `zUMIs.sh` script which relies on conda...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: n
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19949
