### ISSUE TITLE
Circlator

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#287]
* link to support ticket: [#2024021160000023](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=146811)
* website: https://github.com/sanger-pathogens/circlator
* installation docs: https://sanger-pathogens.github.io/circlator
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://sanger-pathogens.github.io/circlator + `setup.py`
* notes:
  * use `circlator progcheck`
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: yes (https://hub.docker.com/r/sangerpathogens/circlator)
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19847

**Comment by laraPPr** [comment]
The user is getting the following error when trying to use Circular:
`circlator.minimus2.Error: toAmos not found in path! Cannot continue`

they then installed the Amos thing with conda that resolved the error message above but than they go this one:
`Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module)`

**Comment by boegel** [comment]
Re-opening, since there's a problem with the installation we should look into...

**Comment by pavelToman** [comment]
`circlator test <DIR>` works fine, but it seems it requires AMOS to work (not in deps). Gonna try create easyconfig for AMOS 2023a.

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20011

**Comment by pavelToman** [comment]
Could users try if it is working now for them?

**Comment by laraPPr** [comment]
reïnstalled and informed the user
