### ISSUE TITLE
ResistanceGA

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#29]
* link to support ticket: [#2022090760001129](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=90820)
* website: https://github.com/wpeterman/ResistanceGA
* installation docs: `README` at https://github.com/wpeterman/ResistanceGA
* toolchain: `foss/2022a`
* easyblock to use: `???`
* required dependencies:
  * [ ] Circuitscape Julia package (https://github.com/Circuitscape/Circuitscape.jl)
    * see also https://petermanresearch.weebly.com/uploads/2/5/9/2/25926970/julia_guide.pdf
* notes:
  * ...
* effort: *(TBD)*

**Comment by boegel** [comment]
For the Julia package dependency, maybe the `JuliaPackage` easyblock from https://github.com/eth-cscs/production/blob/master/easybuild/easyblocks/juliapackage.py can be useful (may need some minor tweaking to remove aspects specific to CSCS)

**Comment by boegel** [comment]
PR for easyconfig without the Julia package dependency: https://github.com/easybuilders/easybuild-easyconfigs/pull/16359

**Comment by boegel** [comment]
@ItIsI-Orient Can you take a look at Circuitscape, should be similar to MultiLevelEstimators...

**Comment by lexming** [comment]
I put in [45_IJulia](https://github.com/vscentrum/vsc-software-stack/tree/main/45_IJulia) the easyblock for `JuliaPackage` and current easyconfigs for IJulia as examples.

**Comment by boegel** [comment]
WIP easyconfig for Circuitspace: https://github.com/easybuilders/easybuild-easyconfigs/pull/16720

**Comment by boegel** [comment]
@ItIsI-Orient https://github.com/easybuilders/easybuild-easyconfigs/pull/16720 merged, so ready for cleanup 🥳

**Comment by lexming** [comment]
Loading `libunwind/1.6.2-GCCcore-11.3.0` (dep of R) breaks the `Pkg` extension of Julia:
```
$ ml

Currently Loaded Modules:
  1) GCCcore/11.3.0   2) XZ/5.2.5-GCCcore-11.3.0   3) libunwind/1.6.2-GCCcore-11.3.0   4) Julia/1.7.2-linux-x86_64

$ julia -e 'using Pkg;Pkg.develop(PackageSpec(path="/user/brussel/101/vsc10122/easybuild/install/skylake/software/ResistanceGA/4.2-5-foss-2022a-R-4.2.1-Julia-1.7.2/packages/Suppressor"));Pkg.build("Suppressor")'
Segmentation fault
```

I do not know exactly what is the linking in Julia that breaks by loading `libunwind`, but it's clear that installing ResistanceGA might very well need a Julia installation using the same toolchain as its dependency in R.

Alternatively, installing `Suppressor` and `RCall` with their own `JuliaPackage` easyconfigs and loading them as deps in ResistanceGA might work if (by any chance) none of their linking is broken by the R environment.

**Comment by boegel** [comment]
A workaround could be to make sure that `julia` picks up the correct `libunwind`, via:

```
export LD_LIBRARY_PATH=$EBROOTJULIA/lib/julia:$LD_LIBRARY_PATH
```

If that's only needed to build/install the Julia packages, maybe it's good enough?

**Comment by ItIsI-Orient** [comment]
PR Open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/18933
