### ISSUE TITLE
ArchR v1.0.2

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#290]
* link to support ticket: [#2024022660001156](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=148642)
* website: https://www.archrproject.com/
* installation docs: https://www.archrproject.com/#installation-of-archr
* toolchain: `foss/2022b`
* easyblock to use: `RPackage`
* required dependencies:
  * [x] ('R', '4.2.2'),
  * [x] ('R-bundle-Bioconductor', '3.16', versionsuffix)
  * [ ] ('presto', '?', versionsuffix),
* optional dependencies:
  * [ ] ...
* notes:
  * Need it to work with MACS3/3.0.0-foss-2022b R-bundle-Bioconductor/3.18-foss-2023a-R-4.3.2
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: [yes](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/a/ArchR/ArchR-1.0.1-foss-2021b-R-4.1.2.eb)

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/19976

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/19979

**Comment by boegel** [comment]
software installed, so closing this...
