### ISSUE TITLE
noise

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#291]
* link to support ticket: [#2024022660001147](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=148641) 
* website: https://pypi.org/project/noise/
* installation docs: https://pypi.org/project/noise/
* toolchain: `?`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] Pyglet
* optional dependencies:
  * [ ] Scipy-Bundle
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/20048

**Comment by boegel** [comment]
installed, so closing...
