### ISSUE TITLE
WGDgc v1.3

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#292]
* link to support ticket: [#2024022360000215](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=148411)
* website: https://github.com/cecileane/WGDgc
* installation docs: https://pages.stat.wisc.edu/~ane/wgd/
* toolchain: `?`
* easyblock to use: `RPAckage`
* required dependencies:
  * [x] R for newer toolchains R-bundle-CRAN
  * [ ] phyext
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda:  no
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild:  no

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/20367
