### ISSUE TITLE
rclone

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#293]
* link to support ticket: [#2024022260000502](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=148240)
* website: https://rclone.org/install/
* installation docs: https://rclone.org/install/#install-from-source
* toolchain: `foss/2023a`
* easyblock to use: `MakeCp`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?)f
  * easyconfig outside EasyBuild: yes

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20038

**Comment by boegel** [comment]
PR merged, ready for cleanup
