### ISSUE TITLE
ED2 (originally ED_R)

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#294]
* link to support ticket: [#2024021660001175](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=147509)
* website: https://pecanproject.github.io/models/ed/docs/articles/running_ed_from_R.html#installing-the-r-package
* installation docs: https://pecanproject.github.io/models/ed/docs/articles/running_ed_from_R.html#installing-the-r-package
* toolchain: `foss/2021b`
* easyblock to use: `RPackage?`
* required dependencies:
  * [ ] R-bundle-Bioconductor/3.15-foss-2021b-R-4.2.0
* optional dependencies:
  * [ ] ...
* notes:
  * user is happy with ED2 instead of ED_R
  * https://pecanproject.github.io/pecan-documentation/master/models-ed.html
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
is this still relevant? https://github.com/EDmodel/ED2/blob/master/ED/build/make/include.mk.ugent
Another useful sites:
https://github.com/EDmodel/ED2
https://github.com/EDmodel/ED2/wiki
https://github.com/EDmodel/ED2/wiki/Using-Github-with-ED2
https://github.com/EDmodel/ED2/wiki/Quick-start
https://github.com/EDmodel/ED2/wiki/Compiler-instructions-%28aka-the-include.mk-files%29

https://github.com/PecanProject/pecan
https://pecanproject.github.io/pecan-documentation/v1.7.1/pecan-manual-setup.html

**Comment by laraPPr** [comment]
First install Pecan. See: https://github.com/vscentrum/vsc-software-stack/issues/309

**Comment by boegel** [comment]
Maybe useful for `ED_R` request: https://pecanproject.github.io/pecan-documentation/v1.7.1/workflow-modules.html#inst-ed2

**Comment by laraPPr** [comment]
It seems that ED_R is no more 

I think this is now what they are using instead https://pecanproject.github.io/pecan-documentation/master/models-ed.html

**Comment by laraPPr** [comment]
@PetrKralCZ this was stuck behind Pecan will you pick it up now again?

**Comment by boegel** [comment]
closing for now, until further notice, asked the researcher whether ED2 is really still needed
