### ISSUE TITLE
fixest 

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#295]
* link to support ticket: [#2024021660000765](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=147468)
* website: https://cran.r-project.org/web/packages/fixest/index.html
* installation docs: https://lrberge.github.io/fixest/
* toolchain: `foss/2023a`
* easyblock to use: `RPackage`
* required dependencies:
  * [x] R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb
  * [x] dreamerr
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild:  no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20029

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20055
