### ISSUE TITLE
currentNe

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#296]
* link to support ticket: [#2024021560000678](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=147299)
* website: https://github.com/esrud/currentNe
* installation docs: https://github.com/esrud/currentNe
* toolchain: `foss/2023a`
* easyblock to use: `?`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild:  no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20791
