### ISSUE TITLE
Transformers in 2023a toolchain

### ISSUE THREAD

**Issue by smoors** [vscentrum/vsc-software-stack#299]
* link to support ticket: INC163749
* website: ...
* installation docs: ...
* toolchain: `2023a`
* easyblock to use: `...`
* required dependencies:
  * [ ] tokenizers
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
@smoors See merged easyconfig PR: 
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20322
