### ISSUE TITLE
python-telegram-bot

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#3]
* link to support ticket: [HPC-UGent OTRS #2022040160001471](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=75439)
* website: https://python-telegram-bot.org
* installation docs: https://docs.python-telegram-bot.org/en/v20.0a0/#installing
* toolchain: `GCCcore/11.2.0`
* easyblock to use: `PythonPackage` or `PythonBundle`
* required dependencies:
  * https://github.com/python-telegram-bot/python-telegram-bot/blob/master/requirements.txt
* notes:
  * ...
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
PR:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16442
