### ISSUE TITLE
FDS 6.7.9

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#30]
* link to support ticket: [#2022090760001503](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=90858)
* website: https://github.com/firemodels/fds
* installation docs: https://github.com/firemodels/fds/wiki
* toolchain: `intel/2022a`
* easyblock to use: *(see existing FDS easyconfigs)*
* notes:
  * straightforward update of `FDS-6.7.7-intel-2021b.eb` didn't seem to work...
* effort: *(TBD)*

**Comment by ItIsI-Orient** [comment]
PR open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16305
