### ISSUE TITLE
MICOM

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#300]
* link to support ticket: [#2024031360000894](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=150503)
* website: https://github.com/micom-dev/micom
* installation docs: https://micom-dev.github.io/micom/installing.html
* toolchain: `foss/2023b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] https://github.com/micom-dev/micom/blob/main/requirements.txt
  * [ ] Gurobi (optional?)
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20186

**Comment by boegel** [comment]
PR merged, ready for cleanup

**Comment by laraPPr** [comment]
@pavelToman, MICOM is installed. You can clean up  300_MICOM and then close this issue.
