### ISSUE TITLE
CellOracle

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#303]
* link to support ticket: [#2024030460000311](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=149265)
* website: https://github.com/morris-lab/CellOracle
* installation docs: https://pypi.org/project/celloracle/
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes (https://github.com/easybuilders/easybuild-easyconfigs/blob/7b65a4c9f02b682953d8fa576f72c8e38c58734f/easybuild/easyconfigs/c/CellOracle/CellOracle-0.12.0-foss-2022a.eb)

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20803

**Comment by boegel** [comment]
PR ready merged, ready for cleanup (installation job submitted)
