### ISSUE TITLE
scFEA

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#304]
* link to support ticket: [#2024030660000362](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=149555)
* website: https://github.com/changwn/scFEA
* installation docs: https://github.com/changwn/scFEA
* toolchain: `foss/2023a`
* easyblock to use: `PythonPackages?`
* required dependencies:
  * [ ] torch
  * [ ] numpy
  * [ ] pandas
  * [ ] matplotlib
  * [ ] magic
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes
  * container image: yes (no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20777

**Comment by boegel** [comment]
all done, merged, installed
