### ISSUE TITLE
simnibs v4

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#307]
* link to support ticket: [#2024031160001191](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=150052)
* website: https://simnibs.github.io/simnibs
* installation docs: https://simnibs.github.io/simnibs/build/html/installation/simnibs_installer.html
* toolchain: `foss/2023a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [x] Python
  * [x] SciPy-bundle
  * [x] h5py
  * [x] NiBabel
  * [x] FMM3D
  * [x] charm-gems
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes (https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/SimNIBS/SimNIBS-3.2.4-foss-2020b.eb)

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20327

**Comment by boegel** [comment]
PR merged, ready for cleanup
