### ISSUE TITLE
pytorch-geometric

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#308]
* link to support ticket: [#2024031260003044](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=150360)
* website: https://pytorch-geometric.readthedocs.io/en/latest/index.html
* installation docs: https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html
* toolchain: `?`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] Python
  * [ ] Pytorch
  * [ ] scikit-learn
  * [ ] scikit-image
  * [ ] numba
  * [ ] h5py
  * [ ] tqdm
  * [ ] RDFlob
  * [ ] ASE
  * [ ] YACS
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) /no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20013
- [PyTorch-Geometric-2.5.0-foss-2023a-PyTorch-2.1.2-CUDA-12.1.1.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/PyTorch-Geometric/PyTorch-Geometric-2.5.0-foss-2023a-PyTorch-2.1.2-CUDA-12.1.1.eb)

**Comment by boegel** [comment]
I've opened a PR for a CPU-only variant as well:
https://github.com/easybuilders/easybuild-easyconfigs/pull/20822

So all done here (other than getting these installed and replying to the request, I'll handle that)
