### ISSUE TITLE
buildingspy

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#31]
* link to support ticket: [#2022091460000723](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=91711)
* website: https://simulationresearch.lbl.gov/modelica/buildingspy
* installation docs: https://simulationresearch.lbl.gov/modelica/buildingspy/install.html
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/lbl-srg/BuildingsPy/blob/master/requirements.txt
* notes:
  * ...
* effort: *(TBD)*

**Comment by ItIsI-Orient** [comment]
I don't see any foss/2022b in existing toolchains... Is that a typo or am I missing something?

**Comment by boegel** [comment]
Typo, go with `foss/2022a`

**Comment by ItIsI-Orient** [comment]
PR open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16308
