### ISSUE TITLE
MeshLab 

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#311]
* link to support ticket: [#2024031860001731](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=150976)
* website: https://www.meshlab.net/
* installation docs: https://www.meshlab.net/#download
* toolchain: `?`
* easyblock to use: `?`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20806

**Comment by boegel** [comment]
PR merged, software installed, ready for cleanup
