### ISSUE TITLE
IEntropy

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#312]
* link to support ticket: [#2024032060000773](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=151169)
* website: https://github.com/LinLi-0909/IEntropy
* installation docs: https://github.com/LinLi-0909/IEntropy
* toolchain: `foss/2023a`
* easyblock to use: `rpackage`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20808

**Comment by boegel** [comment]
PR merged, ready for cleanup
