### ISSUE TITLE
Miniconda 23.10.0

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#313]
* link to support ticket: [#2024032060001138](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=151205)
* website: https://docs.conda.io/en/latest/miniconda.html
* installation docs: https://docs.conda.io/en/latest/miniconda.html
* toolchain: `?`
* easyblock to use: `EB_Anaconda`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20925
