### ISSUE TITLE
napari_microsam

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#314]
* link to support ticket: [#2024032760000841](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=151793)
* website: https://computational-cell-analytics.github.io/micro-sam/micro_sam.html
* installation docs: https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#from-source
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] napari
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
see also discussion in https://github.com/computational-cell-analytics/micro-sam/issues/601

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20636

**Comment by boegel** [comment]
to test microsam:
```
Also when installing the software napari microsam can you test the 3d visualization when typing the following command when importing napari: 

from napari._vispy.utils import gl
 gl.get_max_texture_sizes()
    which should return (32768, 16384)
```

**Comment by pavelToman** [comment]
> to test microsam:
> 
> ```
> Also when installing the software napari microsam can you test the 3d visualization when typing the following command when importing napari: 
> 
> from napari._vispy.utils import gl
>  gl.get_max_texture_sizes()
>     which should return (32768, 16384)
> ```

I try it and got:
```
>>> from napari._vispy.utils import gl
>>> gl.get_max_texture_sizes()
WARNING: could not connect to display 
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted (core dumped)
```
When I tried it in Cluster desktop (with empanada and micro-sam plugins loaded) it returns:
`(16384, 2048)`
When I load only napari and try it it returns same numbers.
