### ISSUE TITLE
empanada-napari

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#315]
* link to support ticket: [#2024032760000886](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=151797)
* website: https://github.com/volume-em/empanada-napari
* installation docs: https://github.com/volume-em/empanada-napari
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] napari?
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20454
