### ISSUE TITLE
napari_denoiseg

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#316]
* link to support ticket: [#2024032760000966](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=151805)
* website: https://juglab.github.io/napari-denoiseg/index.html and https://github.com/juglab/napari-denoiseg/tree/main
* installation docs: https://juglab.github.io/napari-denoiseg/installation.html and https://www.tensorflow.org/install/pip
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20715

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20754

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20933

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20934

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/20934 merged, ready for cleanup
