### ISSUE TITLE
PhyML

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#317]
* link to support ticket: [#2024032860000821](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=151943)
* website: https://github.com/stephaneguindon/phyml
* installation docs: https://github.com/stephaneguindon/phyml
* toolchain: `?`
* easyblock to use: `ConfigureMake`
* required dependencies:
  * [x] ...
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20330
