### ISSUE TITLE
Dictys

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#319]
* link to support ticket: [#2024040460000588](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=152447)
* website: https://github.com/pinellolab/dictys/tree/master
* installation docs: https://github.com/pinellolab/dictys/tree/master?tab=readme-ov-file#installation
* toolchain: `?`
* easyblock to use: `?`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
We got a reminder for this, so bumping priority to get it back into view...

**Comment by pavelToman** [comment]
> We got a reminder for this, so bumping priority to get it back into view...

Next time, please, also change status in Projects from Request to Priority request to let us know that it has higher priority now

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21166
