### ISSUE TITLE
Dorado 0.6.0 or newer

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#320]
* link to support ticket: [#2024040560000684](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=152545) + [#2024041260000189](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=153538) + [#2024042360000668](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=154922) + [#2024042460000568](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=155016) + [#2024051760000991](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156961)
* website: https://github.com/nanoporetech/dorado
* installation docs: https://github.com/nanoporetech/dorado/blob/release-v0.6.0/README.md
* toolchain: `?`
* easyblock to use: `CMakeMake`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
We have a 2nd request for this now, so would be nice to get this one tackled soon.

Should be possible to use `foss/2023a` as toolchain, since `PyTorch/2.1.2-foss-2023a-CUDA-12.1.1` can be used as dependency.
No need to look into CPU-only installation for this one, just go straight for CUDA one.

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20444

**Comment by laraPPr** [comment]
Does this dorado installation the basecalling stuff because there is a specific request for that one? See [#2024041760001213](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=154478)

**Comment by boegel** [comment]
@laraPPr No, that's a totally separate thing I think, since the request points to https://community.nanoporetech.com/downloads (we should ask the user to provide the necessary installation files for that one)

**Comment by boegel** [comment]
https://github.com/nanoporetech/dorado/issues/504 looks useful for `dorado_basecall_server`

**Comment by laraPPr** [comment]
First request for Dorado 0.7.0. should I open a seperate issue? [#2024052260000364](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=157170)

**Comment by boegel** [comment]
> First request for Dorado 0.7.0. should I open a seperate issue? [#2024052260000364](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=157170)

Yes please (since Dorado 0.6.1 is already installed).

I think this one should actually be closed, since the work is done here (other than getting the easyconfig PR merged)

**Comment by laraPPr** [comment]
Ah I did not notice was and this user asked for it 4 days ago [#2024051760000991](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=156961)

**Comment by boegel** [comment]
installed, so closing...
