### ISSUE TITLE
chromVARmotifs

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#321]
* link to support ticket: [#2024040860000464](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=152617)
* website: https://github.com/GreenleafLab/chromVARmotifs
* installation docs: https://github.com/GreenleafLab/chromVARmotifs?tab=readme-ov-file#installation
* toolchain: `foss/2023a`
* easyblock to use: `RPäckage?`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/20402
