### ISSUE TITLE
SCReadCounts

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#322]
* link to support ticket: [#2024041060000343](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=153349)
* website: https://horvathlab.github.io/NGS/SCReadCounts
* installation docs: https://horvathlab.github.io/NGS/SCReadCounts/docs/Installation.html
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] Pysam
  * [ ] SciPy-bundle
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20455

**Comment by boegel** [comment]
merged & installed, ready for cleanup & closing
