### ISSUE TITLE
Histolab

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#329]
* link to support ticket: [#2024041960000498](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=154653)
* website: https://github.com/histolab/histolab
* installation docs: https://histolab.readthedocs.io/en/latest/installation.html
* toolchain: `2022a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] 
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
foss/2023a version:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20886

**Comment by pavelToman** [comment]
foss/2022a version:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20895
