### ISSUE TITLE
scib-pipeline

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#33]
* link to support ticket: [#2022100360002454](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=94981)
* website: https://github.com/theislab/scib-pipeline
* installation docs: https://github.com/theislab/scib-pipeline#installation
* toolchain: `foss/2021b`
* easyblock to use: `???`
* required dependencies:
  * ???
* notes:
  * ...
* effort: *(TBD)*

**Comment by deniskristak** [comment]
starting with these 2 pages of dependencies:
https://github.com/theislab/scib-pipeline/blob/main/envs/scib-pipeline-R4.0.yml
https://github.com/theislab/scib-pipeline/blob/main/envs/scib-R4.0.yml

**Comment by deniskristak** [comment]
turns out we need `scib` first - https://github.com/theislab/scib/blob/main/setup.cfg

**Comment by deniskristak** [comment]
https://github.com/theislab/scib/issues/360 - issue with deprecated dependency

**Comment by deniskristak** [comment]
rpy2 upgrade to 2022a is a bit difficult - here's an issue that was needed:
https://github.com/rpy2/rpy2/issues/974

**Comment by deniskristak** [comment]
https://github.com/theislab/scib-pipeline/issues/53
opened issue at developer's repo...the software itself installs fine, but running the initial example fails immediately

**Comment by laraPPr** [comment]
Asked the user if the installing scib-pipeline is still relevant for them. Will reopen the ticket if the user reaches out that this is still relevant for their research.
