### ISSUE TITLE
scCustomize

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#330]
* link to support ticket: [#2024042260000133](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=154740)
* website: https://cran.r-project.org/web/packages/scCustomize/index.html https://github.com/samuel-marsh/scCustomize
* installation docs: https://cran.r-project.org/web/packages/scCustomize/index.html
* toolchain: `2023a`
* easyblock to use: `RPackage`
* required dependencies:
  * [x] rlang (≥ 1.1.3), in R.eb is v1.1.2
  * [x] paletteer
  * [x] janitor
  * [x] ggprism
  * [x] R-bundle-Bioconductor
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20907

**Comment by boegel** [comment]
PR merged, ready for cleanup
