### ISSUE TITLE
CellBender

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#331]
* link to support ticket: [#2024042260000384](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=154765) 
* website: https://github.com/broadinstitute/CellBender/
* installation docs: https://github.com/broadinstitute/CellBender/
* toolchain: `2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] ...
* optional dependencies:
  * [x] ...
* notes:
  * current installation on our cluster is broken ( CellBender/0.3.1-foss-2022a)
  * The 0.3.1 version has also been recalled so the user is requesting the 0.3.0 version (https://github.com/broadinstitute/CellBender/issues/306)
  * The CUDA version CellBender/0.3.1-foss-2022a-CUDA-11.7.0 is also giving the following error: `error: no cuda devices found`
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20551

**Comment by boegel** [comment]
@pavelToman PR merged, software installed (and modules for CellBender v0.3.1 removed as requested since that version got redacted, cfr. https://github.com/broadinstitute/CellBender/issues/306), so ready for cleanup & closing...
