### ISSUE TITLE
meteogrid

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#332]
* link to support ticket: [#2024042260000599](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=154786)
* website: https://github.com/harphub/meteogrid
* installation docs: https://github.com/harphub/meteogrid
* toolchain: `2023a`
* easyblock to use: `RPackage`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20921

**Comment by boegel** [comment]
PR merged, ready for cleanup
