### ISSUE TITLE
gcloud v472.0.0

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#333]
* link to support ticket: [#2024042360000355](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=154891)
* website: https://cloud.google.com/sdk/gcloud
* installation docs: https://cloud.google.com/sdk/docs/install
* toolchain: `SYSTEM`
* easyblock to use: `Tarball`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/g/gcloud/gcloud-382.0.0.eb
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20523

**Comment by boegel** [comment]
@PetrKralCZ PR merged, software installed, ready for cleanup
