### ISSUE TITLE
SeuratDisk

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#334]
* link to support ticket: [#2024042560000306](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=155083)
* website: https://github.com/mojaveazure/seurat-disk
* installation docs: https://github.com/mojaveazure/seurat-disk?tab=readme-ov-file#Installation
* toolchain: `2023a`
* easyblock to use: `RPackage`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/SeuratDisk/SeuratDisk-0.0.0.9020-foss-2022a-R-4.2.1.eb
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20486

**Comment by boegel** [comment]
PR merged, ready for cleanup & close
