### ISSUE TITLE
HOMER

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#335]
* link to support ticket: [#2024042960000693](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=155291)
* website: http://homer.ucsd.edu/homer/motif/
* installation docs: http://homer.ucsd.edu/homer/introduction/install.html
* toolchain: `?`
* easyblock to use: `?`
* required dependencies:
  * [ ] R
  * [ ] DESeq2
  * [ ] blat
  * [ ] bedGraphToBigWig
  * [ ] liftOver
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20590

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup
