### ISSUE TITLE
Atropos

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#336]
* link to support ticket: [#2024042960001138](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=155335)
* website: https://github.com/jdidion/atropos
* installation docs: https://github.com/jdidion/atropos
* toolchain: `2023a`
* easyblock to use: `PythonPackage?`
* required dependencies:
  * [x] Cython
* optional dependencies:
  * [x] pytest
  * [x] progressbar2 or tqdm
  * [x] pysam
  * [x] khmer
  * [x] jinja2
  * [x] ngstream
* notes:
  * https://github.com/easybuilders/easybuild-easyconfigs/blob/d5cf80e3c57ad6eedfebcb6da88d4e94b0856293/easybuild/easyconfigs/a/atropos/atropos-1.1.21-intel-2018b-Python-3.6.6.eb#L3
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20557
