### ISSUE TITLE
rhandsontable

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#338]
* link to support ticket: [#2024050560000021](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=155702)
* website: https://cran.r-project.org/web/packages/rhandsontable/index.html
* installation docs: https://github.com/jrowen/rhandsontable
* toolchain: `foss/2023a`
* easyblock to use: `R-Package`
* required dependencies:
  * [ ] 
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20537

**Comment by boegel** [comment]
I've collapsed `rhandsontable` as extension into `R-bundle-CRAN` instead, see:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20614

**Comment by boegel** [comment]
@PetrKralCZ installed via https://github.com/easybuilders/easybuild-easyconfigs/pull/20614, ready for cleanup & closing...
