### ISSUE TITLE
wfdb

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#339]
* link to support ticket: [#2024050660001214](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=155835)
* website: https://wfdb.readthedocs.io/en/latest/
* installation docs: https://github.com/MIT-LCP/wfdb-python
* toolchain: `foss/2022a`
* easyblock to use: `PythonPackage?`
* required dependencies:
  * [ ] libsndfile
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20521

**Comment by boegel** [comment]
@PetrKralCZ PR merged, software installed, ready for cleanup
