### ISSUE TITLE
ruffus

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#34]
* link to support ticket: [#2022072860000255](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=86564)
* website: http://www.ruffus.org.uk
* installation docs: http://www.ruffus.org.uk/installation.html
* toolchain: `foss/2021b`
* easyblock to use: `PythonPackage` or `PythonBundle`
* required dependencies:
  * [x] Python
* notes:
  * required dependency for Finder (see issue #21)
  * keep notes on creating an easyconfig file for a Python package
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/16428
