### ISSUE TITLE
Dorado 0.7.0

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#343]
* link to support ticket: [#2024052260000364](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=157170) + [#2024052260000801](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=157214)
* website: https://github.com/nanoporetech/dorado
* installation docs: https://github.com/nanoporetech/dorado/blob/release-v0.6.0/README.md 
* toolchain: `?`
* easyblock to use: `CmakeMake`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20596

**Comment by boegel** [comment]
installed, so closing
