### ISSUE TITLE
Trycycler

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#347]
* link to support ticket: [#2024052260000908](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=157224)
* website: https://github.com/rrwick/Trycycler
* installation docs: https://github.com/rrwick/Trycycler
* toolchain: `foss/2023a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [x] Python
  * [x] SciPy-bundle
  * [x] R
  * [x] edlib
  * [x] miniasm
  * [x] minimap2
  * [x] Mash
  * [x] MUSCLE  
  * [x] Pillow
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20924

**Comment by boegel** [comment]
PR merged, ready for cleanup
