### ISSUE TITLE
Visit

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#349]
* link to support ticket: [#2024060460000771](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=158630)
* website: https://visitusers.org/index.php?title=Main_Page
* installation docs: https://visitusers.org/index.php?title=Downloading_and_Installing_VisIt#How_to_install_VisIt
* toolchain: `foss/2023a?`
* easyblock to use: `CMakeMake`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * never merged but could be good starting point https://github.com/easybuilders/easybuild-easyconfigs/pull/15109/files
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
@akesandgren: Do you happen to remember where we got stuck with https://github.com/easybuilders/easybuild-easyconfigs/pull/15109?
Do you happen to have updated easyconfigs for VisIt in-house?

**Comment by akesandgren** [comment]
No updates, I still only have Visit-3.2.2-foss-2020a-Python-3.8.2.eb installed.
Haven't had any requests for it since then.

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20981

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20982
