### ISSUE TITLE
AMS 2022.102

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#35]
* link to support ticket: [#2022100460000516](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=95094)
* website: https://www.scm.com/amsterdam-modeling-suite
* installation docs: https://www.scm.com/doc/Installation/Installation.html
* toolchain: `SYSTEM`
* easyblock to use: (see existing `AMS` easyconfig)
* required dependencies:
  * ??
* notes:
  * already installed on VUB Tier-2
* effort: *(TBD)*

**Comment by smoors** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/16358

**Comment by boegel** [comment]
PR merged, so closing this, thanks @smoors!
