### ISSUE TITLE
FDS 6.9.1 AND SMV 6.9.1

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#351]
* link to support ticket: [#2024061160001168](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=159276)
* website: https://pages.nist.gov/fds-smv/downloads.html
* installation docs: https://github.com/firemodels/fds/wiki/Installing-and-Running-FDS-on-a-Linux-Cluster
* toolchain: `intel/2023a?`
* easyblock to use: `ConfigureMake`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * https://github.com/easybuilders/easybuild-easyconfigs/tree/0c80144b30fd75b4729dad480e09efbf2505c507/easybuild/easyconfigs/f/FDS
  * https://github.com/easybuilders/easybuild-easyconfigs/tree/0c80144b30fd75b4729dad480e09efbf2505c507/easybuild/easyconfigs/s/SMV
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
I've done some work on this already, FDS seems to be working, but still having some trouble with SMV.

WIP easyconfigs available in [wip branch](https://github.com/vscentrum/vsc-software-stack/tree/wip/351_FDS_SMV)

**Comment by boegel** [comment]
see also #445 (for FDS)

@pavelToman Can you also take a look at SMV?

**Comment by pavelToman** [comment]
FDS merged:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21768

**Comment by pavelToman** [comment]
SMV PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/22036

**Comment by boegel** [comment]
@pavelToman Did you try to start the SMV GUI?

When I do that (in a desktop session on donphan, 8 cores), it fails to start:
```
smokeview[10:42:40] {donphan} vsc40023@node4012:~ $ smokeview

Smokeview  - Dec 17 2024 - 09:54:06

Revision         : unknown
Revision Date    : unknown
Compilation Date : Dec 17 2024 09:54:06
Compiler         : GCC 12.3.0
Checksum(SHA1)   : 8041c2a2c9a0de1853eec50444d92cde271c1f00
Platform         : LINUX64
Smokeview path   : /kyukon/scratch/gent/vo/000/gvo00002/vsc40023/easybuild_REGTEST/RHEL8/cascadelake-ampere-ib/software/SMV/6.9.5-GCCcore-12.3.0/bin/smokeview
Root directory   : /kyukon/scratch/gent/vo/000/gvo00002/vsc40023/easybuild_REGTEST/RHEL8/cascadelake-ampere-ib/software/SMV/6.9.5-GCCcore-12.3.0/bin/
Global ini       : not found
Casename ini     : not found

function is no-op
   GLEW initialization failed
reading  (null)
  wrapping up
Segmentation fault (core dumped)
```

**Comment by pavelToman** [comment]
> @pavelToman Did you try to start the SMV GUI?
> 
> When I do that (in a desktop session on donphan, 8 cores), it fails to start:
> 
> ```
> smokeview[10:42:40] {donphan} vsc40023@node4012:~ $ smokeview
> 
> Smokeview  - Dec 17 2024 - 09:54:06
> 
> Revision         : unknown
> Revision Date    : unknown
> Compilation Date : Dec 17 2024 09:54:06
> Compiler         : GCC 12.3.0
> Checksum(SHA1)   : 8041c2a2c9a0de1853eec50444d92cde271c1f00
> Platform         : LINUX64
> Smokeview path   : /kyukon/scratch/gent/vo/000/gvo00002/vsc40023/easybuild_REGTEST/RHEL8/cascadelake-ampere-ib/software/SMV/6.9.5-GCCcore-12.3.0/bin/smokeview
> Root directory   : /kyukon/scratch/gent/vo/000/gvo00002/vsc40023/easybuild_REGTEST/RHEL8/cascadelake-ampere-ib/software/SMV/6.9.5-GCCcore-12.3.0/bin/
> Global ini       : not found
> Casename ini     : not found
> 
> function is no-op
>    GLEW initialization failed
> reading  (null)
>   wrapping up
> Segmentation fault (core dumped)
> ```

Yes, I have tested it on desktop cluster. 
This error shows either for me, if I run just `smokeview`, but after I run `smokeview example.smv` it works - it needs the smv file for configuration.
Error detail without smv file config is:
```
Thread 1 "smokeview" received signal SIGSEGV, Segmentation fault.
0x00000000005541cc in UpdateIsoColors ()
0x00000000004d692e in ReadSMV_Configure ()
0x00000000004d7faa in ReadSMV ()
0x000000000057a5b3 in SetupCase ()
0x00000000004072a4 in main ()
```

the smv config file is there: easybuild/easyconfigs/s/SMV/example.smv
