### ISSUE TITLE
Medaka

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#352]
* link to support ticket: [#2024060960000039](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=159006)
* website: https://github.com/nanoporetech/medaka
* installation docs: https://github.com/nanoporetech/medaka
* toolchain: `foss/2023b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * Their is a problem with the current installations of medaka the user is not able to use it as intended
  * They left some instructions on how to test and I will have a look at why the older versions are not doing what is expected
  * I saw that recently medaka 1.12.0 so it might  be interesting to try to get that one installed
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20844

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20845

**Comment by boegel** [comment]
@PetrKralCZ Let's stick to `foss/2023a` for this, since we don't have TensorFlow with `2023b` yet.

This was requested with GPU support though, so we'll need TensorFlow with `foss/2023a` + CUDA`

@laraPPr Can you dig up more details on what wasn't working with previous versions, and drop that info in here so @PetrKralCZ can check on that?

**Comment by laraPPr** [comment]
Ok just ran it quickly on their account and it might be something on their site

because they are doing this in the script 

`model='/kyukon/scratch/gent/vo/000/gvo00011/vsc40014/rerio/dorado_models/res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1`

```
Cannot import pyabpoa, some features may not be available.

Cannot import pyabpoa, some features may not be available.

Cannot import pyabpoa, some features may not be available.

Checking program versions

This is medaka 1.11.3

Cannot import pyabpoa, some features may not be available.

Program    Version    Required   Pass     

bcftools   1.18       1.11       True     

bgzip      1.18       1.11       True     

minimap2   2.26       2.11       True     

samtools   1.18       1.11       True     

tabix      1.18       1.11       True     

Cannot import pyabpoa, some features may not be available.

Traceback (most recent call last):

  File "/apps/gent/RHEL8/cascadelake-ib/software/medaka/1.11.3-foss-2023a/bin/medaka", line 8, in <module>

    sys.exit(main())

             ^^^^^^

  File "/apps/gent/RHEL8/cascadelake-ib/software/medaka/1.11.3-foss-2023a/lib/python3.11/site-packages/medaka/medaka.py", line 814, in main

    args.func(args)

  File "/apps/gent/RHEL8/cascadelake-ib/software/medaka/1.11.3-foss-2023a/lib/python3.11/site-packages/medaka/medaka.py", line 316, in is_rle_model

    print(is_rle_encoder(args.model))

          ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/apps/gent/RHEL8/cascadelake-ib/software/medaka/1.11.3-foss-2023a/lib/python3.11/site-packages/medaka/medaka.py", line 322, in is_rle_encoder

    modelstore = medaka.models.open_model(model_name)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/apps/gent/RHEL8/cascadelake-ib/software/medaka/1.11.3-foss-2023a/lib/python3.11/site-packages/medaka/models.py", line 222, in open_model

    raise ValueError(

ValueError: Model /kyukon/scratch/gent/vo/000/gvo00011/vsc40014/rerio/dorado_models/res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1 does not have .hdf5 or .gz extension.
```

**Comment by boegel** [comment]
@laraPPr What did you run to get this output?

**Comment by laraPPr** [comment]
`medaka_consensus -t 24 -o $out -m $model -d $genome -i $reads`

**Comment by laraPPr** [comment]
The model is from here https://github.com/nanoporetech/rerio

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20865

**Comment by boegel** [comment]
Looks like `pyabpoa` is a missing dependency?
If that can be added, we'll install medaka v1.12.0 and see if that works

**Comment by boegel** [comment]
GPU variant requires:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20358

**Comment by PetrKralCZ** [comment]
GPU variant:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21210

**Comment by boegel** [comment]
overlaps with #361, all done, ready for cleanup & closing
