### ISSUE TITLE
EGA-QuickView + crypt4gh

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#353]
* link to support ticket: [#2024061760001031](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=159793)
* website: https://github.com/EGA-archive/ega-quickview + https://crypt4gh.readthedocs.io
* installation docs: https://github.com/EGA-archive/ega-quickview + https://crypt4gh.readthedocs.io/en/latest/setup.html
* toolchain: `foss/2023b`
* easyblock to use: `???`
* required dependencies:
  * see https://github.com/EGA-archive/ega-quickview?tab=readme-ov-file#installation + https://github.com/EGA-archive/crypt4gh/blob/master/requirements.txt
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20870
