### ISSUE TITLE
rMATS-long

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#355]
* link to support ticket: [#2024062560000661](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=160376)
* website: https://github.com/Xinglab/rMATS-long
* installation docs: https://github.com/Xinglab/rMATS-long?tab=readme-ov-file#dependencies
* toolchain: `foss/2023a`?
* easyblock to use: `Tarball`?
* required dependencies:
  * see https://github.com/Xinglab/rMATS-long?tab=readme-ov-file#dependencies
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20916

**Comment by boegel** [comment]
PR merged, ready for cleanup
