### ISSUE TITLE
ilastik-napari + nellie

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#359]
* link to support ticket: [#2024070160000891](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=160864)
* website: https://github.com/ilastik/ilastik-napari
* installation docs: https://github.com/ilastik/ilastik-napari
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR 
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21003

**Comment by boegel** [comment]
@pavelToman `nellie` was also requested as additional tool here, can you look into that too?

https://github.com/aelefebv/nellie

**Comment by pavelToman** [comment]
PR nellie:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21256

**Comment by boegel** [comment]
@pavelToman PR for CPU-only `nellie` merged.

Can you also look into a variant of `nellie` that has CUDA support?
It requires an additional extension, see https://github.com/aelefebv/nellie?tab=readme-ov-file#option-2-via-pip

**Comment by pavelToman** [comment]
PR nellie-CUDA:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21267

**Comment by boegel** [comment]
@pavelToman All merged and installed, ready for cleanup
