### ISSUE TITLE
Dorado

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#360]
* link to support ticket: [#2024070360000861](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=161112)
* website: https://github.com/nanoporetech/dorado
* installation docs: https://github.com/nanoporetech/dorado
* ~~toolchain: `foss/2023b`~~
* toolchain: `foss/2023a`
* easyblock to use: `CMakeMake`
* required dependencies:
  * [x] Flye
  * [x] Medaka
* optional dependencies:
  * [ ] ...
* notes:
  * 
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
see also:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20444
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20596

Update is likely trivial based on that, but we should try and figure out why https://github.com/easybuilders/easybuild-easyconfigs/pull/20444 got stuck...

**Comment by pavelToman** [comment]
#362, https://github.com/vscentrum/vsc-software-stack/issues/361 and https://github.com/vscentrum/vsc-software-stack/issues/360 need to be compatible because the user wants to use them together

**Comment by pavelToman** [comment]
There is no PyTorch for foss/2023b with CUDA yet
-> added to stopped issues for now

**Comment by pavelToman** [comment]
After meeting 2/8/24 -> stick to foss/2023a not 2023b

**Comment by pavelToman** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/20596 could resolve this issue

**Comment by boegel** [comment]
re-opening since we need a PR for latest version of dorado

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21234
