### ISSUE TITLE
Flye

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#362]
* link to support ticket: [#2024070360000851](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=161111)
* website: https://github.com/mikolmogorov/Flye
* installation docs: https://github.com/mikolmogorov/Flye/blob/flye/docs/INSTALL.md
* ~~toolchain: `foss/2023b`~~
* toolchain: `foss/2023a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [x] ...
* optional dependencies:
  * [ ] Dorado
  * [ ] medaka
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by laraPPr** [comment]
#362, https://github.com/vscentrum/vsc-software-stack/issues/361 and https://github.com/vscentrum/vsc-software-stack/issues/360 need to be compatible because the user wants to use them together

**Comment by pavelToman** [comment]
After meeting 2/8/24 -> stick to foss/2023a not 2023b -> flye for foss/2023a is already in EB
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/f/Flye/Flye-2.9.3-GCC-12.3.0.eb

**Comment by pavelToman** [comment]
PR for 2023b:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21109

**Comment by PetrKralCZ** [comment]
EESSI
=====
2023a
-----
```
1 out of 11 required modules missing:

* Flye/2.9.3-GCC-12.3.0 (Flye-2.9.3-GCC-12.3.0.eb)
```
2023b
-----
```
1 out of 11 required modules missing:

* Flye/2.9.4-GCC-13.2.0 (Flye-2.9.4-GCC-13.2.0.eb)
```

**Comment by boegel** [comment]
@PetrKralCZ Did you try actually installing it?

**Comment by PetrKralCZ** [comment]
> [@PetrKralCZ](https://github.com/PetrKralCZ) Did you try actually installing it?

@boegel Both installed successfully under EESSI.
I can open EESSI PRs tomorrow. Shout it be for both `2023a` and `2023b` version?

**Comment by boegel** [comment]
Can be both (in same PR, but separate easystack file)

**Comment by PetrKralCZ** [comment]
@boegel ESSI PR open https://github.com/EESSI/software-layer/pull/1179
