### ISSUE TITLE
CDO with `iimpi/2022a`

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#365]
* link to support ticket: [#2024021360000323](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=147022)
* website: https://code.mpimet.mpg.de/projects/cdo
* installation docs: *(see existing CDO easyconfigs)*
* toolchain: `iimpi/2022a`
* easyblock to use: *(see existing CDO easyconfigs)*
* required dependencies:
  * *(see existing CDO easyconfigs)*
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
I've already spent quite a bit of time on this, but I'm stuck on a compiler error.
WIP easyconfigs available in `wip` branch, see [here](https://github.com/vscentrum/vsc-software-stack/tree/wip/365_CDO).

Must use `iimpi/2022a`, because it must be compatible with other modules like NCO (see https://github.com/easybuilders/easybuild-easyconfigs/pull/19848) & more.

**Comment by pavelToman** [comment]
Seems the `toolchainopts = {'pic': True, 'usempi': True}` help and it could be build without errors.

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21164
