### ISSUE TITLE
OpenFOAM v2406

### ISSUE THREAD

**Issue by WilleBell** [vscentrum/vsc-software-stack#366]
* link to support ticket: https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=161324
* website: https://www.openfoam.com/
* installation docs: 
* toolchain: 
* easyblock to use: 
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda:  no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by WilleBell** [comment]
-  https://github.com/easybuilders/easybuild-easyconfigs/pull/21036

**Comment by boegel** [comment]
@WilleBell PR is merged, `OpenFOAM/v2406-foss-2023a` is installed on Hortense, this can be closed?
