### ISSUE TITLE
EvidentialGene

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#367]
* link to support ticket: [#2024070660000061](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=161835)
* website: http://arthropods.eugenes.org/EvidentialGene/
* installation docs: http://arthropods.eugenes.org/EvidentialGene/evigene/docs/EvidentialGene_howto.txt
* toolchain: `gompi?`
* easyblock to use: `PackedBinary`
* required dependencies:
  * [x] Perl
  * [x] Exonerate
  * [x] CD-HIT
  * [x] BLAST+
* optional dependencies:
  * [x] ...
* notes:
  * The following features need to work: TR2AACDS PIPELINE ALGORITHM
  * exhisting older easyconfig: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/e/EvidentialGene/EvidentialGene-2022.01.14-gompi-2021b.eb
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21106

**Comment by laraPPr** [comment]
reopening for https://github.com/easybuilders/easybuild-easyconfigs/pull/21106

**Comment by laraPPr** [comment]
@pavelToman installed and ready for clean-up
