### ISSUE TITLE
RStudio-Server

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#368]
* link to support ticket: [#2024071260000478](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=162221)
* website: https://www.rstudio.com/
* installation docs: https://posit.co/downloads/
* toolchain: `gfbf/2023a`
* easyblock to use: `CMakeNinja`
* required dependencies:
  * [x] https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2023.12.1%2B402-gfbf-2023b-Java-11-R-4.3.3.eb
* optional dependencies:
  * [x] ...
* notes:
  * Needs to be compatible with R/4.3.2-gfbf-2023a 
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21086
