### ISSUE TITLE
scenicplus

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#369]
* link to support ticket: [#2024071860000145](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=162543)
* website: https://github.com/aertslab/scenicplus
* installation docs: https://github.com/aertslab/scenicplus
* toolchain: `foss/2023a?`
* easyblock to use: `PythonPackage?`
* required dependencies:
  * [x] [adjustText-1.1.1-foss-2023a.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/1935292879bb167293652deff12e46d73d1e3e88/easybuild/easyconfigs/a/adjustText/adjustText-1.1.1-foss-2023a.eb#L3)
  * [x] [aiohttp-3.8.5-GCCcore-12.3.0.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/1935292879bb167293652deff12e46d73d1e3e88/easybuild/easyconfigs/a/aiohttp/aiohttp-3.8.5-GCCcore-12.3.0.eb)
  * [ ] https://github.com/aertslab/scenicplus/blob/main/requirements.txt
* optional dependencies:
  * [ ] ...
* notes:
  * not the same as https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/SCENIC/SCENIC-1.3.0-foss-2023a-R-4.3.2.eb
  * Had a first look at the dependencies and this seems like a very long list
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by laraPPr** [comment]
I am going through the dependencies right now to see how long it would take

**Comment by laraPPr** [comment]
closing duplicate https://github.com/vscentrum/vsc-software-stack/issues/64

**Comment by pavelToman** [comment]
I am quiet close to have this done - https://github.com/vscentrum/vsc-software-stack/blob/wip/64_scenicplus/scenicplus-2023a.eb
Last thing I am working on is to make `scenicplus init_snakemake --out_dir` works.

EDIT:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21085

**Comment by laraPPr** [comment]
Thanks Pavel I saw it I'll close it again so that we don't have a duplicate anymore
