### ISSUE TITLE
PySCF 2.1.x

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#37]
* link to support ticket: [Ticket#2022100660001548 ](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=95762)
* website: https://pyscf.org/index.html
* installation docs: https://pyscf.org/install.html
* toolchain: `foss/2022a`
* easyblock to use: *(see existing PySCF easyconfigs)*
* required dependencies:
  * *(see existing PySCF easyconfigs)*
* notes:
  * try to install with all extension modules, and test whether they're indeed installed; see also https://pyscf.org/install.html#extension-modules
* effort: *(TBD)*

**Comment by lexming** [comment]
@boegel I got a ticket for this, what's the status on your side?

**Comment by boegel** [comment]
@lexming @PetrKralCZ is looking into this, see WIP easyconfigs in https://github.com/vscentrum/vsc-software-stack/tree/main/37_PySCF

It's not a trivial version update, PySCF got splintered into a whole bunch of components, several of which cause trouble...

**Comment by lexming** [comment]
PRs to get `dmrgscf` working:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16710
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16711

**Comment by lexming** [comment]
PRs with direct dependencies of PySCF:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16749
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16750

PR with dependency of `fciqmc`:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16751

PR with dependency of `icmpspt`:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16752

**Comment by lexming** [comment]
I updated the [easyconfig + patches of PySCF v2.1.1](37_PySCF) with my last developments. I got a working installation of PySCF with the modules in its `all` set of extras plus `dmrgscf`, `fciqmcscf`, `hci`, `mbd`, `tblis` and `zquatev`.

The only extensions missing from the list in https://pyscf.org/install.html#extension-modules are `cornell-shci` (needs non-public program), `rt` (does not exist any more)  and `nao` (deprecated, now is a standalone program).

On my side, this is ready. Please test and let me know if this is also ok for you.

**Comment by boegel** [comment]
@lexming Can you open a PR for `PySCF-2.1.1-foss-2022a.eb` already, so we know which dependency PRs to merge to get that in?

**Comment by boegel** [comment]
PR merged, ready for cleanup (removing the `37_PySCF` subdirectory in this repo)

**Comment by lexming** [comment]
Leave this open to not forget about:
* https://github.com/easybuilders/easybuild-easyconfigs/issues/17164#issuecomment-1398138724

**Comment by boegel** [comment]
Let's close this, we have an open issue for the problem with the NECI tests
