### ISSUE TITLE
accelerate

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#370]
* link to support ticket: [#2024071960000143](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=162605)
* website: https://pypi.org/project/accelerate/
* installation docs: https://huggingface.co/docs/accelerate/main/en/basic_tutorials/install#installing--accelerate
* toolchain: `PythonPackage?`
* easyblock to use: `foss/2023a`
* required dependencies:
  * [x] Ppytorch
  * [x] transformers
* optional dependencies:
  * [x] ...
* notes:
  * The user has a test script in his account
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21107
