### ISSUE TITLE
nanopolish 

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#371]
* link to support ticket: [#2024071960000214](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=162612)
* website: https://github.com/jts/nanopolish
* installation docs: https://github.com/jts/nanopolish
* toolchain: `foss/2023a`
* easyblock to use: `MakeCp`
* required dependencies:
  * [x]    ('zlib', '1.2.12'),
  * [x] ('Python', '3.10.4'),
  * [x] ('Biopython', '1.79'),
  * [x] ('Pysam', '0.19.1'),
  * [x] ('HDF5', '1.12.2'),
  * [x] ('HTSlib', '1.15.1'),
  * [x] ('minimap2', '2.24'),
  * [x] ('VBZ-Compression', '1.0.3'),
* optional dependencies:
  * [x] ...
* notes:
  * The user needs on shinx so needs to be on 2023a or older
  * Also have to them if it is possible to move their pipeline to a newer toolchain because she actually asked to install an older toolchain on shinx
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21087
