### ISSUE TITLE
porechop

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#372]
* link to support ticket: [#2024071960000223](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=162613)
* website: https://github.com/rrwick/Porechop
* installation docs: https://github.com/rrwick/Porechop
* toolchain: `GCCcore/12.3.0`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [x] Python
* optional dependencies:
  * [ ] ...
* notes:
  * needs it on shinx so needs to be 12.3.0 or older
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21784

**Comment by laraPPr** [comment]
installing now

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
