### ISSUE TITLE
LAMMPS 27JUN2024

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#373]
* link to support ticket: [#2024072460000348](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=162920)
* website: https://www.lammps.org/index.html#gsc.tab=0
* installation docs: https://www.lammps.org/download.html
* toolchain: `foss/2023b`
* easyblock to use: `LAMMPS`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by laraPPr** [comment]
There is no stable release yet with the feature. I'll see how far I'll get with installing the feature release.

**Comment by MaximeVdB** [comment]
Hi Lara -- I actually happen to have dealt with an identical request last week. But I then didn't think of contributing it since it's not a stable release and that request got modified afterwards. I will push to a branch for you to have a look at it.

**Comment by laraPPr** [comment]
Thanks am very familliar with LAMMPS as well so I am testing a build as well to see if it passes

**Comment by laraPPr** [comment]
Ah it might be the same person because it is a KU Leuven account

**Comment by MaximeVdB** [comment]
On our side, I ultimately installed it with foss-2023a instead, which is easily done starting from the existing `LAMMPS-2Aug2023_update2-foss-2023a-kokkos.eb` and with a small (ad-hoc) modification of the [lammps easyblock](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/l/lammps.py#L472).

**Comment by laraPPr** [comment]
ah also ran into that one. I was looking for it and to see what I had done wrong because I made that patch and changed that part of the easyblock. gonna see if I can make that part more generic.

**Comment by laraPPr** [comment]
installed and informed user
