### ISSUE TITLE
missMDA

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#374]
* link to support ticket: [#2024073060000247](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=163117)
* website: https://cran.r-project.org/web/packages/missMDA/index.html
* installation docs: https://cran.r-project.org/doc/manuals/r-patched/R-admin.html
* toolchain: `foss/2023a`
* easyblock to use: `RPackage`
* required dependencies:
  * [x] R-4.3.2-gfbf-2023a.eb
  * [x] R-bundle-CRAN-2023.12-foss-2023a.eb
* optional dependencies:
* notes:
  * If it is simple enough it can simply be added to the R-Bundle-CRAN
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21167
