### ISSUE TITLE
MBX

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#377]
* link to support ticket: [#2024073060000792](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=163172)
* website: https://github.com/paesanilab/MBX
* installation docs: https://github.com/paesanilab/MBX
* toolchain: `foss/2023a`
* easyblock to use: `Make? PythonPackage?`
* required dependencies:
  * [ ] ~~MBX_MPI~~
    * [ ] LAMMPS
  * [x] MBX_BASIC
    * [x] i-PI
    * [x] Python
* optional dependencies:
  * [x] ...
* notes:
  * ~~The user want two seperate installations~~
  * he wants the python library which is the basic one 
  * ~~and he wants the one compatible with lammps (which is not compatible with anything else) MBX_MPI~~
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by laraPPr** [comment]
They let us know that they will need it in the coming weeks for a review of a paper. If later it is no longer relevant for them

**Comment by boegel** [comment]
@pavelToman I spent some time on this last Friday, and have a draft easyconfig for it, see [wip branch](https://github.com/vscentrum/vsc-software-stack/tree/wip/377_MBX)

It needs a bit more love, and this is only the non-LAMMPS part. For MBX via LAMMPS, will probably need to provide a separate installation of LAMMPS, since some code has to be copied from MBX into LAMMPS.

I'll ask the researchers whether they actually need the LAMMPS integration before we look into that though...

**Comment by boegel** [comment]
Sanity check command needs a bit of work, there's no `--help`, but just running it without options is the equivalent and has exit code 0:

```
$ optimize --help
** ERROR ** C++ Exception in function ReadNrg, in line 52 of file io_tools/read_nrg.cpp. Could not open NRG file --help for reading.
Segmentation fault (core dumped)
```

```
$ optimize
Usage: optimize <config.nrg> [<mbx.json>] [<max iterations>] [<tolerance>] [<configs.xyz>] [<step>]
$ echo $?
0
```

**Comment by boegel** [comment]
For now being able to just install MBX standalone is enough, there's no need (yet) to also look into LAMMPS+MBX.

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21155

**Comment by boegel** [comment]
PR merged, ready for cleanup
