### ISSUE TITLE
Julia 1.10.4

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#378]
* link to support ticket: [#2024073160000281](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=163209)
* website: https://julialang.org/downloads/#current_stable_release
* installation docs: https://julialang.org/downloads/
* toolchain: `SYSTEM`
* easyblock to use: `JuliaBundle`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by lexming** [comment]
@laraPPr I have a PR open for version 1.10.3 if that is useful:

* https://github.com/easybuilders/easybuild-easyconfigs/pull/20662

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21177
