### ISSUE TITLE
EMMAX

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#379]
* link to support ticket: [#2024080160000264](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=163275)
* website: https://csg.sph.umich.edu//kang/emmax/download/index.html
* installation docs: https://csg.sph.umich.edu//kang/emmax/download/index.html
* toolchain: `2023a`
* easyblock to use: `Tarball?`
* required dependencies:
  * [ ] ?
* optional dependencies:
  * [ ] ...
* notes:
  * Had a look at it and except for how to download the sources I could not really find anythin
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
It is 14y old sw - seems it needs ATLAS to be built with foss toolchain. Seems can be built either with intel toolchain, there is a build.sh script but some of the files missing in new intel compilers and mkl, like `libguide.a`. 
Build script for intel: https://github.com/vscentrum/vsc-software-stack/blob/wip/379_EMMAX/emmax_build.sh.comments

**Comment by boegel** [comment]
You can probably just replace the linking to ATLAS libraries with linking to FlexiBLAS (which is included in foss) instead, ATLAS is a BLAS/LAPACK library.
Definitely don't try to install ATLAS, since it's no longer maintained (see https://sourceforge.net/projects/math-atlas/files/Stable).

Maybe see how difficult that would be. If it's really a problem/time sink, we'll ask the researcher how much they really want this.

**Comment by laraPPr** [comment]
They also asked for miniprot and said thank you for miniprot and also this about EMMAX
```
If you would have the time to install the other software 'EMMAX' that I requested, it would be great. I have a large project to run and would like to take the opportunity of running those jobs in the summer as it is less crowded.
```

**Comment by boegel** [comment]
@pavelToman I'll pick it up from here, give it a quick try myself, and if it doesn't work out I'll let the researchers know we can't spend our time in getting dinosaur code like this to work...

**Comment by boegel** [comment]
Worth considering if EMMAX doesn't work out: https://github.com/slowkoni/EPI-EMMAX

**Comment by boegel** [comment]
Got it working with relatively minimal effort in the end: 
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21174

**Comment by boegel** [comment]
PR merged, software installed, ready for cleaning & closing...
