### ISSUE TITLE
EpiNano

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#38]
* link to support ticket: [Ticket#2022100660001781](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=95786)
* website: https://github.com/novoalab/EpiNano
* installation docs: https://github.com/novoalab/EpiNano/blob/master/README.md
  * see also https://github.com/novoalab/EpiNano/blob/master/dockerfile/Dockerfile
* toolchain: `foss/2022a` (?)
* easyblock to use: `Tarball` (+ `PythonPackage` for extensions)
* required dependencies:
  * see https://github.com/novoalab/EpiNano#pre-requisites
* notes:
  * ...
* effort: *(TBD)*

**Comment by laraPPr** [comment]
Asked the user if the installing SnapATAC2 is still relevant for them. Will reopen the ticket if the user reaches out that this is still relevant for their research.
