### ISSUE TITLE
HERRO

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#380]
* link to support ticket: [#2024080160000577](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=163306)
* website: https://github.com/lbcb-sci/herro
* installation docs: https://github.com/lbcb-sci/herro
* toolchain: `foss/2023a` Not specified
* easyblock to use: `CargoPythonPackage?`
* required dependencies:
  * [x] Python
  * [x] Zstandard
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21252

**Comment by boegel** [comment]
PR merged, software installed, cleanup done in fa07b7f
