### ISSUE TITLE
MATES

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#381]
* link to support ticket: [#2024080560000113](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=163420)
* website: https://github.com/mcgilldinglab/MATES
* installation docs: https://github.com/mcgilldinglab/MATES?tab=readme-ov-file#installation
* toolchain: `GCC/12.3.0?`
* easyblock to use: `PythonPackage?PythonBundle?`
* required dependencies:
  * [x] SAMtools/1.17-GCC-12.2.0 
  * [x] BEDTools/2.31.0-GCC-12.3.0 
  * [x] Python/3.11.3-GCCcore-12.3.0
* optional dependencies:
  * [ ] ...
* notes:
  * The user seemed to indicate that you might need python 3.9 but just try with 3.11 and see what happens the versions of SAMtools and BEDTools exactly match the requirements
  * I think the user want a version with and without GPU
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21229

**Comment by boegel** [comment]
PR merged, ready for cleanup
