### ISSUE TITLE
AGAT

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#382]
* link to support ticket: [#2024080660000693](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=163589)
* website: https://agat.readthedocs.io/en/latest/
* installation docs: https://github.com/NBISweden/AGAT?tab=readme-ov-file#installation
* toolchain: `GCC/12.3.0`
* easyblock to use: `Bundle`
* required dependencies:
  * [ ] Perl
  * [ ] BioPerl
* optional dependencies:
  * [ ] ...
* notes:
  * Will already install https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/a/AGAT/AGAT-1.1.0-GCC-12.2.0.eb because the user says that it is blocking their work
  * By the migration to Rhel9 we would however need a newer one
  * @PavelToman maybe you can add an extra list to the project for requests like these which are not necessary because people can still rely on older version but will need an update when moving to Rhel9? 
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21331

**Comment by boegel** [comment]
@PetrKralCZ PR merged, software installed, ready for cleanup
