### ISSUE TITLE
miniprot

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#383]
* link to support ticket: [#2024080760000155](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=163637)
* website: https://github.com/lh3/miniprot
* installation docs: https://github.com/lh3/miniprot
* toolchain: `GCC/12.3.0?`
* easyblock to use: `MakeCp?`
* required dependencies:
  * [ ] zlib
* optional dependencies:
  * [ ] ...
* notes:
  * Might be similar to this easyconfig is from the same github account and they look similar to some extend
  * https://github.com/easybuilders/easybuild-easyconfigs/blob/3815115d25a91fcb65789f838befb65988da5e81/easybuild/easyconfigs/b/BFC/BFC-1-foss-2018a.eb#L6
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21157
