### ISSUE TITLE
Salmon

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#384]
* link to support ticket: [#2024080860000457](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=163778)
* website: https://github.com/COMBINE-lab/salmon
* installation docs: https://combine-lab.github.io/salmon/getting_started/#obtaining-salmon
* toolchain: `GCC/12.3.0`
* easyblock to use: `CMakeMake`
* required dependencies:
  * [x]  Boost 
  * [x] tbb
  * [x] cURL
  * [x] libiconv
  * [x] bzip2
  * [x] XZ
  * [x] zlib
* optional dependencies:
  * [x] ...
* notes:
  * Needs to be compatible with Transrate/1.0.3-GCC-12.3.0
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21163
