### ISSUE TITLE
MultiQC

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#385]
* link to support ticket: [#2024080960000553](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=163869)
* website: https://multiqc.info/
* installation docs: https://github.com/MultiQC/MultiQC?tab=readme-ov-file#installation
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] Python
  * [ ] Python-bundle-PyPI
  * [ ] Kaleido
  * [ ] matplotlib
  * [ ] plotly.py
  * [ ] pydantic
  * [ ] tqdm
  * [ ] Pillow
  * [ ] PyYAML
  * [ ] networkx
  * [ ] 
* optional dependencies:
  * [ ] ...
* notes:
  * See: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/m/MultiQC/MultiQC-1.22.3-foss-2023b.eb
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by laraPPr** [comment]
The user wants it to be compatible with GCC-12.3.0 but the dependencies on that toolchain are to old:
```
multiqc 1.23 has requirement plotly>=5.18, but you have plotly 5.16.0.

multiqc 1.23 has requirement pydantic>=2.7.1, but you have pydantic 2.5.3.
```

- [pydantic-2.5.3-GCCcore-12.3.0.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/pydantic/pydantic-2.5.3-GCCcore-12.3.0.eb)
- [plotly.py-5.16.0-GCCcore-12.3.0.eb](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/plotly.py/plotly.py-5.16.0-GCCcore-12.3.0.eb)

**Comment by boegel** [comment]
@laraPPr Can you ask why they want it to be compatible with GCC/12.3.0?

That's probably because they want to combine it with other modules that are using that toolchain, we can look into updating those too

**Comment by laraPPr** [comment]
installing STAR and MultiQC on GCC-13.2.0 already have easyconfigs

**Comment by laraPPr** [comment]
installed and informed user
