### ISSUE TITLE
cf-array

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#387]
* link to support ticket: [#2024081260000761](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=164030)
* website: https://cf-xarray.readthedocs.io/en/latest/
* installation docs: https://cf-xarray.readthedocs.io/en/latest/
* toolchain: `?` same as #386 
* easyblock to use: `PythonPackage?`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * See #386 
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
Already in xESMF PR? Is it ok? 
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20985

**Comment by laraPPr** [comment]
Leave it open until is installed and the user informed because otherwise I'm gonna lose track of these

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup

This is maybe better I've added a column to keep track of the stuff that is not installed yet and where the user is not informed yet so go ahead and close @pavelToman

**Comment by laraPPr** [comment]
Is the same OTRS ticket as for #386. When creating the issue I did not notice that cf-array was a dependency so will close this one
