### ISSUE TITLE
Isoquant

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#388]
* link to support ticket: [#2024081460000954](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=164237)
* website: https://github.com/ablab/IsoQuant
* installation docs: https://ablab.github.io/IsoQuant/installation.html
* toolchain: `foss/2023a` or older
* easyblock to use: `Tarball`
* required dependencies:
  * [ ] Python
  * [ ] gffutils
  * [ ] Biopython
  * [ ] SciPy-bundle
  * [ ] pybedtools
  * [ ] Pysam
  * [ ] pyfaidx
  * [ ] minimap2
  * [ ] SAMtools
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21209

**Comment by boegel** [comment]
PR merged + installed, ready for cleanup
