### ISSUE TITLE
OpenFOAM 12

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#389]
* link to support ticket: [#2024081660000272](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=164326)
* website: https://www.openfoam.org/
* installation docs: https://openfoam.org/download/source/
* toolchain: `foss/2023b or foss/2023a`
* easyblock to use: `Custom OpenFoam`
* required dependencies:
  * [ ]  ncurses
  * [ ] METIS
  * [ ] SCOTCH
  * [ ] CGAL
  * [ ] ParaView
  * [ ] gnuplot
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21330

**Comment by boegel** [comment]
@PetrKralCZ This update will be relevant here:
* https://github.com/easybuilders/easybuild-easyblocks/pull/3434

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21324

@PetrKralCZ In the short term, we can definitely proceed with that to cover this installation request.
OpenFOAM is rarely (if ever) used as a dependency for something, so having multiple versions of it in a single toolchain generation is pretty OK.

Maybe continue your effort with `gnuplot` (5.x, or 6.x if you can make it work), but other than that no further effort is really required here, we don't ab-so-lutely need OpenFOAM 12 with `foss/2023b`, `foss/2023a` is good enough (also for RHEL9)

**Comment by boegel** [comment]
@PetrKralCZ As discussed, let's favor https://github.com/easybuilders/easybuild-easyconfigs/pull/20834 over your https://github.com/easybuilders/easybuild-easyconfigs/pull/21330

So close https://github.com/easybuilders/easybuild-easyconfigs/pull/21330, and then this issue can be closed too, since we already have OpenFOAM 12 installed with `foss/2023a`

**Comment by boegel** [comment]
@PetrKralCZ Ready for cleanup + closing
