### ISSUE TITLE
BayesOpt (C++)

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#391]
* link to support ticket: [#2024082160000637](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=165447)
* website: https://rmcantin.github.io/bayesopt/html/index.html
* installation docs: https://rmcantin.github.io/bayesopt/html/install.html
* toolchain: `foss/2023a` or older
* easyblock to use: `CMakeMake?`
* required dependencies:
  * [ ] libboost-dev 
  * [ ] python-dev 
  * [ ] python-numpy 
  * [ ] cmake 
  * [ ] cmake-curses-gui 
  * [ ] g++ 
  * [ ] cython 
  * [ ] octave 
  * [ ] liboctave-dev 
  * [ ] freeglut3-dev
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21261

**Comment by laraPPr** [comment]
Inbstalled and informed user
