### ISSUE TITLE
SecretomeP 2.0

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#393]
* link to support ticket: [#2024082160001118](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=165495)
* website: https://services.healthtech.dtu.dk/services/SecretomeP-2.0/
* installation docs: https://services.healthtech.dtu.dk/services/SecretomeP-2.0/
* toolchain: `GCC/12.3.0` or older
* easyblock to use: `?`
* required dependencies:
  * [ ] ProP
  * [ ] PSORT II
  * [ ] TMHMM
  * [ ] SignalP
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by laraPPr** [comment]
@pavelToman @PetrKralCZ This user is asking for an update so maybe one of you can look at this one next?

**Comment by laraPPr** [comment]
They also sent a tarball for psort

**Comment by pavelToman** [comment]
Could you or them also provide sources for this? Or where to get it?

**Comment by boegel** [comment]
@pavelToman The researcher wasn't able to find the sources for version `2.0`  either, but we can look into installing the available `1.0h` version

**Comment by pavelToman** [comment]
sources are there: /apps/gent/source/s/SecretomeP/secretomep-1.0h.Linux.tar.gz

**Comment by pavelToman** [comment]
There are a few problems with build/installation:
- I am unable to make a ProP works. There are mainly tcsh scripts that process fasta files and predicts arginine and lysine  propeptide cleavage sites. Either there are 2 binaries in /how and they do not work.
The `/how/how98_Linux_v2`: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
- There is a dependency `Seg` - seems as a old one and only place I can find sources is: https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/ncbi-seg/0.0.20000620-6/ but do not know if this one is suitable for SecretomeP

**Comment by laraPPr** [comment]
Pushed back to user. Closing for now.
