### ISSUE TITLE
SeqKit

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#394]
* link to support ticket: [#2024082260000171](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=165521)
* website: https://bioinf.shenwei.me/seqkit/
* installation docs: https://github.com/shenwei356/seqkit
* toolchain: `SYSTEM`
* easyblock to use: `GoPackage`
* required dependencies:
  * [ ] GO
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21253

**Comment by boegel** [comment]
PR merged, software installed, ready for cleanup
