### ISSUE TITLE
Cellformer

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#395]
* link to support ticket: [#2024082260001072](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=165611)
* website: https://github.com/elo-nsrb/Cellformer
* installation docs: https://github.com/elo-nsrb/Cellformer
* toolchain: `foss/2023a` or older
* easyblock to use: `PythonPackage? PythonBundle?`
* required dependencies:
  * [ ] Python 3
  * [ ] PyTorch (2.0.0)
  * [ ] ArchR (R version 4.2.2)
  * [ ] Scikit-learn (1.2.2)
  * [ ] Asteroid (0.5.2)
  * [ ] Pytorch-lightning (2.0.4)
  * [ ] comet_ml (3.32.8)
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21474

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21475

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21621

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup
