### ISSUE TITLE
NextDenovo

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#397]
* link to support ticket: [#2024082260001091](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=165613)
* website: https://github.com/Nextomics/NextDenovo
* installation docs: https://github.com/Nextomics/NextDenovo
* toolchain: `GCC/12.3.0?`
* easyblock to use: `Tarball`
* required dependencies:
  * [x] Python
  * [x] [Paralleltask](https://github.com/moold/ParallelTask)
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21264

**Comment by boegel** [comment]
To fix the problem with HTSlib, we should add it as a dependency and make it is used, probably with something like `HTSDIR=$EBROOTHTSLIB` in `buildopts`, see also https://github.com/Nextomics/NextDenovo/blob/master/lib/Makefile#L4

**Comment by pavelToman** [comment]
It uses either minimap2 but modified one - https://nextdenovo.readthedocs.io/en/latest/UTILITY.html#minimap2-nd

**Comment by pavelToman** [comment]
I was unable to replace htslib by one from EB. 
I've tried even to build and use HTSlib-1.9 as they use this version. 
Most recent log is https://github.com/vscentrum/vsc-software-stack/blob/wip/397_NextDenovo/log5.txt 
There are a lot of `undefined reference to` for `bsort.c` during `gcc -Wall -O3 -Wno-unused-function  -o bam_sort bam_sort.c ../lib/bsort.c -I ../lib/htslib/  -lpthread -lcurl -lm -lz -lcrypto`
The finall WIP is there: https://github.com/vscentrum/vsc-software-stack/blob/wip/397_NextDenovo/nextdenovo_HTS_test_2.eb
another one there: https://github.com/vscentrum/vsc-software-stack/blob/wip/397_NextDenovo/nextdenovo_HTS_test.eb

**Comment by boegel** [comment]
@pavelToman The `undefined reference` errors hint towards not linking to XZ + bzip2, that's probably what you should try and fix.

Maybe also ask upstream whether linking with your own HTSlib library makes sense/is supported

**Comment by boegel** [comment]
@pavelToman PR merged, software installed, ready for cleanup
