### ISSUE TITLE
NECAT

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#399]
* link to support ticket: [#2024082260001143](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=165618)
* website: https://github.com/xiaochuanle/NECAT
* installation docs: https://github.com/xiaochuanle/NECAT
* toolchain: `foss/2023a` or older
* easyblock to use: `Tarball?`
* required dependencies:
  * [ ] BRAKER
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
@PetrKralCZ BRAKER is not a dependency, but the researcher wants to use it together with NECAT, so can you look into an update of BRAKER too?

**Comment by boegel** [comment]
Actually, let us check with the researcher first if/how they need BRAKER along with this...

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21359

**Comment by boegel** [comment]
PR merged, software installed, ready for cleanup

**Comment by boegel** [comment]
@PetrKralCZ No reply yet from researcher if/how they want to combine NECAT with BRAKER.

If we get an answer, I'll either re-open this issue, or (probably) open a new issue for an update of BRAKER.

**Comment by boegel** [comment]
Follow-up for BRAKER via #410
