### ISSUE TITLE
insight (CRAN-package)

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#401]
* link to support ticket: [#2024082560000102](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=165770)
* website: https://cran.r-project.org/web/packages/insight/index.html
* installation docs: https://cran.r-project.org/web/packages/insight/index.html
* toolchain: `foss/2023a` and `foss2023b`?
* easyblock to use: `bundle`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * Just add to the R-bundle-CRAN-2023.12-foss-2023a.eb
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21260

**Comment by laraPPr** [comment]
installed and informed user

**Comment by boegel** [comment]
see also:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21272
(extra optional packages required by `insight`)
