### ISSUE TITLE
pyseer

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#402]
* link to support ticket: [#2024082760000948](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=165993)
* website: https://github.com/mgalardini/pyseer
* installation docs: https://github.com/mgalardini/pyseer
* toolchain: `foss/2023a` or older
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] Python
  * [ ] SciPy-bundle
  * [ ] pybedtools
  * [ ] statsmodels
  * [ ] scikit-learn
  * [ ] Pysam
  * [ ] DendroPy
  * [ ] matplotlib
  * [ ] tqdm
* optional dependencies:
  * [ ] ...
* notes:
  * https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/pyseer/pyseer-1.3.11-foss-2022b.eb
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21306

**Comment by boegel** [comment]
PR merged, ready for cleanup
