### ISSUE TITLE
Bayesian-optimization

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#406]
* link to support ticket: [#2024082960001391](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=166291)
* website: https://bayesian-optimization.github.io/BayesianOptimization/index.html
* installation docs: https://bayesian-optimization.github.io/BayesianOptimization/quickstart.html#installation
* toolchain: `2023a` or older
* easyblock to use: `Pythonpackage?`
* required dependencies:
  * [ ] Python
* optional dependencies:
  * [ ] ...
* notes:
  * Could not find a requirements page
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21301

**Comment by boegel** [comment]
@PetrKralCZ PR merged, software installed, ready for cleanup
