### ISSUE TITLE
scTIE

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#408]
* link to support ticket: [#2024090360000188](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=166694)
* website: https://github.com/SydneyBioX/scTIE
* installation docs: https://github.com/SydneyBioX/scTIE?tab=readme-ov-file#installation
* toolchain: `foss/2023a` (must be compatible with `Single-cell-python-bundle/2024.02-foss-2023a`)
* easyblock to use: `Tarball`
* required dependencies:
  * `PyTorch` & more, see https://github.com/SydneyBioX/scTIE?tab=readme-ov-file#installation
* notes:
  * also make a CUDA variant
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64):no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21360

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21693

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21694

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup...
