### ISSUE TITLE
CIRCE

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#409]
* link to support ticket: [#2024090360000277](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=166703)
* website: https://github.com/cantinilab/Circe
* installation docs: https://github.com/cantinilab/Circe?tab=readme-ov-file#installation
* toolchain: `PythonBundle`
* easyblock to use: `foss/2023a`
* required dependencies:
  * see https://github.com/cantinilab/Circe/blob/main/pyproject.toml
* notes:
  * should be compatible with `Single-cell-python-bundle/2024.02-foss-2023a`, `CellOracle/0.18.0-foss-2023a`, `PyTorch/2.1.2-foss-2023a`, `CellRank/2.0.2-foss-2023a`
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21702

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21703

**Comment by laraPPr** [comment]
installing now

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
