### ISSUE TITLE
BRAKER 3.x

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#410]
* link to support ticket: [#2024091260000751](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=167788)
* website: https://github.com/Gaius-Augustus/BRAKER
* installation docs: https://github.com/Gaius-Augustus/BRAKER?tab=readme-ov-file#installation
* toolchain: `foss/2023a` (should be compatible with `NECAT` (cfr. #399)
* easyblock to use: `Tarball`
* required dependencies:
  * see https://github.com/Gaius-Augustus/BRAKER?tab=readme-ov-file#installation
* notes:
  * `BRAKER-2.1.6-foss-2022a.eb` is hopefully a good starting point
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21476

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21498

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21529

**Comment by PetrKralCZ** [comment]
It's a draft because on `donphan` it takes forever to build, so I want to try it on `generoso` / `jsc-zen3`.
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21541

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21701

**Comment by boegel** [comment]
PR merged, software installed, ready for cleanup...
