### ISSUE TITLE
decona

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#411]
* link to support ticket: [#2024091260000358](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=167748)
* website: https://github.com/Saskia-Oosterbroek/decona
* installation docs: https://github.com/Saskia-Oosterbroek/decona?tab=readme-ov-file#installation
* toolchain: `foss/2023b` (or at least `foss/2023a`)
* easyblock to use: `Binary`? *(see existing easyconfig)*
* required dependencies:
  * https://github.com/Saskia-Oosterbroek/decona?tab=readme-ov-file#dependencies
* notes:
  * update of `decona-0.1.2-foss-2019b-Python-3.7.4.eb`
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21449

**Comment by boegel** [comment]
PR merged, software installed, ready for cleanup

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21445
