### ISSUE TITLE
SDSL-lite

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#412]
* link to support ticket: [#2024091160000798](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=167661)
* website: https://github.com/simongog/sdsl-lite
* installation docs: https://github.com/simongog/sdsl-lit
* toolchain: `GCCcore-12.3.0` or newer
* easyblock to use: `CMakeMake`
* required dependencies:
  * [ ] 
* optional dependencies:
  * [ ] ...
* notes:
  * https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/SDSL/SDSL-2.1.1-20191211-GCCcore-8.3.0.eb#L36
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21848

**Comment by boegel** [comment]
@PetrKralCZ PR merged, software installed, ready for cleanup

Can you make an estimate of how much time (# hours) this took request you?

**Comment by PetrKralCZ** [comment]
It took about 4 hours
