### ISSUE TITLE
RepeatMasker

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#413]
* link to support ticket: [#2024091360000212](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=167855)
* website: https://www.repeatmasker.org/
* installation docs: https://github.com/Dfam-consortium/RepeatMasker
* toolchain: `foss/2023a` or newer
* easyblock to use: `Tarball`
* required dependencies:
  * [ ]  Python
  * [ ] Perl
  * [ ] TRF
  * [ ] h5py
  * [ ] HMMER
  * [ ] RMBlast
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21420

**Comment by boegel** [comment]
PR merged, software installed, ready for cleanup...
