### ISSUE TITLE
modkit

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#415]
* link to support ticket: [#2024091660000681](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=168108)
* website: https://github.com/nanoporetech/modkit
* installation docs: https://github.com/nanoporetech/modkit?tab=readme-ov-file#installation
* toolchain: `foss/2023a`
* easyblock to use: `Cargo?`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR for GCCcore/12.3.0:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21725

**Comment by pavelToman** [comment]
PR for GCCcore/13.3.0:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21727

**Comment by laraPPr** [comment]
Started installing it centrally and some are failing

On gallade:
- 21725
- 21727
On doduo
- 21727

The error:
```
ERROR: Build of /tmp/eb-xmcnqiml/files_pr21727/m/modkit/modkit-0.4.1-GCCcore-13.3.0.eb failed (err: 'build failed (first 300 chars): cmd " cargo test --profile=release " exited with exit code 101 and output:
warning: unused variable: `patterns`
    --> src/entropy/methylation_entropy.rs:305:13
    |
305 |         let patterns = all_patterns_dp(&sequences, 4, &alphabet_info);
    |             ^^^^^^^^ help: if this is intentional,')
```

But it is also a little flaky because it failed on shinx and than it passed

**Comment by laraPPr** [comment]
I installed it with less resources in the allocation and it is now installed everywhere

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
