### ISSUE TITLE
Remora

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#416]
* link to support ticket: [#2024091660000691](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=168109)
* website: https://github.com/nanoporetech/remora
* installation docs: https://github.com/nanoporetech/remora?tab=readme-ov-file#installation
* toolchain: `foss/2023a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] Python
  * [ ] SciPy-bundle
  * [ ] ONNX-Runtime
  * [ ] PyTorch
  * [ ] scikit-learn
  * [ ] tqdm
* optional dependencies:
  * [ ] ...
* notes:
  * This not the same as [REMORA](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/REMORA/REMORA-1.8.3-gompi-2019a.eb)
  * This is [ont-remora](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/o/ont-remora/ont-remora-1.0.0-foss-2021a.eb)
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21478
