### ISSUE TITLE
awscli

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#417]
* link to support ticket: [#2024091660001608](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=168200)
* website: https://aws.amazon.com/cli/
* installation docs: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html#cliv2-linux-install
* toolchain: `GCCcore-13.2.0`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] Python
  * [ ] PyYAML
  * [ ] ruamel.yaml
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21451

**Comment by laraPPr** [comment]
installed + ready for clean-up
