### ISSUE TITLE
MCR 2022b (9.13) AND 2023b

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#418]
* link to support ticket: [#2024091760001731](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=168414)
* website: https://www.mathworks.com/products/compiler/mcr/
* installation docs: https://www.mathworks.com/products/compiler/mcr/
* toolchain: `SYSTEM`
* easyblock to use: `MCR`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21454

**Comment by boegel** [comment]
PR merged, software installed, ready for cleanup
