### ISSUE TITLE
HTSplotter

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#419]
* link to support ticket: [#2024091860000865](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=168503)
* website: https://github.com/CBIGR/HTSplotter
* installation docs: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/h/HTSplotter/HTSplotter-2.11-foss-2022b.eb
* toolchain: `foss/2023a` or older
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] Python
  * [ ] SciPy-bundle
  * [ ] matplotlib
  * [ ] h5py
  * [ ] Seaborn
  * [ ] tqdm
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21479
