### ISSUE TITLE
PySCF

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#422]
* link to support ticket: [#2024092360002264](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=169249;ArticleID=590275)
* website: http://www.pyscf.org
* installation docs: https://github.com/easybuilders/easybuild-easyconfigs/blob/b96680b84ab4f4b64e8f5ac798f4d0e13a511d6a/easybuild/easyconfigs/p/PySCF/PySCF-2.4.0-foss-2022b.eb
* toolchain: `foss/2023a` or newer
* easyblock to use: `CMakeMakeCp`
* required dependencies:
  * [ ] Python
  * [ ] SciPy-bundle
  * [ ] h5py
  * [ ] libcint
  * [ ] libxc
  * [ ] XCFun
  * [ ] CPPE
  * [ ] PyBerny
  * [ ] PyCheMPS2
  * [ ] Block
  * [ ] NECI
  * [ ] Dice
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21522

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21523

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21524

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21525

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21553

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21616

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21647

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21750

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
