### ISSUE TITLE
AMRFinderPlus

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#427]
* link to support ticket: [#2024100160003042](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=170891)
* website: https://github.com/ncbi/amr
* installation docs: https://github.com/ncbi/amr/wiki/Installing-AMRFinder
* toolchain: `gompi/2023a`
* easyblock to use: `MakeCp`
* required dependencies:
  * [ ] BLAST
  * [ ] HMMER
  * [ ] cURL
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21551

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
