### ISSUE TITLE
ABRicate

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#428]
* link to support ticket: [#2024100160003061](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=170893)
* website: https://github.com/tseemann/abricate
* installation docs: https://github.com/tseemann/abricate?tab=readme-ov-file#installation
* toolchain: `gompi/2023a`
* easyblock to use: `Tarball`
* required dependencies:
  * [ ] Perl
  * [ ] any2fasta
  * [ ] BioPerl
  * [ ] BLAST+
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21554

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
