### ISSUE TITLE
BindCraft

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#429]
* link to support ticket: [#2024100360001844](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=171333) + [#2024103060000473](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=174449)
* website: https://github.com/martinpacesa/BindCraft
* installation docs: https://github.com/martinpacesa/BindCraft?tab=readme-ov-file#installation
* toolchain: `Conda?` or `PythonPackage`
* easyblock to use: `foss/2023a`
* required dependencies:
  * [ ] pandas
  * [ ] numpy
  * [ ] biopython
  * [ ] scipy
  * [ ] pdbfixer
  * [ ] seaborn
  * [ ] tqdm
  * [ ] jupyter
  * [ ] ffmpeg
* optional dependencies:
  * [ ] ...
* notes:
  * The installation only mentions `conda` as a package manager but maybe the [installscript](https://github.com/martinpacesa/BindCraft/blob/8eb051da806fec5ccc280a0d28bbe9e5056c25c4/install_bindcraft.sh) also works with `pip`
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21791

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup

**Comment by laraPPr** [comment]
I overlooked this but the user wanted GPU support. So I'm reopening this one.

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21958

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/22039

**Comment by boegel** [comment]
@PetrKralCZ PR merged, software installed, ready for cleanup

Can you make an estimate of how much time (# hours) this took request you?
