### ISSUE TITLE
chemprop

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#43]
* link to support ticket: [#2022101260000153](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=96492)
* website: https://github.com/chemprop/chemprop
* installation docs: https://github.com/chemprop/chemprop#installation
* toolchain: `foss/2021b`
* easyblock to use: `PythonBundle`?
* required dependencies:
  * [x] Python
  * [x] RDKit (see `RDKit-2022.03.5-foss-2021b.eb`)
  * [ ] descriptastorus (https://github.com/bp-kelley/descriptastorus)
    * [ ] kyotocabinet (https://dbmx.net/kyotocabinet)
  * + additional Python packages incl. PyTorch (`torch`), `numpy`/`scipy`/`pandas` (cfr. `SciPy-bundle`), etc., see https://github.com/chemprop/chemprop/blob/master/setup.py#L39
* notes:
  * ...
* effort: *(TBD)*

**Comment by ItIsI-Orient** [comment]
Since this needs PyTorch, shouldn't I be using `foss/2021a` as a toolchain? Or is [this repo](https://github.com/easybuilders/easybuild-easyconfigs/pull/16286) going to get merged?

**Comment by boegel** [comment]
@ItIsI-Orient Yes, for now either use PyTorch 1.10.0 (with `foss/2021a`) or PyTorch 1.12.0 (with `foss/2022a`)

**Comment by ItIsI-Orient** [comment]
@boegel PR open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17261

**Comment by ItIsI-Orient** [comment]
@boegel opened PR for CUDA version:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17282

**Comment by boegel** [comment]
both PRs merged, ready for cleanup
