### ISSUE TITLE
CRAN packages: Goldilocks and gsDesign

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#430]
* link to support ticket: [#2024100460001226](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=171475)
* website: https://cran.r-project.org/package=goldilocks and https://cran.r-project.org/web/packages/gsDesign/index.html
* installation docs: add to R-bundle-CRAN
* toolchain: `foss/2023a` or newer
* easyblock to use: `Bundle`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21583

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup. @Kenneth will you inform the user or shall I steel the ticket?

**Comment by laraPPr** [comment]
Informed user
