### ISSUE TITLE
Stellarscope

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#432]
* link to support ticket: [#2024100760001784](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=171756)
* website: https://github.com/nixonlab/stellarscope
* installation docs: https://github.com/nixonlab/stellarscope/blob/main/docs/protocol.md
* toolchain: `foss/2023a` or newer
* easyblock to use: `PythonPackage?`
* required dependencies:
  * [ ] Python
  * [ ] future
  * [ ] pip
  * [ ] packaging
  * [ ] pyyaml
  * [ ] cython
  * [ ] numpy
  * [ ] scipy
  * [ ] pysam
  * [ ] htslib
  * [ ] intervaltree
  * [ ] pandas
  * [ ] samtools
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR
https://github.com/easybuilders/easybuild-easyconfigs/pull/21602

**Comment by boegel** [comment]
@pavelToman PR merged, software installed, ready for cleanup
