### ISSUE TITLE
cisDiversity

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#435]
* link to support ticket: [#2024100960000334](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=172055)
* website: https://github.com/NarlikarLab/cisDIVERSITY
* installation docs: https://github.com/NarlikarLab/cisDIVERSITY
* toolchain: `?`
* easyblock to use: `Make?`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
Do they really need it? Seems like old one:
```
The following packages need to be installed in order to view the output of cisDIVERSITY:
 * Python 2.7+ (Not compatible with Python 3.x)
 * python-numpy
 * python-ctypes
 * python-re
 * R > 3.0
 * R package corrplot
```

**Comment by pavelToman** [comment]
PR:
- https://github.com/vscentrum/vsc-software-stack/issues/435

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21692

**Comment by laraPPr** [comment]
installing now

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
