### ISSUE TITLE
PyBioLib

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#436]
* link to support ticket: [#2024101160000268](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=172381)
* website: https://biolib.com/
* installation docs: https://pypi.org/project/pybiolib/
* toolchain: `GCC-12.3.0`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] Python
  * [ ] Flask
  * [ ] PyYAML
* optional dependencies:
  * [ ] ...
* notes:
  * The user needs the DeepTMHMM model you can find the comandos for testing it here https://dtu.biolib.com/DeepTMHMM
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21716

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
