### ISSUE TITLE
BEDOPS

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#438]
* link to support ticket: [#2024101460001529](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=172706)
* website: http://%(namelower)s.readthedocs.io/en/latest/index.html
* installation docs: https://bedops.readthedocs.io/en/latest/content/installation.html#linux
* toolchain: `foss/2023a` or newer
* easyblock to use: `MakeCp`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21810

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup...
