### ISSUE TITLE
MEME

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#441]
* link to support ticket: [#2024101560001429](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=172926)
* website: https://meme-suite.org/meme/index.html
* installation docs: ...
* toolchain: `gompi/2023a` or newer
* easyblock to use: `ConfigureMake`
* required dependencies:
  * [ ] libxml2
  * [ ] libxslt
  * [ ] zlib
  * [ ] Perl
  * [ ] Python
  * [ ] Ghostscript
  * [ ] XML-Compile
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment]
I have easyconfigs for this already, but haven't created the PR yet

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21744

**Comment by laraPPr** [comment]
installing now

**Comment by laraPPr** [comment]
installed and informed user
