### ISSUE TITLE
Mustache

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#442]
* link to support ticket: [#2024101660000151](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=172995)
* website: https://github.com/ay-lab/mustache
* installation docs: https://github.com/ay-lab/mustache
* toolchain: `foss/2023a` or newer
* easyblock to use: `PythonPackage?`
* required dependencies:
  * [x] h5py
  * [x] hdf5
  * [x] numpy
  * [x] python=3.8
  * [x]  cooler
  * [x] hic-straw
  * [x] pandas
  * [x] scipy
  * [x] statsmodels
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21783
