### ISSUE TITLE
OPERA-MS

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#443]
* link to support ticket: [#2024101660000722](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=173052)
* website: https://github.com/CSB5/OPERA-MS
* installation docs: 
* toolchain: `foss/2023a`
* easyblock to use: `MakeCp`
* required dependencies:
  * [ ] Perl
  * [ ] Perl-bundle-CPAN?
  * [ ] Statistics-R
  * [ ] Python
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by laraPPr** [comment]
This might not be neccessary. I did not see that they requested to install the already exhisting easyconfig on Hortense. So doing that now. I will however warn them that software is also gonna dissapear.

**Comment by boegel** [comment]
We should definitely also look into updating `OPERA-MS-0.9.0-20200802-foss-2020a-Python-3.8.2.eb`, so we can keep it alive on RHEL9

**Comment by laraPPr** [comment]
Closed the ORTRS ticket because requested software is on Hortense. But Kenneth is right we should keep it open to make sure OPERA-MS is still available after the OS is upgraded. So add the request to RHEL9 requests.

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21770

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
