### ISSUE TITLE
Trinotate

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#444]
* link to support ticket: [#2024102360000352](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=173761)
* website: https://github.com/Trinotate/Trinotate/wiki
* installation docs: 
* toolchain: `foss/2023a`
* easyblock to use: `Tarball`
* required dependencies:
  * [ ]  Perl
  * [ ] Python
  * [ ] Trinity
  * [ ] BLAST+
  * [ ] DIAMOND
  * [ ] eggnog-mapper
  * [ ] HMMER
  * [ ] Infernal
  * [ ] PyBioLib
  * [ ] SAMtools
  * [ ] TransDecoder
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21749

**Comment by boegel** [comment]
@pavelToman PR merged, ready for cleanup
