### ISSUE TITLE
FDS

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#445]
* link to support ticket: [#2024101860000639](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=173312)
* website: https://pages.nist.gov/fds-smv
* installation docs: https://pages.nist.gov/fds-smv/manuals.html
* toolchain: `intel/2023a` or newer only skitty and donphan?
* easyblock to use: `ConfigureMake`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21768

**Comment by boegel** [comment]
@pavelToman PR merged, software installed, ready for cleanup...

**Comment by boegel** [comment]
@pavelToman See also #351 (for SMV)
