### ISSUE TITLE
iodata

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#446]
* link to support ticket: [#2024102160001355](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=173558;ArticleID=606290)
* website: https://github.com/theochem/iodata
* installation docs: https://iodata.qcdevs.org/install.html
* toolchain: `foss/2023a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] Python
  * [ ] SciPy-bundle
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21811

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup...
