### ISSUE TITLE
stacks

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#448]
* link to support ticket: [#2024102560000171](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=174035)
* website: https://catchenlab.life.illinois.edu/stacks/
* installation docs: https://catchenlab.life.illinois.edu/stacks/manual/#install
* toolchain: `foss/2023a`
* easyblock to use: `ConfigureMake`
* required dependencies:
  * [ ] zlib
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21781

**Comment by laraPPr** [comment]
installing now

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
