### ISSUE TITLE
mosdepth

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#449]
* link to support ticket: [#2024102560000509](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=174068)
* website: https://github.com/brentp/mosdepth
* installation docs: https://github.com/brentp/mosdepth
* toolchain: `GCC/12.3.0` or newer
* easyblock to use: `Binary`
* required dependencies:
  * [ ] Nim
  * [ ] HTSlib
  * [ ] PCRE
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21782

**Comment by laraPPr** [comment]
installing now

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
