### ISSUE TITLE
IJulia

### ISSUE THREAD

**Issue by lexming** [vscentrum/vsc-software-stack#45]
* link to support ticket: ad#14600 (VUB)
* website: https://github.com/JuliaLang/IJulia.jl
* installation docs: https://github.com/JuliaLang/IJulia.jl
* toolchain: SYSTEM
* easyblock to use: needs new easyblock
* required dependencies:
  * [x] Julia
* notes:
  * [ ] easyblock JuliaPackage
* effort: hard because there is no easyblock for Julia packages

**Comment by boegel** [comment]
@lexming You mentioned that you have a WIP easyblock for installing Julia packages (as extensions?).

Can you share that by creating a `45_IJulia` subdirectory in this repo, and pushing what you have in there?

Would be useful for us too, for `CIRCUITSPACE` (cfr. #29) and [MultilevelEstimators](https://github.com/PieterjanRobbe/MultilevelEstimators.jl)

cc @ItIsI-Orient

**Comment by lexming** [comment]
@boegel I put in [45_IJulia](https://github.com/vscentrum/vsc-software-stack/tree/main/45_IJulia) the easyblock for `JuliaPackage` and current easyconfigs for IJulia as examples.
* [IJulia-1.23.3-Julia-1.6.3.eb](https://github.com/vscentrum/vsc-software-stack/blob/main/45_IJulia/IJulia-1.23.3-Julia-1.6.3.eb) is the standard solution where all packages are installed as extensions in a `Bundle`
* [IJulia-1.23.3-Julia-1.6.3-git.eb](https://github.com/vscentrum/vsc-software-stack/blob/main/45_IJulia/IJulia-1.23.3-Julia-1.6.3-git.eb) is an example of directly using sources from git and also lets Julia download missing dependencies (opt-in with `bundle_deps`).

**Comment by lexming** [comment]
PRs:
* easyblock: https://github.com/easybuilders/easybuild-easyblocks/pull/2816
* easyconfig: https://github.com/easybuilders/easybuild-easyconfigs/pull/16494

**Comment by boegel** [comment]
PRs merged, ready for cleanup (remove `[45_IJulia](https://github.com/vscentrum/vsc-software-stack/tree/main/45_IJulia)`) + close
