### ISSUE TITLE
VEP

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#450]
* link to support ticket: [#2024102560000545](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=174072)
* website: https://www.ensembl.org/info/docs/tools/vep
* installation docs: https://github.com/Ensembl/ensembl-vep
* toolchain: `GCC/12.3.0` or newer
* easyblock to use: `VEP`
* required dependencies:
  * [ ] Perl
  * [ ] Perl-bundle-CPAN?
  * [ ] Archive-Zip
  * [ ] DBD-mysql
  * [ ] BioPerl
  * [ ] Bio-DB-HTS
  * [ ] # VEP requires Compress::Raw::Zlib >= 2.103?
  * [ ] Compress-Raw-Zlib
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21801

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup...
