### ISSUE TITLE
trusTEr

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#453]
* link to support ticket: [#2024101060000564](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=172230)
* website: https://github.com/raquelgarza/truster
* installation docs: https://github.com/raquelgarza/truster?tab=readme-ov-file#how-to-install
* toolchain: `GCC/12.3.0` / `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/raquelgarza/truster?tab=readme-ov-file#requirements
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21855

**Comment by pavelToman** [comment]
@laraPPr could you install it and inform the user , please? Could I close this?

**Comment by laraPPr** [comment]
PR merged, software installed, ready for cleanup
