### ISSUE TITLE
Spectre

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#456]
* link to support ticket: [#2024111260000344](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=175943)
* website: https://github.com/fritzsedlazeck/Spectre
* installation docs: https://github.com/fritzsedlazeck/Spectre?tab=readme-ov-file#install-spectre
* toolchain: `foss/2023a` (or newer)
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/fritzsedlazeck/Spectre/blob/main/requirements.txt
* notes:
  * should be compatible with existing modules for `Sniffles` and `mosdepth`
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21881

**Comment by boegel** [comment]
@pavelToman PR merged, software installed, ready for cleanup & close
