### ISSUE TITLE
Nextflow 24.10.0

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#457]
* link to support ticket: [#2024111260000399](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=175948) [#2024112760001084](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=177679;ArticleID=621396)
* website: https://nextflow.io
* installation docs: https://nextflow.io/docs/latest/install.html
* toolchain: `system`
* easyblock to use: *(see existing easyconfigs)*
* required dependencies:
  * *(see existing easyconfigs)*
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21939

**Comment by laraPPr** [comment]
not installed yet on the cluster

**Comment by laraPPr** [comment]
installed
