### ISSUE TITLE
MFIX

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#461]
* link to support ticket: [#2024111560000704](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=176394) + [#2024120360000716](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=178206)
* website: https://mfix.netl.doe.gov/products/mfix/
* installation docs: https://mfix.netl.doe.gov/doc/mfix/24.3/html/getting_started/install-linux.html
* toolchain: `foss/2023a?`
* easyblock to use: `cmake?conda?`
* required dependencies:
  * [ ] miniforge3
  * [ ] 
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
Do you have source files? Seems it is provided only after registration: https://mfix.netl.doe.gov/products/mfix/download

**Comment by laraPPr** [comment]
Yes the user did something very stupid and gave us his login info. I haven't had time to download them yet.

**Comment by boegel** [comment]
The "source file" for MFIX is apparently a `.txt` file that includes two lines:

* a `conda create` command
* a line saying that you should run the `conda create` command on the line above

I wish I was kidding...

**Comment by boegel** [comment]
We can't install this centrally, I've suggested to the researcher to take care of this themselves in their account, so closing...
