### ISSUE TITLE
dorado

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#468]
* link to support ticket: [#2024112660001568](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=177542)
* website: https://github.com/nanoporetech/dorado
* installation docs: https://dorado-docs.readthedocs.io/en/latest/#installation
* toolchain: ~~`foss/2023b`~~ `foss/2023a`
* easyblock to use: `CMakeMake`
* required dependencies:
  * [ ] https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/d/dorado/dorado-0.8.0-foss-2023a-CUDA-12.1.1.eb
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
There is still no PyTorch-CUDA for foss/2023b, so I will stick to foss/2023a.

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21996

**Comment by boegel** [comment]
@pavelToman PR merged, ready for cleanup
