### ISSUE TITLE
MCU

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#47]
* link to support ticket: [#2022110360000436](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=99290)
* website: https://hungqpham.com/mcu - https://github.com/hungpham2017/mcu
* installation docs: https://hungqpham.com/mcu/install.html
* toolchain: `gomkl/2021a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * see https://hungqpham.com/mcu/install.html#prerequisites
    * use `SciPy-bundle` for `numpy`/`scipy`
* notes:
  * ...
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16566

**Comment by boegel** [comment]
PR merged, ready for cleanup...
