### ISSUE TITLE
frbs add to CRAN

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#471]
* link to support ticket: [#2024120360001135](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=178248)
* website: https://cran.r-project.org/web/packages/frbs/index.html
* installation docs: ...
* toolchain: `foss/2023a` and 'foss/2023b'
* easyblock to use: `Bundle`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21993

**Comment by boegel** [comment]
@pavelToman PR merged, software installed, ready for cleanup

Can you make an estimate of how much time (# hours) this took request you?

**Comment by pavelToman** [comment]
Prepare ECs: 1h
Testing/building: 1h
Solve requested changes in PR + testing: 1h
So about 3h, but I let it run during the night since build takes a lot of time.

I was adding either a `gcmr` for https://github.com/vscentrum/vsc-software-stack/issues/467 and test it either.
