### ISSUE TITLE
bamFilters

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#48]
* link to support ticket: [#2022110360000589](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=99305)
* website: https://github.com/institut-de-genomique/bamFilters
* installation docs: -
* toolchain: `GCC/11.3.0`
* easyblock to use: `MakeCp`
* required dependencies:
  * [x] HTSlib
  * [x] BamTools
  * [x] zlib
  * [x] bzip2
* notes:
  * ...
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/16735

**Comment by PetrKralCZ** [comment]
I had to make an easyconfig for an older version of `SAMtools` because since the `1.14` version it does not contain the `libbam.a` file.

**Comment by boegel** [comment]
Hmm, it seems like `bamFilters` requires the legacy API of SAMtools, which was indeed removed in SAMtools 1.14, see https://github.com/samtools/samtools/blob/410d910e9846b1884706facf2212a194a7492de1/NEWS#L237-L251

Using SAMtools 1.13 as dependency when using a recent toolchain like `GCC/11.3.0` is something we should try and avoid though.

Can you check if making SAMtools 1.13 a *build* dependency is sufficient?
It seems like it could, since `bamFilters` is statically linking in `libbam.a`?

If that works out, please change the PR accordingly, and add a comment for `builddependencies` to explain why an old version of SAMtools is being used.

**Comment by boegel** [comment]
@PetrKralCZ https://github.com/easybuilders/easybuild-easyconfigs/pull/16735 merged, ready for cleanup
