### ISSUE TITLE
DensPart

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#50]
* link to support ticket: [#2022111460001101](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=100680)
* website: https://github.com/theochem/denspart
* installation docs: https://github.com/theochem/denspart#minimal-setup
* toolchain: `intel/2021b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] numpy (see `SciPy-bundle`)
  * [x] GRID (https://github.com/theochem/grid)
* notes:
  * no release yet, so use datestamp of latest commit as poor man's version
* effort: *(TBD)*

**Comment by boegel** [comment]
GRID depends on `sympy`, see #79

**Comment by boegel** [comment]
@ItIsI-Orient `sympy/1.11.1-intel-2022a` is installed (see also https://github.com/easybuilders/easybuild-easyconfigs/pull/17442), so you should be able to proceed with GRID + DensPart...

**Comment by ItIsI-Orient** [comment]
PR Open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17473

**Comment by boegel** [comment]
PR merged + `DensPart` installed, ready for cleanup
