### ISSUE TITLE
QuPath

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#51]
* link to support ticket: [#2022111760000704](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=101165) + [#2023010460001058](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=105572)
* website: https://qupath.github.io
* installation docs: https://qupath.readthedocs.io/en/stable/docs/intro/installation.html#linux + https://qupath.readthedocs.io/en/latest/docs/reference/building.html
* toolchain: `SYSTEM` (?)
* easyblock to use: `Binary` (?)
* required dependencies:
  * There's a mention of `OpenSlide` as (optional?) dependency
* notes:
  * ...
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19962

**Comment by boegel** [comment]
PR merged, ready for cleanup
