### ISSUE TITLE
DIA-NN

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#53]
* link to support ticket: [#2022111760001614](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=101256)
* website: https://github.com/vdemichev/DiaNN
* installation docs: https://github.com/vdemichev/DiaNN#installation
* toolchain: `SYSTEM`
* easyblock to use: `Rpm` ?
* required dependencies:
  * -
* notes:
  * seems like only a pre-built binary is available, see https://github.com/vdemichev/DiaNN/issues/465
* effort: *(TBD)*

**Comment by boegel** [comment]
seemingly working easyconfig available at [53_DIA-DN/DIA-NN.eb](https://github.com/vscentrum/vsc-software-stack/blob/main/53_DIA-DN/DIA-NN.eb), will ask researcher to verify first that it's working as expected...

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/16706

**Comment by laraPPr** [comment]
Software was installed and ticket was closed
