### ISSUE TITLE
vaeda

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#57]
* link to support ticket: [#2022112360000569](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=101925)
* website: https://github.com/kostkalab/vaeda
* installation docs: https://github.com/kostkalab/vaeda#installation
* toolchain: `foss/2021b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/kostkalab/vaeda/blob/main/setup.py#L18
* notes:
  * ...
* effort: *(TBD)*

**Comment by boegel** [comment]
working easyconfigs added to [`57_vaeda`](https://github.com/vscentrum/vsc-software-stack/tree/main/57_vaeda), but need to check for compatibility with `scrublet` (#58), `infercnvpy` (#59), `solo` (#60)

**Comment by boegel** [comment]
@deniskristak PR merged, ready for cleanup

**Comment by deniskristak** [comment]
cleaned up, closing
