### ISSUE TITLE
infercnvpy

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#59]
* link to support ticket: [#2022112360000701](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=101939)
* website: https://github.com/icbi-lab/infercnvpy
* installation docs: https://github.com/icbi-lab/infercnvpy#installation
* toolchain: `foss/2021b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/icbi-lab/infercnvpy/blob/main/pyproject.toml#L22
* effort: *(TBD)*

**Comment by boegel** [comment]
easyconfig PR open @ https://github.com/easybuilders/easybuild-easyconfigs/pull/16712/files

**Comment by boegel** [comment]
working easyconfigs added to [`58_scrublet`](https://github.com/vscentrum/vsc-software-stack/tree/main/58_scrublet), but need to check for compatibility with `vaeda` (#57), `scrublet` (#58), `solo` (#60)

**Comment by boegel** [comment]
need to check for compatibility with `vaeda` (#57), `scrublet` (#58), `solo` (#60)

**Comment by deniskristak** [comment]
this package is present in easybuild already on the correct toolchain (2022a)
https://github.com/easybuilders/easybuild-easyconfigs/blob/173ba43352ff2fedef40895ec2ba60ae76030b51/easybuild/easyconfigs/i/infercnvpy/infercnvpy-0.4.2-foss-2022a.eb

**Comment by boegel** [comment]
@deniskristak [PR merged](https://github.com/easybuilders/easybuild-easyconfigs/pull/17678), ready for cleanup

**Comment by deniskristak** [comment]
cleaned up, closing
