### ISSUE TITLE
solo

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#60]
* link to support ticket: [#2022112360000729](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=101941)
* website: https://github.com/calico/solo
* installation docs: https://github.com/calico/solo#quick-set-up
* toolchain: `foss/2021b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/calico/solo/blob/master/requirements.txt
* notes:
  * easyconfig for `scvi-tools` dependency already available via https://github.com/easybuilders/easybuild-easyconfigs/pull/16457 (see also https://github.com/hpcugent/eb_inuits/issues/248)
  * `PyTorch-Lightning` dependency implies `PyTorch` dependency, for which https://github.com/easybuilders/easybuild-easyconfigs/pull/16385 should get merged
* effort: *(TBD)*

**Comment by boegel** [comment]
working easyconfigs added to [`58_scrublet`](https://github.com/vscentrum/vsc-software-stack/tree/main/58_scrublet), but need to check for compatibility with `vaeda` (#57), `scrublet` (#58), `infercnvpy` (#59)

**Comment by boegel** [comment]
@deniskristak PR merged, ready for cleanup

**Comment by deniskristak** [comment]
cleaned up, closing
