### ISSUE TITLE
stardist

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#61]
* link to support ticket: [#2022112360000845](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=101953)
* website: https://github.com/stardist/stardist
* installation docs: https://github.com/stardist/stardist#installation
* toolchain:
  * [x] CPU version: `foss/2021b` => https://github.com/easybuilders/easybuild-easyconfigs/pull/17215
  * [x] GPU version: `foss/2021b+CUDA/11.4.1`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] TensorFlow (2.7.1)
* optional dependencies:
  * [x] [gputools](https://github.com/maweigert/gputools)
  * [x] [MLAEDT-3D](https://github.com/seung-lab/euclidean-distance-transform-3d)
* notes:
  * GUI app?
* effort: *(TBD)*

**Comment by stevenvdb** [comment]
I added an [easyconfig](https://github.com/vscentrum/vsc-software-stack/blob/099d98ba3c7f4b4d6a71d38344ceaa8df3bbb48c/61_stardist/stardist-0.8.3-foss-2021b.eb) that installs stardist _without_ GPU support (so without the optional gputools dependency). The authors of stardist recommend GPU support when training models, but not when only using pre-trained models. It depends on the user whether a GPU support is necessary. If so, I think pocl has to be installed with support for NVIDIA GPUs, which is currently not the case.
As far as I can tell, this is not a GUI app. Generating input files for stardist requires annotating images, and that is typically done with a GUI (with an application like Fiji).

**Comment by boegel** [comment]
It would be nice if we could have both a CPU-only and GPU easyconfig for `stardist`, but a CPU-only one is a good starting point.

Installing pocl with GPU support should not be a big problem I think, we have (old-ish) `pocl` easyconfigs that are built on top of CUDA.

**Comment by boegel** [comment]
`stardist/0.8.3-foss-2021b` is now installed on Tier-1 Hortense + Tier-2 clusters (CPU-only)

@stevenvdb We should also look into the GPU-capable installation? Are you up for looking into that too?
If so, do let me know if you need any help there...

**Comment by stevenvdb** [comment]
> @stevenvdb We should also look into the GPU-capable installation? Are you up for looking into that too? If so, do let me know if you need any help there...

I started looking into it. I am currently stuck building `Clang-13.0.1-GCCcore-11.2.0-CUDA-11.4.1.eb` with `NVPTX` as target, which I think is necessary for pocl with CUDA support. For some reason, the following lines to add it as a target don't seem to work:

https://github.com/easybuilders/easybuild-easyblocks/blob/ea83c9c14aa37f99af2e4cdaa73c89e669720092/easybuild/easyblocks/c/clang.py#L184-L185

Is it possible the dependencies are not yet loaded at that point?

**Comment by boegel** [comment]
@stevenvdb Indeed, dependencies are only loaded during the `prepare` step, not during the initialization of the easyblock, so you've hit a bug in the Clang easyblock, which was introduced in https://github.com/easybuilders/easybuild-easyblocks/pull/2800

**Comment by boegel** [comment]
@stevenvdb I've opened https://github.com/easybuilders/easybuild-easyblocks/issues/2871, feel free to add more relevant info in there (if you have any)

**Comment by boegel** [comment]
@stevenvdb Problem with Clang easyblock is fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/2873, please try again to install Clang with `eb --include-easyblocks-from-pr 2873 ...`

**Comment by stevenvdb** [comment]
Pull request for GPU version: https://github.com/easybuilders/easybuild-easyconfigs/pull/17283

**Comment by boegel** [comment]
PRs merged, software installed, cleanup of `61_stardist` in `wip` branch done, so closing...

Thanks for the help here @stevenvdb , and my apologies for letting it linger for so long...
