### ISSUE TITLE
SCENIC+

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#64]
* link to support ticket: [#2022112360001095](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=101978) + [#2024031360000536](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=150467) + [#2024071860000145](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=162543;ArticleID=569372)
* installation docs: https://github.com/aertslab/scenicplus#installing
* toolchain: `foss/2021b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/aertslab/scenicplus/blob/main/requirements.txt
* notes:
  * ...
* effort: *(TBD)*

**Comment by laraPPr** [comment]
Asked the user if the installing ... is still relevant for them. Will reopen the ticket if the user reaches out that this is still relevant for their research.

**Comment by laraPPr** [comment]
Reopening because the users still need it

**Comment by pavelToman** [comment]
Old PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19060

**Comment by pavelToman** [comment]
Open issue: https://github.com/aertslab/scenicplus/issues/440

**Comment by pavelToman** [comment]
PR
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21085
