### ISSUE TITLE
SimpleElastix

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#70]
* link to support ticket: [#2022120660000394](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=103228)
* website: https://simpleelastix.readthedocs.io
* installation docs: https://simpleelastix.readthedocs.io/GettingStarted.html
* toolchain: `foss/2022a`
* easyblock to use: `Bundle` (see existing easyconfig)
* required dependencies:
  * *(see existing easyconfig)*
* notes:
  * see existing easyconfig `SimpleElastix-1.1.0-foss-2019b-Python-3.7.4.eb`, just update toolchain + dependencies?
* effort: *(TBD)*

**Comment by ItIsI-Orient** [comment]
In the official [github repo](https://github.com/SuperElastix/SimpleElastix) they are saying, that SImpleElastix is no longer maintained at this repo and that it got integrated into SimpleITK. There is an (almost) up to date easyconfig for that. Could we just use that?

**Comment by boegel** [comment]
@ItIsI-Orient I'll install the latest `SimpleITK` we have, and inform the researcher, it indeed doesn't make sense to put a lot of effort into installing `SimpleElastix` if it's deprecated and replaced by `SimpleITK`
