### ISSUE TITLE
GRASP / GRASP-suite

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#71]
* link to support ticket: [#2022121460001351](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=104217) + [#2023040360000886](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=116673)
* website: https://bodenlab.github.io/GRASP-suite/project/graspcmd
* installation docs: https://bodenlab.github.io/GRASP-suite/project/graspcmd
* toolchain: `SYSTEM`
* easyblock to use: `PackedBinary`?
* required dependencies:
  * [x] Java 11
  * [x] Maven (build-only)
* notes:
  * actually need to install `bnkit` and then create a wrapper script for that
  * see for example [Tika](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/Tika/Tika-1.16.eb)
  * not the same `GRASP` as we currently have an easyconfig file for, so need to come up with a different name?
* effort: *(TBD)*

**Comment by boegel** [comment]
This should actually be pretty trivial, see "`asr.GRASP: How do I run it?`" section in https://bodenlab.github.io/GRASP-suite/project/graspcmd/, since the `grasp` command is just a wrapper around `bnkit.jar`.

To get a consistent download of `bnkit.jar`, we can download the `20230504` "version" via https://github.com/bodenlab/GRASP-suite/commit/97cceec83c4455408bddb12b2660032c14899c95

**Comment by pavelToman** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19665

**Comment by boegel** [comment]
@pavelToman easyconfig PR merged, software installed, ready for cleanup...
