### ISSUE TITLE
GLIMPSE

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#73]
* link to support ticket: [#2023010260000482](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=105352)
* website: https://github.com/odelaneau/GLIMPSE
* installation docs: https://odelaneau.github.io/GLIMPSE/docs/installation/build_from_source/compile_glimpse2
* toolchain: `GCC/12.2.0`
* easyblock to use: `MakeCp`?
* required dependencies:
  * ???
* notes:
  * try to install all tools, keep them in subdirectories?
  * no need to actually edit the Makefile as the docs suggest, just pass argument to `make` via `buildopts`
* effort: *(TBD)*

**Comment by boegel** [comment]
see https://github.com/easybuilders/easybuild-easyconfigs/pull/18153

**Comment by boegel** [comment]
@laraPPr We can install the existing easyconfig to close this

**Comment by laraPPr** [comment]
installed and closed ticket
