### ISSUE TITLE
Cellpose

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#76]
* link to support ticket: [#2023010460001085](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=105575)
* website: https://cellpose.readthedocs.io
* installation docs: https://cellpose.readthedocs.io/en/latest/installation.html
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/MouseLand/cellpose/blob/main/setup.py
* optional dependencies:
  * [ ] ...
* notes:
  * see easyconfig for old version of `Cellpose` @ https://github.com/easybuilders/easybuild-easyconfigs/pull/13703
  * should be compatible with QuPath (#75)
* effort: *(TBD)*

**Comment by deniskristak** [comment]
here we go:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/18002
* https://github.com/easybuilders/easybuild-easyconfigs/pull/18003
* https://github.com/easybuilders/easybuild-easyconfigs/pull/18004

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/18004 merged, PR for CUDA version opened at https://github.com/easybuilders/easybuild-easyconfigs/pull/18152, so ready for cleaning & closing...

**Comment by deniskristak** [comment]
cleaned up, closing
