### ISSUE TITLE
alleleIntegrator

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#77]
* link to support ticket: [#2023011160001679](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=106344)
* website: https://github.com/constantAmateur/alleleIntegrator
* installation docs: https://github.com/constantAmateur/alleleIntegrator#installation
* toolchain: `GCC/11.3.0`
* easyblock to use: `RPackage`
* required dependencies:
  * [ ] alleleCount ([see existing old easyconfig](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/a/alleleCount/alleleCount-4.0.0-GCCcore-6.4.0.eb))
  * [x] BCFtools
  * [x] parallel
  * [ ] [ASCAT](https://github.com/VanLoo-lab/ascat)
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*

**Comment by ItIsI-Orient** [comment]
PR open:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17923

**Comment by boegel** [comment]
PR merged, ready for cleanup
