### ISSUE TITLE
CatLearn

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#78]
* link to support ticket: [#2023011660001321](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=106794)
* website: https://catlearn.readthedocs.io
* installation docs: https://catlearn.readthedocs.io/en/latest/installation.html
* toolchain: `intel/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] ASE
  * [x] GPAW
  * and more, see https://github.com/SUNCAT-Center/CatLearn/blob/master/requirements.txt
* notes:
  * ...
* effort: *(TBD)*

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/17122

**Comment by PetrKralCZ** [comment]
- other install methods
- container image/recipe: https://github.com/SUNCAT-Center/CatLearn/blob/master/Dockerfile
