### ISSUE TITLE
sympy w/ intel/2021b

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#79]
* link to support ticket: [#2023011660001731](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=106835)
* website: https://docs.sympy.org
* installation docs: https://docs.sympy.org/latest/install.html
* toolchain: `intel/2021b`
* easyblock to use: `PythonPackage`
* required dependencies:
  * see existing `sympy` easyconfigs
* notes:
  * ...
* effort: *(TBD)*

**Comment by boegel** [comment]
WIP easyconfigs available, but test suite crashes hard with:

```
INTEL MKL ERROR: /user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/zen2-ib/software/imkl/2021.4.0/mkl/2021.4.0/lib/intel64/libmkl_vml_def.so..
1: undefined symbol: mkl_lapack_dspevd.
Intel MKL FATAL ERROR: cannot load libmkl_vml_def.so.1.
```

**Comment by boegel** [comment]
Issue opened upstream for this: https://github.com/sympy/sympy/issues/24651

We can try:

* running the tests in verbose mode:
  ```
  python setup.py test --verbose
  ```

* running the tests differently, this may work (based on https://github.com/sympy/sympy/blob/master/bin/test_tensorflow.py):
  ```
  python -c "import sympy; sympy.test('sympy/utilities/tests/test_lambdify.py', verbose=True)"
  ```

**Comment by boegel** [comment]
sympy with `intel/2021b` is also required for DensPart (issue #50)

**Comment by boegel** [comment]
problem with `numexpr` fixed with https://github.com/easybuilders/easybuild-easyblocks/pull/2897

**Comment by boegel** [comment]
(WIP) PR for `sympy` with `intel/2022a`: https://github.com/easybuilders/easybuild-easyconfigs/pull/17442

**Comment by boegel** [comment]
`sympy` with `intel/2021b`: https://github.com/easybuilders/easybuild-easyconfigs/pull/17467

**Comment by PetrKralCZ** [comment]
- other install methods
- conda: https://anaconda.org/anaconda/sympy
- easyconfigs outside EasyBuild:
    - https://github.com/ComputeCanada/easybuild-easyconfigs/tree/2cfa54b282b984536ed38a0b261e54a90ce7da67/easybuild/easyconfigs/s/sympy
    - https://github.com/easybuilders/JSC/tree/9802fb890cd0259d2015868d675422f1022c4703/Golden_Repo/s/sympy
    - https://github.com/bear-rsg/easybuild-easyconfigs/tree/4db27ea6cc24ee305f8da28609952597bdc359f9/easybuild/easyconfigs/s/sympy

**Comment by boegel** [comment]
PR merged, software installed, closing...
