### ISSUE TITLE
RNA-Bloom

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#81]
* link to support ticket: [#2023011960000978](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=107282)
* website: https://github.com/bcgsc/RNA-Bloom
* installation docs: https://github.com/bcgsc/RNA-Bloom#installation-wrench
* toolchain: `GCC/12.2.0` (or `GCC/11.3.0` if needed)
* easyblock to use: `Tarball` *(see existing easyconfig)*
* required dependencies:
  * *(see existing easyconfig)*
* notes:
  * ...
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
- other install methods
- conda: https://anaconda.org/bioconda/rnabloom
- easyconfigs outside EasyBuild:
    - https://github.com/ComputeCanada/easybuild-easyconfigs/tree/2cfa54b282b984536ed38a0b261e54a90ce7da67/easybuild/easyconfigs/r/RNA-Bloom
    - https://github.com/bear-rsg/easybuild-easyconfigs/tree/4db27ea6cc24ee305f8da28609952597bdc359f9/easybuild/easyconfigs/r/RNA-Bloom

**Comment by laraPPr** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/19925

**Comment by laraPPr** [comment]
installed and OTRS ticket closed
