### ISSUE TITLE
CatMAP

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#82]
* link to support ticket: [#2023012460001298](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=107812)
* website: https://catmap.readthedocs.io
* installation docs: https://catmap.readthedocs.io/en/latest/installation.html
* toolchain: `foss/2022a`
* easyblock to use: *(see existing easyconfig)*
* required dependencies:
  * *(see existing easyconfig)*
* notes:
  * ...
* effort: *(TBD)*

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/17203

**Comment by PetrKralCZ** [comment]
- other install methods
- easyconfigs outside EasyBuild:
    - https://github.com/ComputeCanada/easybuild-easyconfigs/tree/2cfa54b282b984536ed38a0b261e54a90ce7da67/easybuild/easyconfigs/c/CatMAP
    - https://github.com/bear-rsg/easybuild-easyconfigs/tree/4db27ea6cc24ee305f8da28609952597bdc359f9/easybuild/easyconfigs/c/CatMAP

**Comment by laraPPr** [comment]
Installed and OTRS ticket closed
