### ISSUE TITLE
OpenFold

### ISSUE THREAD

**Issue by smoors** [vscentrum/vsc-software-stack#84]
* link to support ticket: [#2023012660000446](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=108093)
* website: ...
* installation docs: ...
* toolchain: `foss-2021a-CUDA-11.3.1`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * requested by Carl Mensch for Hydra and Hortense
  * the easyconfig `OpenFold-1.0.1-foss-2021a-CUDA-11.3.1.eb` already exists, but it's not usable standalone: the OpenMM dep should be CUDA enabled and the parameters are not available
* effort: *(TBD)*

**Comment by smoors** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/17206

**Comment by boegel** [comment]
@smoors https://github.com/easybuilders/easybuild-easyconfigs/pull/17206 is merged + `OpenFold/1.0.1-foss-2021a-CUDA-11.3.1` is installed on Tier-1 Hortense
