### ISSUE TITLE
Open-SURFEX

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#85]
* link to support ticket: [#2023012660001141](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=108163) + [#2023030160001274](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=112355)
* website: https://www.umr-cnrm.fr/surfex/spip.php?rubrique141
* installation docs: https://www.umr-cnrm.fr/surfex/spip.php?article191
* toolchain: `foss/2022a`
* easyblock to use: `ConfigureMake` (?)
* required dependencies:
  * HDF5
  * netCDF + netCDF-Fortran
  * cURL
  * Szip
  * zlib
  * M4
  * grib_api
  * ecCodes
* notes:
  * source tarballs for required dependencies are included in `src/LIB/*tar.gz`, we should make sure that those are *not* used, and use proper dependencies instead...
* effort: *(TBD)*

**Comment by deniskristak** [comment]
many hardcoded paths, super-strict versions, I am going to do a whole bunch of patching...

**Comment by boegel** [comment]
@deniskristak Maybe try to get it working with the included stuff first, then start checking how much work it would be to flesh things out and use proper dependencies?

**Comment by deniskristak** [comment]
i emailed the developer:
```
Hello,
as a part of an Easybuild project (https://easybuilders.github.io/), I am trying to build this project with some differences than what is written in readme.
First of all, I need to use my own installations of all dependencies. That means everything from the LIB directory, software like eccodes, netcdf4, grib_api ...
Secondly, I need to specify a custom installation directory, so that no files go to `/usr/bin/` etc., which I see is currently hardcoded in the configure script and makefiles...
I've noticed there is a forked version on github (https://github.com/joewkr/open-SURFEX) that uses CMake and is close to what I would need, however, they use the second latest (8.1) version, which is a little inconvenient for me.
However, I would like to ask you first - is there anything like that forked version, but coming from you, the original developers ? 
Have you, by any chance, tested the forked version and have any comments about it?
Thank you dearly for your time and for the answer.
Denis
```

they replied:
```
Hi Denis

We do not use GitHub for SURFEX but have our own GIT server, with limited developer access.
We make available the open source version as a tarball (http://www.umr-cnrm.fr/surfex/data/OPEN-SURFEX/open_surfex_v8_1_20220817.tar.gz) and the version you refer to (https://github.com/joewkr/open-SURFEX) is the initiative of a developer with whom we collaborate.

Best regards
Patrick
```

**Comment by boegel** [comment]
Small clarification: the original request is for version 8.1 explicitly, but maybe they're also happy with a 9.0 installation...

**Comment by boegel** [comment]
We now also have a 2nd installation request for Open-SURFEX (v8.1), just to throw some oil on the fire...

**Comment by pavelToman** [comment]
There is Open-Surfex-8.1 with CMake build system here: https://github.com/joewkr/open-SURFEX/tree/master

**Comment by pavelToman** [comment]
PR:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21975

**Comment by laraPPr** [comment]
How much time did you spend on this @pavelToman

**Comment by laraPPr** [comment]
Reminder for after Holidays: started installation on Tier-2

**Comment by pavelToman** [comment]
> How much time did you spend on this @pavelToman

7h

**Comment by laraPPr** [comment]
installed and informed user, ready for cleanup
