### ISSUE TITLE
Slicer

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#87]
* link to support ticket: [#2022051860000447](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=80327)
* website: https://www.slicer.org
* installation docs: https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html#installing-3d-slicer
* toolchain: `foss/2022a`
* easyblock to use: `CMakeMake`
* required dependencies:
  * a lot, see https://github.com/Slicer/Slicer/tree/main/SuperBuild
* notes:
  * ...
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
- other install methods
pre-built binaries: https://download.slicer.org/
- easyconfigs outside EasyBuild: https://github.com/ComputeCanada/easybuild-easyconfigs/tree/2cfa54b282b984536ed38a0b261e54a90ce7da67/easybuild/easyconfigs/s/Slicer

**Comment by laraPPr** [comment]
Asked the user if the installing Slicer is still relevant for them. Will reopen the ticket if the user reaches out that this is still relevant for their research.
