### ISSUE TITLE
Omnipose

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#89]
* link to support ticket: [#2023013160000892](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=108644)
* website: https://omnipose.readthedocs.io/
* installation docs: https://omnipose.readthedocs.io/installation.html
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] [cellpose-omni](https://github.com/kevinjohncutler/cellpose-omni)
  * see https://github.com/kevinjohncutler/omnipose/blob/main/setup.py
* notes:
  * ...
* effort: *(TBD)*

**Comment by boegel** [comment]
Should also support GPUs

**Comment by boegel** [comment]
PR for Omnipose: https://github.com/easybuilders/easybuild-easyconfigs/pull/18402 (CPU-only)

**Comment by boegel** [comment]
PR for Omnipose with GPU support: https://github.com/easybuilders/easybuild-easyconfigs/pull/18637

**Comment by boegel** [comment]
@deniskristak ready for cleanup & closing

**Comment by deniskristak** [comment]
cleaned up, closing
