### ISSUE TITLE
vitessce-python

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#90]
* link to support ticket: [#2023020160000937](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=108804)
* website: https://vitessce.github.io/vitessce-python
* installation docs: https://vitessce.github.io/vitessce-python/#installation
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/vitessce/vitessce-python/blob/main/setup.py
* notes:
  * ...
* effort: *(TBD)*

**Comment by boegel** [comment]
@deniskristak PR merged, ready for cleanup

**Comment by deniskristak** [comment]
cleaned up, closing
