### ISSUE TITLE
vitessceR

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#91]
* link to support ticket: [#2023020160000946](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=108805)
* website: https://vitessce.github.io/vitessceR
* installation docs: https://vitessce.github.io/vitessceR/#installation
* toolchain: `RPackage`
* easyblock to use: `foss/2022a`
* required dependencies:
  * ???
* notes:
  * ...
* effort: *(TBD)*

**Comment by deniskristak** [comment]
@boegel ready to be reviewed

**Comment by boegel** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/17525 merged, ready for cleanup!

**Comment by deniskristak** [comment]
finished, closing
