### ISSUE TITLE
synthcity

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#93]
* link to support ticket: [#2023020360000611](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=109040)
* website: https://github.com/vanderschaarlab/synthcity
* installation docs: https://github.com/vanderschaarlab/synthcity#rocket-installation
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [x] Python
  * + see https://github.com/vanderschaarlab/synthcity/blob/main/prereq.txt
* notes:
  * ...
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17321
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17537
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17544
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17545
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17570
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17571
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17572
