### ISSUE TITLE
FunGAP

### ISSUE THREAD

**Issue by lexming** [vscentrum/vsc-software-stack#95]
* link to support ticket: INC0132096 (VUB)
* website: https://github.com/CompSynBioLab-KoreaUniv/FunGAP
* installation docs: https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/master/INSTALL.md
* toolchain: foss/2022a
* easyblock to use: Tarball
* required dependencies:
  * [x] [Hisat2](https://ccb.jhu.edu/software/hisat2/index.shtml) v2.2.1
  * [x] [Trinity](https://github.com/trinityrnaseq/trinityrnaseq) v2.12.0
  * [x] [RepeatModeler](http://www.repeatmasker.org/RepeatModeler/) v2.0.1 > v2.0.4
  * [x] [Maker](http://www.yandell-lab.org/software/maker.html) v3.01.03
  * [x] [GeneMark-ES/ET](http://topaz.gatech.edu/GeneMark/license_download.cgi) v4.65_lic
  * [x] [Augustus](https://github.com/Gaius-Augustus/Augustus) v3.4.0
  * [x] [Braker](http://exon.gatech.edu/braker1.html) v2.1.5
  * [x] [BUSCO](https://busco.ezlab.org/) v5.1.2
  * [x] [Pfam_scan](https://www.ebi.ac.uk/seqdb/confluence/display/THD/PfamScan) v1.6
  * [x] [BLAST](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=Download) v2.11.0 > v2.13.0
  * [x] [Samtools](http://www.htslib.org/download/) v1.10 > v1.16.1
  * [x] [Bamtools](https://github.com/pezmaster31/bamtools) v2.5.1 > v2.5.2
  * [x] [Pfam](https://pfam.xfam.org/) release **34.0**
* notes:
  * some of the dependencies are licensed
* effort: annoying

**Comment by smoors** [comment]
https://github.com/easybuilders/easybuild-easyconfigs/pull/17281

**Comment by lexming** [comment]
More PRs:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17292
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17290

**Comment by smoors** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17317
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17339

**Comment by lexming** [comment]
Many more PRs for Trinity:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17378
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17383
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17387
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17384
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17382
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17403
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17408

**Comment by lexming** [comment]
Last dependency:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17530

**Comment by lexming** [comment]
More PRs with fixes:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17631
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17629

**Comment by lexming** [comment]
Last PR:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17652
