### ISSUE TITLE
scHiCExplorer

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#96]
* link to support ticket: [#2023020860001021](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=109517)
* website: https://schicexplorer.readthedocs.io
* installation docs: https://schicexplorer.readthedocs.io/en/latest/content/installation.html
* toolchain: `foss/2022a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] HiCExplorer
  * [ ] HiCMatrix
  * [ ] cooler
  * [ ] sparse-neighbors-search
* notes:
  * ...
* effort: *(TBD)*

**Comment by PetrKralCZ** [comment]
PR for the `imbalanced-learn` dependency:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/17321

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/17334
