### ISSUE TITLE
Q-Chem

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#99]
* link to support ticket: [#2023021060000938](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=109755)
* website: https://www.q-chem.com/
* installation docs: https://manual.q-chem.com/latest/Ch2.S1.SS1.html
* toolchain: `SYSTEM`?
* easyblock to use: `??`
* required dependencies:
  * ??
* notes:
  * already installed on Hydra @ VUB
* effort: *(TBD)*

**Comment by boegel** [comment]
@lexming @smoors The person who requested this mentioned that `Q-chem` is already installed on Hydra, do you have any more info on this?

**Comment by lexming** [comment]
It's commercial software with a poorly designed installer that asks questions, downloads binaries, calls home to verify your purchase order and triggers the generation of your license file.

To properly handle this install with EB you would need to develop a new easyblock, which we have not done. We installed this software manually and have an [easyconfig to setup the environment of the Q-Chem](https://github.com/lexming/easybuild-easyconfigs/blob/vub-hpc/easybuild/easyconfigs/q/Q-Chem/Q-Chem-6.0.2.eb).

**Comment by lexming** [comment]
One more thing, if the request comes from the ALGC group in VUB, they have a Flexnet license. Q-chem ships its own module for the flexnet server with the particularity that it requires the list of users allowed to use the software. This list has to be explicitly defined in a configuration file in the license server. A group name is not allowed.
Maybe it will be easier to just use our license server, but it is not reachable from outside VUB, so we would need to make some changes there.

**Comment by boegel** [comment]
@lexming I've moved the ticket into the `Infrastructuur::HPC::Tier1` queue, so you can access it.

The request indeed comes from the ALGC group @ VUB.

Any chance you can help them with this?

**Comment by lexming** [comment]
@boegel sure, we continue in the ticket

**Comment by lexming** [comment]
Added [Q-Chem-6.0.2.eb](https://github.com/vscentrum/vsc-software-stack/blob/ba7dda80b3030235446b5743ff99d7a76d76fe0e/99_Q-Chem/Q-Chem-6.0.2.eb) which is the easyconfig that we use to set the environment for Q-Chem. Installation is done manually.
